// fukushima (95件)
(function(){
  const data = [
    { name: "エムエムエルラーナーズ株式会社", type: "登録支援機関", address: "福島県福島市森合字台の前１８－４", tel: "0245574548", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "一般社団法人ＳＮＤ", type: "登録支援機関", address: "福島県いわき市好間町榊小屋字原７９番地", tel: "0246881543", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "遠藤　寬士", type: "登録支援機関", address: "福島県郡山市田村町金屋字宝蔵９１番地", tel: "09064560066", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "野崎　富夫", type: "登録支援機関", address: "福島県岩瀬郡鏡石町岡ノ内１１１ 野崎行政書士事務所", tel: "0248923501", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-5" },
    { name: "ぐるっと株式会社", type: "登録支援機関", address: "福島県いわき市中央台高久一丁目３６番地の６", tel: "0246686223", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社トライアンフ", type: "登録支援機関", address: "福島県須賀川市西山寺町２９３番地", tel: "0248723301", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-4" },
    { name: "協同組合さくら人材支援センター", type: "登録支援機関", address: "福島県福島市さくら三丁目１番地の２６", tel: "0245635880", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "マニュファクチャリングサービス協同組合", type: "登録支援機関", address: "福島県いわき市平上荒川字長尾１１５番地の３　第３すずビル２０２", tel: "0246886228", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "福島国際交流事業協同組合", type: "登録支援機関", address: "福島県福島市栄町６番５号南条ビルA館５階", tel: "0245731270", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社インパルス", type: "登録支援機関", address: "福島県福島市森合町１３－２８", tel: "0245341175", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社アイ・パートナー", type: "登録支援機関", address: "福島県須賀川市八幡山２３２番地１", tel: "0248639050", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-4" },
    { name: "株式会社エージェーシー", type: "登録支援機関", address: "福島県郡山市駅前一丁目９番１５号オフィス古泉ビル３階", tel: "0249260551", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "きずな国際交流協同組合", type: "登録支援機関", address: "福島県須賀川市堀底町７番地コーポタナカ１０２号", tel: "0248946158", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-4" },
    { name: "国際経済交流協同組合", type: "登録支援機関", address: "福島県岩瀬郡鏡石町高久田１０２番地１", tel: "0248638806", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-5" },
    { name: "サンライズ事業協同組合", type: "登録支援機関", address: "福島県いわき市平下神谷字御城１３２番地の７", tel: "0246386144", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社成栄", type: "登録支援機関", address: "福島県いわき市四倉町字芳ノ沢１番地の２７", tel: "0246385881", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "ハッピーライフコーポレーション株式会社", type: "登録支援機関", address: "福島県いわき市中央台飯野三丁目６番地の１　アークガーデンＣ１０１", tel: "0246850805", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "佐藤　勝伸（佐藤アンドパートナーズ行政書士事務所）", type: "登録支援機関", address: "福島県双葉郡浪江町大字権現堂字御殿南２６番地９", tel: "05013289691", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-6" },
    { name: "伊藤　仁平（伊藤仁平行政書士事務所）", type: "登録支援機関", address: "福島県いわき市植田町本町三丁目９番地の１", tel: "0246633518", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "ＡＳＥＡＮ技術支援事業協同組合", type: "登録支援機関", address: "福島県郡山市富田西四丁目３５番地", tel: "0249838528", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "いわきビジネスサポート事業協同組合", type: "登録支援機関", address: "福島県いわき市泉町下川字宮ノ下１７１番地の１", tel: "0246688831", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市小原田一丁目１７番２４号", tel: "0249545007", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県白河市十文字５番地１４", tel: "0248212345", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県会津若松市飯寺北二丁目１番１６号", tel: "0242292575", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市安積町日出山三丁目１９５番地", tel: "0249428045", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県西白河郡矢吹町北浦１３６番地１", tel: "0248411001", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県白河市北堀切７番地５", tel: "0248574104", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県東白川郡塙町大字塙字大町三丁目３１番地１", tel: "0247430371", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県須賀川市並木町２８３番地５", tel: "0248637033", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市南矢野目字番城前７番地の２", tel: "0245727715", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平字作町三丁目４－６、２Ｆ", tel: "0246855837", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平字大町２０－８八百真大町ビル２０１", tel: "0246385093", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県西白河郡西郷村字豊作西１１番地", tel: "0248218530", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市野田町六丁目７番地の１４ＳＴビル２０１号", tel: "0245725727", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市小名浜字辰巳町４１番地", tel: "0246535751", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市勿来町大高高松３６番地５", tel: "08011103561", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市大町一丁目９番１３号８階B区画", tel: "0354221560", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市山居４１－２", tel: "0245455640", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県東白川郡棚倉町大字棚倉字新町３２番地２", tel: "0247579997", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市郷ケ丘二丁目９２番地の１１", tel: "0246281044", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市桑野一丁目４番７号", tel: "0249336063", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市富久山町福原字西原４７番地", tel: "0249736969", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市本内字南街道下１番地１", tel: "0245535233", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市常磐西郷町落合２６５番地", tel: "0246434532", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市富久山町久保田字古町２５５番地レジデンスミナミⅡ１０１号", tel: "0249839745", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県伊達市保原町字中瀬町１０２番地の１", tel: "0245739740", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市森合町１５番１１号", tel: "0245295806", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県田村市常葉町常葉字中町４８番地", tel: "0247738926", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市清水町字寺ノ上２０番地の１", tel: "0245494245", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市東浜町２４番１３号", tel: "09026035461", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市中岡町六丁目１２番地の１４", tel: "0246631110", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県相馬郡新地町谷地小屋字樋掛田５８番地１", tel: "0244266506", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市野田町６丁目７－１４ＳＴビル２０２号", tel: "0245736291", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市小島町一丁目８番地の７", tel: "0246386636", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市赤木町１４番４号", tel: "0249537305", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市泉町下川字畑中１５６番地の１", tel: "0246560695", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県須賀川市和田字新池４５－２Ｆ", tel: "0248752380", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市安積二丁目６番地の１", tel: "0249533350", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市田村町下行合字石山田１１６番地", tel: "09037522920", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平中平窪東高砂５－５ １０３", tel: "08018192650", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県白河市菅生舘１５５番地１０", tel: "0248210770", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県白河市高山７７番地", tel: "0248219975", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市八島町１２番２０号ＢＣビル５階", tel: "0245724591", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県南相馬市鹿島区鹿島字石川内４４番地", tel: "0244265378", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県白河市新白河三丁目３番ア・ラモード・アラ１Ｆ", tel: "0248210458", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県西白河郡矢吹町神田東３０１番地４", tel: "0248219631", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市小名浜野田字田中１０６番地", tel: "0246588472", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市笹谷字稲場２７－１７リヴェール１０３号室", tel: "0245635515", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県白河市昭和町１５６番地１トレンドビル", tel: "0248217380", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市本町４番８号", tel: "0245212612", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県会津若松市中央一丁目５番２９号", tel: "0242241551", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市横塚三丁目４番７号横塚貸事務所２０３号室", tel: "0249534502", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県岩瀬郡鏡石町高久田１０２番地１", tel: "0248726552", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県南会津郡南会津町古町字居平５番地５", tel: "0241728155", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平六町目１番地１１", tel: "0246855944", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平字愛谷町一丁目１番地の７", tel: "0246389907", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市早稲町４ー１６", tel: "0245730600", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県相馬市中村字北町１３９番地の２", tel: "0244267572", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市中町１－３０", tel: "0245735885", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市常磐西郷町落合２７３番地１", tel: "0246848125", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平中平窪東高砂５番地５－２０１号", tel: "08018192650", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県白河市北堀切７番地５", tel: "09062213647", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平字愛谷町四丁目８番地の３", tel: "0246210511", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市安積北井一丁目２４番地", tel: "0249556251", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平赤井字大作場１３番地", tel: "0246253127", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県須賀川市向陽町２７５番地", tel: "08018060478", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市久之浜町久之浜字水上３番地の１３ ハイム水上２-Ｄ", tel: "08011359132", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市池ノ台１５番１５号三浦ビル１Ｆ", tel: "0249352590", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県いわき市平字二町目８番地", tel: "0246223122", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市台新２丁目２６番１５号", tel: "0249224411", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市田村町金屋字冬室１１０番１０", tel: "0249537537", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市田村町桜ヶ丘二丁目６５番地１", tel: "0249556652", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県田村郡三春町桜ケ丘三丁目３番地の６", tel: "0247627715", visa: ["tokutei1"], prefId: "fukushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県福島市成川字仲ノ内１０－１", tel: "0245735151", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福島県郡山市朝日二丁目２３－６", tel: "0249545910", visa: ["tokutei1"], prefId: "fukushima", districtId: "fukushima-3" },
  ];
  if (window.VISA_DATA && VISA_DATA.agencies) {
    VISA_DATA.agencies.push(...data);
  } else {
    window._pendingAgencies = window._pendingAgencies || [];
    window._pendingAgencies.push(...data);
  }
})();