// 登録支援機関データ - fukui (64件)
(function(){
  const data = [
    { name: "株式会社フォーリーフ", type: "登録支援機関", address: "福井県福井市渕４丁目１２０８ ア裏EAST １F", tel: "0776635799", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "アスカ株式会社", type: "登録支援機関", address: "福井県福井市月見四丁目４番５号", tel: "0776978247", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社キャリアネットワーク", type: "登録支援機関", address: "福井県福井市新田塚一丁目２５番１８号", tel: "0776250864", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "ＪＡ・ＶＩブリッジ合同会社", type: "登録支援機関", address: "福井県鯖江市桜町１－３－９", tel: "0778435669", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "ユニバーサルジャパン協同組合", type: "登録支援機関", address: "福井県福井市文京５丁目１７番３号", tel: "0776301689", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "行政書士法人坪川事務所", type: "登録支援機関", address: "福井県福井市日之出三丁目９番３号京福日之出ビル２階", tel: "0776236433", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "技能開発協同組合", type: "登録支援機関", address: "福井県福井市高木町第４号１０番地の３", tel: "0776570102", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社オーシンテクノ", type: "登録支援機関", address: "福井県越前市矢放町１４－２２", tel: "0778240300", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社コムスター", type: "登録支援機関", address: "福井県福井市花堂南一丁目５番１６号", tel: "0776336780", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "ＨＦＣ事業協同組合", type: "登録支援機関", address: "福井県福井市西開発一丁目２４０１番地", tel: "0776978920", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "ＩＸＰＬＥＡＳ株式会社", type: "登録支援機関", address: "福井県越前市家久町第２４号９番地の２", tel: "0778239190", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "ハイネスワーク協同組合", type: "登録支援機関", address: "福井県越前市家久町５３－９－１　コンパビル２階", tel: "0778427858", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "ＲＴＭ株式会社", type: "登録支援機関", address: "福井県福井市新田塚二丁目１１４番３８号", tel: "09016394066", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "協同組合若越", type: "登録支援機関", address: "福井県福井市舟橋三丁目１００１番地", tel: "0776500222", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "エスパス協同組合", type: "登録支援機関", address: "福井県坂井市三国町三国東六丁目５番５号", tel: "0776826033", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "北陸対外事業協同組合", type: "登録支援機関", address: "福井県福井市成和一丁目２４１４番地１", tel: "0776233335", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "協同組合ヒューテック", type: "登録支援機関", address: "福井県福井市竹生町１９号１５番地の３", tel: "0776982873", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "一般社団法人福井県外国人支援センター", type: "登録支援機関", address: "福井県福井市松本二丁目３７番１３号", tel: "0776260456", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社Ｔｏｒｉｓｅ　Ｊａｐａｎ", type: "登録支援機関", address: "福井県あわら市花乃杜一丁目２９番１６号", tel: "0776431270", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "広域技能協同組合", type: "登録支援機関", address: "福井県坂井市丸岡町猪爪二丁目７１５番地", tel: "0776676011", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県大野市月美町１０番７号", tel: "0779691200", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県越前市武生柳町６番３０号", tel: "0778213852", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県吉田郡永平寺町東古市第２号２３番地１", tel: "0776436883", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県大野市明倫町３番３７号", tel: "0779661230", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市学園三丁目１番２１号", tel: "0776891017", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県小浜市小浜広峰１０８番地", tel: "0770321000", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県敦賀市中８１号岩ケ鼻１番地１３", tel: "0770371743", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県鯖江市杉本町第１８号８番地１４", tel: "0778251151", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県越前市芝原５丁目４番１６号", tel: "0778213799", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県丹生郡越前町道口９ー４２", tel: "0778370001", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県坂井市三国町宿一丁目１７番３３号", tel: "0776820261", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県坂井市丸岡町一本田第１６号２２番地２", tel: "0776655774", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県吉田郡永平寺町松岡上合月第３９号１番地１", tel: "0776616601", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市茱崎町第１４号３２番地", tel: "0776892316", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県越前市千福町６８番地の５", tel: "0778213771", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県越前市塚町３０６", tel: "0778435401", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市北四ツ居二丁目１３番３号", tel: "0776767918", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市高屋町第４２号８７番地２", tel: "0776550129", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市東今泉町第５号３番地２５", tel: "05030922646", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市大手三丁目７番１号", tel: "0776244685", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県大野市月美町１４番４号", tel: "0779644373", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市春日二丁目８番１２号", tel: "0776361307", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市渡町５１２番地１", tel: "0776764313", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市成和二丁目４０１番地", tel: "0776976858", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県坂井市春江町寄安第１０号８番地", tel: "0776510536", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市松本一丁目３６番１５号", tel: "0776520010", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県大野市美川町６番１９号", tel: "0779644450", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県丹生郡越前町乙坂第１９号１番地１", tel: "0778340434", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県大野市東中野一丁目５０１番地", tel: "0779655669", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県あわら市上番第３３号２番地１", tel: "0776766542", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県小浜市飯盛第２１号４５番地の７", tel: "0770645292", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県鯖江市新横江二丁目３番４号めがね会館７階", tel: "0776528761", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県大野市篠座６６号５番地", tel: "0779645322", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市光陽二丁目３番２２号", tel: "0776242339", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県あわら市花乃杜一丁目２９番１６号", tel: "0776430351", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市中央三丁目１４番３号幸橋グランデＣＨＡ１Ｆ", tel: "09043254244", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県越前市府中三丁目２番２６号２階", tel: "07023638668", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県敦賀市呉竹町一丁目２３番６号", tel: "0770371754", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市新田塚一丁目２５番１８号", tel: "0776979008", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市開発町第８号２番地の３", tel: "0776880555", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県鯖江市本町３丁目２番３６号", tel: "09030380178", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県福井市宝永３丁目３４号２４番地", tel: "0776273050", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県丹生郡越前町高佐第３６号１７番地", tel: "09037477626", visa: ["tokutei1"], prefId: "fukui", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "福井県あわら市田中々１－１０－３", tel: "09022674311", visa: ["tokutei1"], prefId: "fukui", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();