// 登録支援機関データ - gifu (261件)
(function(){
  const data = [
    { name: "坂口　裕祐（行政書士坂口事務所）", type: "登録支援機関", address: "岐阜県各務原市那加日新町６丁目３番オフィス２１　３－C", tel: "0583819031", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "陳　少玲", type: "登録支援機関", address: "岐阜県岐阜市六条東一丁目６番１８－３０３号（交告第３ビル）", tel: "09099191388", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "東海ビジネス株式会社", type: "登録支援機関", address: "岐阜県岐阜市大工町２３番地", tel: "0582159485", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "栗本　元治（栗本行政書士事務所・栗本経営労務管理事務所）", type: "登録支援機関", address: "岐阜県岐阜市則武２６４８番地", tel: "0582137009", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "ＬＩＮＫ株式会社", type: "登録支援機関", address: "岐阜県岐阜市加納新本町三丁目３番地", tel: "0582778888", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワールド", type: "登録支援機関", address: "岐阜県岐阜市橋本町二丁目８番地", tel: "0582553066", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "協同組合アクシス", type: "登録支援機関", address: "岐阜県岐阜市六条大溝三丁目１番１６号", tel: "0582016351", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "アジアリサーチ協同組合", type: "登録支援機関", address: "岐阜県岐阜市鷺山８３９番地１", tel: "0582323309", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "中央ネット協同組合", type: "登録支援機関", address: "岐阜県羽島市小熊町島三丁目６９番地１０３号", tel: "0582167082", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "さくら事業協同組合", type: "登録支援機関", address: "岐阜県可児市徳野南一丁目１６０番地", tel: "0574600011", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "東商テクノ株式会社", type: "登録支援機関", address: "岐阜県岐阜市長住町一丁目６番地ヒノヨシビル", tel: "0582157703", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "テクニカル事業協同組合", type: "登録支援機関", address: "岐阜県岐阜市入舟町三丁目３２番地３", tel: "0582405188", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社トラストコーポレーション", type: "登録支援機関", address: "岐阜県大垣市外渕２丁目１７５", tel: "0584848008", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社Ｂ＆Ｂ", type: "登録支援機関", address: "岐阜県岐阜市中鶉１丁目１２７番地１", tel: "0582734530", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "ＦＩＬ協同組合", type: "登録支援機関", address: "岐阜県海津市平田町幡長１５１５番地１", tel: "05088872578", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "岐阜コネクトサービス協同組合", type: "登録支援機関", address: "岐阜県岐阜市春近古市場南６番地１", tel: "0582295641", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "アシスト協同組合", type: "登録支援機関", address: "岐阜県美濃加茂市草笛町４丁目９番３号", tel: "0574662121", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社笑顔いちばん", type: "登録支援機関", address: "岐阜県各務原市小佐野町六丁目６２番地", tel: "0582168230", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社サクセススタッフ", type: "登録支援機関", address: "岐阜県美濃加茂市太田町１７１番地", tel: "0574230208", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "中央国際協同組合", type: "登録支援機関", address: "岐阜県養老郡養老町五日市４８０番地２５", tel: "0584717345", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "協同組合イノベーション", type: "登録支援機関", address: "岐阜県安八郡神戸町神戸１１１２－１", tel: "0584848883", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "未来創造協同組合", type: "登録支援機関", address: "岐阜県高山市昭和町一丁目３２９番地", tel: "0577360120", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社モアナスタッフ", type: "登録支援機関", address: "岐阜県岐阜市秋沢一丁目５５番地１", tel: "0582399113", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社岐文商務", type: "登録支援機関", address: "岐阜県岐阜市五坪一丁目１番５－４０２号（エスポア田神）", tel: "0582158580", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社イー・オー・シー", type: "登録支援機関", address: "岐阜県各務原市鵜沼西町三丁目７１番地", tel: "0583222888", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "尚道中部加工技術協同組合", type: "登録支援機関", address: "岐阜県岐阜市大菅北７－４", tel: "0582534543", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ＡａｎｄＫ", type: "登録支援機関", address: "岐阜県可児市今渡３－１１", tel: "0574663511", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ファイブオール", type: "登録支援機関", address: "岐阜県羽島郡岐南町八剣四丁目２０２番地", tel: "0583740755", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ユウアイ", type: "登録支援機関", address: "岐阜県各務原市蘇原瑞雲町一丁目４番地６", tel: "0583716555", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社４４ーｐｒｏｊｅｃｔ", type: "登録支援機関", address: "岐阜県岐阜市東興町２７番地", tel: "0582150661", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社スカイコーポレーション", type: "登録支援機関", address: "岐阜県関市倉知２６０３番地３", tel: "0575469725", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "東海国際交友会事業協同組合", type: "登録支援機関", address: "岐阜県岐阜市竜田町５－８", tel: "0582597780", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "岐勝愛山協同組合", type: "登録支援機関", address: "岐阜県岐阜市日野北二丁目３番１７号", tel: "0583377801", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "草野　保之（行政書士草野保之事務所）", type: "登録支援機関", address: "岐阜県大垣市上石津町上鍛治屋１６４番地３", tel: "0584452368", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "山形　輝明（山形総合研究所）", type: "登録支援機関", address: "岐阜県多治見市太平町４丁目６０－１　ファインコール９１　T３　１F", tel: "0572871660", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "Ｊｏｙｏｕｓ　Ｍｅｄｉａｔｉｏｎ株式会社", type: "登録支援機関", address: "岐阜県岐阜市城東通三丁目４８番地丸正ビル２F", tel: "0583771008", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "エコ・プロジェクト協同組合", type: "登録支援機関", address: "岐阜県岐阜市薮田南四丁目１０番４号", tel: "0582750226", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "森川　俊策（社会保険労務士森川相談事務所）", type: "登録支援機関", address: "岐阜県岐阜市長良３４５９－１５５", tel: "09049055665", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "日本国際人材開発支援協同組合", type: "登録支援機関", address: "岐阜県岐阜市加納清野町２０番地", tel: "0582776030", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "技能者支援事業協同組合", type: "登録支援機関", address: "岐阜県多治見市希望が丘四丁目７５番地の３", tel: "0572267056", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "立木ＭＲ株式会社", type: "登録支援機関", address: "岐阜県不破郡関ヶ原町大字関ヶ原３４５６番地１", tel: "0584430066", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "ジャパンネット株式会社", type: "登録支援機関", address: "岐阜県中津川市千旦林８１４番地２３", tel: "0573781110", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "ヒューマンリレーションズ株式会社", type: "登録支援機関", address: "岐阜県大垣市林町六丁目８０－５５", tel: "0584831024", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "西川産業株式会社", type: "登録支援機関", address: "岐阜県可児市土田４５４１番地", tel: "0574273050", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "中部国際産業協同組合", type: "登録支援機関", address: "岐阜県安八郡神戸町大字神戸字井田６９２番地１", tel: "0584281637", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "アジアニズム協同組合", type: "登録支援機関", address: "岐阜県岐阜市東川手４丁目５番地", tel: "0582787531", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社東海国際ビジネス", type: "登録支援機関", address: "岐阜県岐阜市本町二丁目３２番地２", tel: "0583726658", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "協同組合アセンド", type: "登録支援機関", address: "岐阜県羽島郡岐南町平島四丁目１３２番地", tel: "0582593255", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ヒューマン・リンク", type: "登録支援機関", address: "岐阜県可児市今渡５２番地１", tel: "0574287772", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "スン　陽子", type: "登録支援機関", address: "岐阜県岐阜市問屋町一丁目６番地３", tel: "08067247778", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ＫＡＥＤＥ", type: "登録支援機関", address: "岐阜県岐阜市御望４５８番地の１０７", tel: "0582341273", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "一般財団法人国際クラブ", type: "登録支援機関", address: "岐阜県羽島市福寿町平方七丁目３３番地２", tel: "0583970232", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "小栗　輝之(おぐり行政書士事務所)", type: "登録支援機関", address: "岐阜県中津川市本町１－１－７", tel: "0573666313", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "T・アシスト協同組合", type: "登録支援機関", address: "岐阜県岐阜市江添二丁目８番１７号", tel: "0582156120", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ヘルシーケアサービス", type: "登録支援機関", address: "岐阜県岐阜市鷺山１１７８番地の１", tel: "0582011833", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "東海ビジネスサポート協同組合", type: "登録支援機関", address: "岐阜県岐阜市則武２５０番地１４", tel: "0582163137", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ケイ・プランニング", type: "登録支援機関", address: "岐阜県岐阜市金町七丁目１３番地", tel: "0582694664", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "グローバルクエスト協同組合", type: "登録支援機関", address: "岐阜県岐阜市則武東二丁目５番４８号", tel: "0582321122", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "中日本経済技術協同組合", type: "登録支援機関", address: "岐阜県加茂郡坂祝町酒倉町字北野１０５８番１号", tel: "0574663490", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社きたせ", type: "登録支援機関", address: "岐阜県岐阜市栄新町一丁目１８番地", tel: "0582947930", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "ニューパワー東海協同組合", type: "登録支援機関", address: "岐阜県美濃加茂市西町二丁目６４番地", tel: "0574259759", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "河田　敏弘(河田敏弘行政書士事務所）", type: "登録支援機関", address: "岐阜県各務原市上中屋町三丁目２０８番地", tel: "08030693714", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "一般社団法人全国福祉勤労支援機構", type: "登録支援機関", address: "岐阜県岐阜市六条東１－１０－１４", tel: "0582732777", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "松岡　愛子", type: "登録支援機関", address: "岐阜県岐阜市東鶉２丁目１１５番地７", tel: "08045307171", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "エスケーエム株式会社", type: "登録支援機関", address: "岐阜県揖斐郡池田町田畑７０３番地８", tel: "0585529225", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "岐阜メタルアート協同組合", type: "登録支援機関", address: "岐阜県岐阜市野一色五丁目９番１２号", tel: "0582450390", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "武藤　功(武藤社会保険労務士事務所)", type: "登録支援機関", address: "岐阜県岐阜市加納新本町二丁目２５番地丸三ビル４０１号室", tel: "0582429106", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "岐阜中部樹脂工業協同組合", type: "登録支援機関", address: "岐阜県羽島郡笠松町西金池町４３番地１", tel: "0583888123", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市福寿町平方十一丁目２番地", tel: "0583970233", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市雨踊町１３番地", tel: "0582012155", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島郡岐南町徳田西１丁目１６４番地", tel: "0582748936", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市足近町市場１２５５番地５", tel: "0583223210", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市東金宝町一丁目１２番地８F", tel: "0582015221", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県山県市高富２４４３番地１", tel: "0581225611", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市鵜沼西町三丁目７１番地", tel: "0583703945", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県中津川市茄子川１６４２番地１６７", tel: "0573677786", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市加納神明町一丁目１０番地２", tel: "0582131456", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県美濃加茂市太田町７５番地", tel: "0574280515", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市西中島五丁目３番１５号", tel: "0582951880", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市田口町１番地", tel: "0584818848", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市大菅南１３番１６号", tel: "0582135999", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県多治見市虎渓山町七丁目１４番地", tel: "0572244351", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市忠節町二丁目１８番地", tel: "0582151188", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市足近町市場１２５５番地５", tel: "0583919448", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市中西郷四丁目５６番地１", tel: "0582149978", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県海津市海津町福江４４８番地", tel: "0584547080", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞浪市西小田町三丁目２２１番地", tel: "0572661030", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市新田町四丁目７４番地３", tel: "0584718070", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市郭町東二丁目５７番地戸田ビル２０１号室", tel: "0584843003", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市打越５４６番地の２", tel: "0582957295", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市和合新町一丁目２５番地１", tel: "0584828060", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県多治見市金岡町三丁目５０番地", tel: "0572268370", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島郡笠松町門間１７１１番地", tel: "0582182357", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市小熊町島二丁目１０２番地１", tel: "0583917313", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県関市尾太町１７番地", tel: "0575216778", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県中津川市茄子川１６８３番地の２４６", tel: "0573688294", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市六条北４丁目６番６号", tel: "0582686066", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県可児市川合字寺田２４３番地１ここやビル２階", tel: "0574661717", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市又丸２０番地６", tel: "0582390230", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市鏡島南２丁目１３番１１号", tel: "0582541061", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市加納南広江町５８番地", tel: "0583383829", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市上土居３丁目４番１号ラ・フォーレ神谷１０５号室", tel: "0582954585", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県美濃加茂市古井町下古井２６４３番地の１", tel: "0574250798", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市蘇原東島町４丁目５６番地", tel: "0583801030", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県可児市下恵土４４６番地２４２", tel: "0574601404", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県加茂郡坂祝町深萱字北大洞１８３番地１", tel: "0574240771", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市那加石山町１丁目１２６－１", tel: "0583229375", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県不破郡垂井町地蔵１丁目２５番地１", tel: "0584240557", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市八代１丁目４番２１号", tel: "0582160739", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県高山市西之一色町３丁目４６２番３３号", tel: "0577577130", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市柳津町梅松四丁目１１２－１", tel: "07039720374", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県安八郡輪之内町南波３１８番地１ムーンテラス片山Ｓ館１０２号室", tel: "0584680215", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市川島小網町２１５０番地１８", tel: "0586591900", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県不破郡垂井町宮代２９０８番４", tel: "0584478683", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島郡岐南町平島四丁目１３２番地", tel: "0582480331", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市加納清野町２０番地", tel: "0582160056", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県安八郡神戸町大字安次４６６番地の１", tel: "0584519961", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市昭和町二丁目１１番地", tel: "0582150551", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市正木町曲利７５１番地１", tel: "0583228810", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市吉野町五丁目１２番地４F", tel: "0582643537", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県不破郡垂井町綾戸８９２番地の１３", tel: "0584478717", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市花園町１６番地　エストラ岐阜２０１号室", tel: "0582151200", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市開発町五丁目５３９番地", tel: "0584741684", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県加茂郡富加町大山８６２番地１", tel: "09040808685", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市郭町一丁目１０３番地", tel: "0584740368", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県郡上市白鳥町白鳥１１１１番地５", tel: "0575679990", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市三田洞９１１番地２　野川ビル３０２", tel: "0582165001", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市長良５１６-９", tel: "0582013028", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県高山市石浦町９丁目３４１－２\nA-２０１", tel: "0577578851", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞穂市野田新田４１１９番地１", tel: "0583226469", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞穂市生津外宮東町二丁目８番地", tel: "0583227247", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市芋島三丁目６番２０号", tel: "0583377801", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市加野１丁目３２番２０号", tel: "08030607843", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市今嶺１丁目２１番５号", tel: "0582719369", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市柳津町上佐波西五丁目１６", tel: "0582136636", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市那加織田町二丁目５番地１", tel: "0582603317", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市一日市場北町８番６号", tel: "0582013930", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県養老郡養老町高田３８７９番地の３", tel: "0584320549", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市東金宝町一丁目１８番地", tel: "0582136950", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市薮田南一丁目７番地１６", tel: "0582161139", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県多治見市池田町６丁目１４番地", tel: "0572216860", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市西野町八丁目１４番地", tel: "0582522886", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市戎町四丁目２１番地", tel: "0582138016", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市荒尾町２２９番地の２", tel: "0584931013", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市福富永田７４番地１ふくとみ２２C号", tel: "0582292754", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市五反田町１３番地", tel: "0582534433", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市今宿六丁目５２番地１６ソフトピアジャパンセンタードリーム・コア３０１号室", tel: "0584773675", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市柳津町東塚４－４６　WING NODA ２０１号", tel: "08042158571", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞穂市祖父江字伯母塚東４６番地１２", tel: "0582167138", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市高田３丁目１５番１４号", tel: "0582571377", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市打越５４６番地２", tel: "0582333333", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市六条東一丁目１０番地１４", tel: "0582725501", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県多治見市旭ヶ丘六丁目３７番地", tel: "0572272800", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市今川町ニ丁目２２ＧＩＦＵエステートピアビル２０１", tel: "0583381467", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞穂市穂積１８１４番地１", tel: "0583290655", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞穂市別府１２４２番地２", tel: "0583227788", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県関市志津野２０７８番地４", tel: "0575290830", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県多治見市滝呂町十三丁目５９番地の１", tel: "0572224823", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県揖斐郡揖斐川町谷汲名礼２４６番地２", tel: "0585552853", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市各務山の前町四丁目５４３番地", tel: "0583227106", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県関市西田原大千前６１番地１", tel: "0575252661", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県可児市土田７１１番地１", tel: "0574257776", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市徹明通５丁目８番地　田中ビルヂング２階南", tel: "0582524314
07064108935", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市六条北四丁目１９番１号", tel: "0582730678", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市茜部菱野三丁目１７１番地", tel: "09065935916", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県多治見市旭ケ丘十丁目２番地の１９４", tel: "08051024255", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市和合新町一丁目１５番地中村第三ビル２０３号", tel: "0584716382", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市古市場中原６７番地１", tel: "0582160131", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市城田寺１９３３番地２", tel: "0582956606", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県土岐市泉町大富字報徳町２５４番地６ユニーブル土岐１００３号", tel: "0572552202", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県関市小瀬２７６４番地３", tel: "0575215031", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島郡岐南町平成三丁目９３番地の１", tel: "0582488749", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県美濃加茂市深田町三丁目６番９号", tel: "0574666644", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市加納新本町三丁目１番地", tel: "0582010220", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞穂市別府１６９９番地５", tel: "09016253668", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県不破郡垂井町表佐１１２番地２", tel: "0584719613", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市荒川町４６－４", tel: "05031100355", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県揖斐郡池田町片山１３６７番地", tel: "0585740899", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県美濃加茂市牧野５５８番地", tel: "0574427955
09081806559", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県安八郡安八町南今ヶ淵１５００-１", tel: "09096228473", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県不破郡垂井町府中１５２８番地の３", tel: "0584716140", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市中鶉一丁目１２８番地サンアリーネビル１Ｆ", tel: "0582737327", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市長良城西町一丁目１４番地", tel: "0582955060", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市蘇原東島町三丁目１７２番地３", tel: "0583370834", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市蘇原申子町一丁目１番地", tel: "0583802622", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市若宮町九丁目１６番地", tel: "0582123788", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県高山市花里町三丁目３９番地１", tel: "0577575570", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市市ノ坪町四丁目２０番地", tel: "0582156420", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市都通四丁目１１番地１", tel: "0582155151", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市薮田南三丁目７番２０号", tel: "05035296543", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市竹鼻町丸の内二丁目６番地", tel: "0583912888", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県関市山田字太田１３５５番地１", tel: "0575467771", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市加野１丁目１３番１３号", tel: "09086746273", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県山県市谷合１２３２番地の２", tel: "0581552914", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市舟橋町二丁目２８番地", tel: "0583971001", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市那加日新町六丁目２２番地各務原ＭＳトーカイビル", tel: "0582606111", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県美濃加茂市田島町一丁目２番２３号", tel: "0574274633", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市東鶉三丁目６９番地５", tel: "09062886388", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市水海道四丁目２２番１２号", tel: "0582462558", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市北一色１丁目１９－１１　イイヌマビル２F（２０１）", tel: "08051969312", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市赤坂大門三丁目６３番地１", tel: "0584402301", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市芋島三丁目６番２０号", tel: "0582150050", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市長良校文町２０番地パティオＢ１０１号室", tel: "09092626207", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市今宿６丁目５２番地１６　ドリーム・コア１０３", tel: "09099159588", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市茜部菱野三丁目１７番地", tel: "0582011505", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市中西郷二丁目５７番地１", tel: "0582935118", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市川島渡町１７４番地", tel: "0586828830", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市近島三丁目４番１３号ＯＭレジデンス近島２０２号室", tel: "0582165320", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市城東通三丁目４８番地", tel: "0582079935", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市墨俣町さい川４５番地１", tel: "05035288404", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県加茂郡富加町夕田３８０番地", tel: "0574543321", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県下呂市萩原町萩原１５００番地", tel: "0576521811", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市長良福光１６４５番地１０", tel: "0582961128", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市加納本石町三丁目７番地", tel: "0582763888", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県安八郡神戸町大字加納３２１番地の８", tel: "0584716800", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市河渡三丁目６番地１　ラ・メゾン・デスポアB１０２号", tel: "09098933981", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞穂市穂積１８１４番１", tel: "0583268555", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県海津市南濃町松山６４７番地２６", tel: "0584515886", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市中鶉一丁目１２７番地１", tel: "0582683750", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市粟野東４丁目２０９番地の２", tel: "0582375888", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県土岐市肥田町肥田２２４７番地の１９", tel: "0572552175", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市美園町四丁目７番地", tel: "0582010880", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県美濃加茂市下米田町信友４８２番地", tel: "0574262687", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市曙町２丁目８番地２", tel: "0583380688", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県土岐市肥田町肥田２２４７番地の２０", tel: "0572553175", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県本巣市神海９１６番地", tel: "08065529384", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市河渡四丁目１６８番地２", tel: "0582161243", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市福富永田７４番地１ふくとみ２２Ａ号", tel: "0582160082", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市一日市場北町５番３号", tel: "0582335008", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県下呂市湯之島８６８番地１", tel: "0576253339", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市住ノ江町一丁目１９番地", tel: "0583749039", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県土岐市肥田町浅野１０７８番地の９７", tel: "0572555757", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県関市豊岡町二丁目５番７号", tel: "0582132388", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県高山市三福寺町３１７０番地３２", tel: "05088805014", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県本巣市仏生寺８８５番地の１", tel: "08034614775", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市六条江東二丁目８番地８エムステイト１０３号", tel: "0582011357", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市六条東一丁目１０番地１４", tel: "0582717444", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市旦島五丁目３番地１９", tel: "0583377820", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県高山市名田町五丁目９５番地の１５", tel: "09058600834", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市芥見三丁目３０３番地", tel: "0583745448", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県土岐市駄知町２２７９番地の１－３階", tel: "09033060515", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市鵜沼朝日町２丁目７９番地", tel: "0583705239", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市太郎丸新屋敷９－１ＫＵＮＺ　Ｂ棟１０６号室", tel: "0582012627", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県瑞穂市美江寺５１１番地５", tel: "0583225697", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市足近町市場１２５８番地１", tel: "0583944155", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市向加野二丁目１７番地７ＣＡＳＡＨｉｇａｓｈｉｙａｍａ２０５号室", tel: "0582431666", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市鷺山南２０番１４号", tel: "0582942193", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市禾森町５丁目８番地", tel: "0584719412", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県各務原市各務おがせ町９丁目２５番地", tel: "0582017783", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市早田東町４丁目５９番地", tel: "0582131231", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市神田町二丁目１番地", tel: "0584475671", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県関市平和通４丁目１２番地６", tel: "0575212338", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県安八郡神戸町末守７８番地２", tel: "09047994845", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市上土居４丁目１３番１号", tel: "09033897825", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市竜田町４丁目３番地３", tel: "0582139330", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県中津川市東町３番３４", tel: "09085457979", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県岐阜市加納上本町４丁目２６番地大忠ビル２Ａ", tel: "0582015310", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県関市上之保１４０１番地", tel: "0575472166", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島市小熊町島２丁目２４番地", tel: "0582168921", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県羽島郡岐南町八剣４丁目２０２番地", tel: "0582158912", visa: ["tokutei1"], prefId: "gifu", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岐阜県大垣市領家町１丁目７番地３", tel: "0584843397", visa: ["tokutei1"], prefId: "gifu", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();