// hokkaido (272件)
(function(){
  const data = [
    { name: "株式会社キャリア・フォース", type: "登録支援機関", address: "北海道札幌市北区北７条西４丁目１番トーカン札幌ビル５階", tel: "0117361113", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社アイアジア", type: "登録支援機関", address: "北海道帯広市西４条南１５丁目９番地　共栄ビル", tel: "0155247737", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "ＪＡＰＡＮ　ＰＯＬＡＲＩＳ株式会社", type: "登録支援機関", address: "北海道札幌市北区北３８条西７丁目１番１０号シティハイム西麻生１階", tel: "0115002302", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "キャリアバンク株式会社", type: "登録支援機関", address: "北海道札幌市中央区北５条西５丁目７番地ｓａｐｐｏｒｏ５５", tel: "0112515009", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "Ａ－ＢＲＩＤＧＥ事業協同組合", type: "登録支援機関", address: "北海道札幌市東区北十四条東八丁目３番１号BEビル３階", tel: "0117767751", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "中村　浩三（中村社会保険労務士事務所，中村総合法務・行政書士事務所）", type: "登録支援機関", address: "北海道札幌市中央区南１条西７丁目２０番地１札幌スカイビル５階", tel: "0112101008", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "一般社団法人海外人材開発推進機構", type: "登録支援機関", address: "北海道札幌市中央区南１条東３丁目１０－１３アイパスビル３Ｆ", tel: "0112114952", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社アシストワン", type: "登録支援機関", address: "北海道河東郡音更町木野大通西１４丁目１番地１５", tel: "0155302200", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-5" },
    { name: "株式会社ＢＡＺＡＬＡコーポレーション", type: "登録支援機関", address: "北海道札幌市中央区北五条西十三丁目１番１１６号", tel: "0112060780", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "共通産業協同組合", type: "登録支援機関", address: "北海道札幌市白石区本通１８丁目北１ー１第五栄輪ビル３FーＢ", tel: "0115981368", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "人材育成事業協同組合", type: "登録支援機関", address: "北海道札幌市西区二十四軒１番六丁目１４－１０二十四軒ライフシティー４０３室", tel: "0113031315", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社さくらコミュニティサービス", type: "登録支援機関", address: "北海道札幌市北区北４０条西４丁目２番７号札幌Ｎ４０ビル６階", tel: "0117163987", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "鵡川農業協同組合", type: "登録支援機関", address: "北海道勇払郡むかわ町末広二丁目１２４番地", tel: "0145422611", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-7" },
    { name: "中和石油株式会社", type: "登録支援機関", address: "北海道札幌市中央区南４条西９丁目１００８番地", tel: "0115111101", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "サンリブロ協同組合", type: "登録支援機関", address: "北海道帯広市西１６条南６丁目２７番１４号　テラス安ら木２号室", tel: "0155664760", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "東日本国際交流事業協同組合", type: "登録支援機関", address: "北海道札幌市中央区南５条西１丁目１番地２３北一ビル２階", tel: "0115327797", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "職業訓練法人キャリアバンク職業訓練協会", type: "登録支援機関", address: "北海道札幌市中央区北５条西５丁目７番ｓａｐｐｏｒｏ５５", tel: "0112076540", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "洪　傑（楽農企画とかち）", type: "登録支援機関", address: "北海道札幌市厚別区もみじ台北５丁目９番１２号", tel: "08019772089", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "グローバルフレッシュ株式会社", type: "登録支援機関", address: "北海道千歳市千代田町６丁目７番地２駿河千代田ビル５階", tel: "0123271600", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "北海道近代酪農協同組合", type: "登録支援機関", address: "北海道野付郡別海町別海常盤町２５番地の１", tel: "0153796667", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-8" },
    { name: "石垣　一郎（石垣牧場）", type: "登録支援機関", address: "北海道稚内市大字声問村字上声問", tel: "0162742833", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-9" },
    { name: "協同組合アジアンネットワーク", type: "登録支援機関", address: "北海道札幌市北区北９条西４丁目７番地４エルムビル７階", tel: "0117883600", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "オホーツクはまなす農業協同組合", type: "登録支援機関", address: "北海道紋別市落石町４丁目８番９号", tel: "0158235211", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-3" },
    { name: "株式会社アスクゲートトラスト", type: "登録支援機関", address: "北海道札幌市白石区菊水３条２丁目３番２６号大和商会ビル２０１号室", tel: "0118338166", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "国際人材開発事業協同組合", type: "登録支援機関", address: "北海道滝川市明神町三丁目８－２２", tel: "0125749704", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-10" },
    { name: "パワーズトレーディング株式会社", type: "登録支援機関", address: "北海道札幌市西区発寒六条十丁目７番６号", tel: "0116681244", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "リアニード大千株式会社", type: "登録支援機関", address: "北海道帯広市西十八条南三十四丁目１－４０", tel: "08055822167", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社エヌエスジー", type: "登録支援機関", address: "北海道札幌市中央区南九条西六丁目４２１番地１５", tel: "0112527139", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "明亜協同組合", type: "登録支援機関", address: "北海道紋別市幸町六丁目１－１０", tel: "0158285466", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-3" },
    { name: "行政書士法人Ａｉｍパートナーズ", type: "登録支援機関", address: "北海道札幌市西区西野２条５丁目６番５号Ａｉｍ. ＢＬＤ", tel: "0116696064", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "有限会社東豊企画", type: "登録支援機関", address: "北海道札幌市中央区北三条西七丁目１番１号緑苑ビル５０３号室", tel: "0112047505", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "あかり行政書士法人", type: "登録支援機関", address: "北海道札幌市中央区南四条西六丁目８番地晴ばれビル", tel: "0112817722", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "渡島国際交流事業協同組合", type: "登録支援機関", address: "北海道茅部郡森町字砂原２丁目１８８－１", tel: "0137485111", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-11" },
    { name: "株式会社北海道アルバイト情報社", type: "登録支援機関", address: "北海道札幌市中央区南二条西六丁目１３番地１", tel: "0112515188", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "山田　大介（ＴＦＳ）", type: "登録支援機関", address: "北海道帯広市西１８条北２丁目１番地", tel: "0155363820", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ナップ", type: "登録支援機関", address: "北海道帯広市西九条南二十八丁目２３番地", tel: "0155677523", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "びらとり農業協同組合", type: "登録支援機関", address: "北海道沙流郡平取町本町４０番地１", tel: "0145722211", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-12" },
    { name: "Ｊ・クラウド事業協同組合", type: "登録支援機関", address: "北海道河東郡音更町南鈴蘭北三丁目１２番地１５", tel: "0155435160", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-5" },
    { name: "道南地域国際交流事業協同組合", type: "登録支援機関", address: "北海道北斗市東浜二丁目４－１８号", tel: "0138869921", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-13" },
    { name: "札幌エージェント株式会社", type: "登録支援機関", address: "北海道札幌市中央区南五条西九丁目１０１６番地２３号ＳＡビル", tel: "0113745790", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "北斗国際交流事業協同組合", type: "登録支援機関", address: "北海道宗谷郡猿払村鬼志別南町１４番地", tel: "0163522350", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-14" },
    { name: "根室商工会議所", type: "登録支援機関", address: "北海道根室市松ヶ枝町二丁目７番地", tel: "0153242062", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-15" },
    { name: "札幌南国際事業協同組合", type: "登録支援機関", address: "北海道千歳市稲穂一丁目８番８号　千歳市森林組合ビル", tel: "0123422553", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "澤井　利之（アンビシャス総合法律事務所）", type: "登録支援機関", address: "北海道札幌市中央区大通西１１丁目４－２２－８Ｆ", tel: "0112107501", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "ワークテック協同組合", type: "登録支援機関", address: "北海道広尾郡大樹町字下大樹１８９番地２４", tel: "0155887206", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-16" },
    { name: "ＩＳＳ北海道事業協同組合", type: "登録支援機関", address: "北海道江別市朝日町３０番地３３", tel: "0113983780", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-17" },
    { name: "羽萌国際株式会社", type: "登録支援機関", address: "北海道千歳市柏陽三丁目１番地の１０", tel: "0123297986", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "紋別国際交流協同組合", type: "登録支援機関", address: "北海道紋別市港町五丁目３番４号", tel: "0158262744", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-3" },
    { name: "株式会社グローバルセトル", type: "登録支援機関", address: "北海道旭川市流通団地三条五丁目５番地の５", tel: "0166672206", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "有限会社ウイングプロダクション", type: "登録支援機関", address: "北海道釧路市武佐五丁目３８番５６号", tel: "0154473666", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-6" },
    { name: "オホーツク国際事業協同組合", type: "登録支援機関", address: "北海道紋別市真砂町一丁目２番４２号", tel: "0158236686", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-3" },
    { name: "蛯原　友浩（行政書士　蛯原友浩法務事務所）", type: "登録支援機関", address: "北海道札幌市中央区宮の森２条１０丁目１－２４－２０１", tel: "0113020544", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "ＳＯＪ協同組合", type: "登録支援機関", address: "北海道札幌市中央区南一条西一丁目１３番１", tel: "0112064223", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "ＫＦホールディングス株式会社", type: "登録支援機関", address: "北海道新冠郡新冠町字共栄３０１番地の１", tel: "08034835197", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-19" },
    { name: "さくらネットワーク・システム協同組合", type: "登録支援機関", address: "北海道札幌市中央区南八条西十七丁目３番２６号", tel: "0112151201", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "東北海道経済交流中小企業協同組合", type: "登録支援機関", address: "北海道釧路市緑ヶ丘１丁目２２番１０号メゾン１２２D", tel: "0154645151", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-6" },
    { name: "札幌介護事業協同組合", type: "登録支援機関", address: "北海道札幌市中央区南三条西十丁目１００２番地Ｓ３１０ビル５０１号", tel: "0112074185", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "渡島噴火湾水産協同組合", type: "登録支援機関", address: "北海道山越郡長万部町字静狩５２番地１０", tel: "09095244210", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-20" },
    { name: "有限会社デリカ食品", type: "登録支援機関", address: "北海道紋別市落石町二丁目３６番２８号", tel: "0158243338", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-3" },
    { name: "株式会社ＫＪＫサポート", type: "登録支援機関", address: "北海道札幌市中央区大通西十六丁目２番地２大通公園シティハウス４０１号", tel: "0117926275", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南１条東四丁目７番地", tel: "0115966171", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道紋別郡雄武町字雄武７０８番地の２", tel: "0158843784", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道空知郡南幌町栄町四丁目４番３４号", tel: "0113782800", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道紋別市大山町一丁目３６番１４号", tel: "0158246522", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市十条通九丁目９７５番地の８２", tel: "0166739603", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道釧路市双葉町８番１７号", tel: "0154226775", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北三条西七丁目１番地", tel: "0112818524", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区琴似１条３丁目３番２２号　ことにセンタービル８ｰＡ", tel: "0116434770", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区北二十八条東十丁目２番１７号", tel: "0117920058", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道苫前郡羽幌町港町一丁目３６番地", tel: "0164621291", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道北見市常呂町字土佐４３番地４", tel: "0152676026", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区新琴似十二条一丁目１番３３号", tel: "0117081500", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区本町一条二丁目５番３０号", tel: "0117891700", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条西二丁目１８番地", tel: "0112116185", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道砂川市空知太東一条三丁目２番１０号", tel: "0125562220", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道苫小牧市東開町五丁目１４番１９号", tel: "0144843668", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南１条西１１丁目３２７番地６　ワンズ南一条ビル　４階", tel: "0112527361", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区流通センター七丁目８番２１号", tel: "0118938711", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北五条西十一丁目１６番１ー６０５号", tel: "0112066111", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道余市郡余市町大川町十九丁目２０番地４１", tel: "08060682805", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市新町西四丁目９番地", tel: "0155665190", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道伊達市鹿島町７－１１Ｙ’ｓＢＡＳＥ２Ｆ", tel: "0142829015", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道苫小牧市弥生町二丁目３番１号", tel: "0144783500", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道釧路市貝塚二丁目１５番２７号", tel: "0154645438", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条東二丁目３番地２", tel: "0112316355", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市豊平区豊平四条１２丁目１番２７号", tel: "0118319555", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道小樽市住吉町５番１７号", tel: "0134251342", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道函館市田家町１７番１８号　アルカディア２１　２０３号", tel: "0138870181", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市厚別区大谷地東５丁目３番３０号Ｏｙａｃｈｉ５　Ｋ号室", tel: "0118879819", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区琴似一条３丁目３番２２号", tel: "0116763936", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市五条西一丁目１番３号", tel: "0166567776", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道枝幸郡枝幸町幸町１番地枝幸町水産会館内", tel: "0163624420", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道中川郡美深町字大通北２丁目１２番地", tel: "0165621601", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北四条西６丁目１番３号", tel: "0112108088", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南９条西１２丁目１番５０号ＨＩＲＡＴＡＢＬＤ３階", tel: "0116763157", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道上川郡下川町南町３２３番地１", tel: "0165543531", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市東光５条２丁目４番１５号", tel: "0166646515", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北４０条西４丁目１－１ ＡＳＡＢＵ　ＬＡＮＤ　２Ｆ", tel: "0115581568", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道千歳市大和１丁目８番３号", tel: "0123297231", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区宮の森三条五丁目２番２５-５０１番", tel: "0112139864", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道恵庭市柏木町５丁目３番１５-２０１号", tel: "07021810129", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市大空町３丁目２番地８", tel: "0155671310", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区栄通１５丁目８番６号", tel: "0118768183", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区宮の沢一条五丁目６－３５", tel: "08060773156", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南十三条西一丁目２番１０ー６０４号", tel: "0112191855", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区東苗穂八条三丁目１番１号ー２階C", tel: "0117852866", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道河東郡音更町木野大通東十四丁目４番地１８８", tel: "08060958270", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道新冠郡新冠町字朝日１３６番地の４", tel: "0146473665", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-19" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道函館市松陰町２８番１３号", tel: "0138836303", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区菊水三条２丁目４-１", tel: "0118338111", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北十八条西七丁目２０番２１４", tel: "0117078835", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条東二丁目１１番地１ノーザンヒルズ大通東３０３号", tel: "0112131695", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区大通西８丁目２番地３９", tel: "0115226615", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道紋別郡興部町字興部５１８番地", tel: "0158822101", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道北斗市東前１９番地１", tel: "0138777485", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-13" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区八軒八条西十丁目６番２５号", tel: "0116335061", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道江別市豊幌花園町１２番地の２４", tel: "08040408887", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-17" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道河東郡音更町宝来北一条六丁目２番地４", tel: "0155669898", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条東三丁目１０番１３号", tel: "0112121471", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道千歳市千代田町二丁目２２番地２", tel: "0123273077", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市手稲区富丘二条四丁目１８番１３号", tel: "0116886919", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北六条西六丁目２番地２４第２山崎ビル７階", tel: "0116001755", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道千歳市東雲町五丁目１８番地の２３", tel: "0123297831", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道石狩市花川北六条一丁目２０番地", tel: "0133629572", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区栄通二十一丁目９番３号", tel: "0112066718", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道滝川市明神町三丁目８番２２", tel: "05031364974", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-10" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道釧路郡釧路町わらび三丁目８番地", tel: "0154403178", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道阿寒郡鶴居村字雪裡４９６番地４", tel: "0154642542", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市清田区平岡公園東四丁目３番１３号", tel: "0113773677", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道北広島市大曲緑ヶ丘５丁目４番地４", tel: "09094321504", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道函館市小安町９０番地", tel: "08040442043", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区北十四条東十五丁目３－５　STビル４F", tel: "0117848001", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市川端町四条七丁目３番１３号", tel: "0166761869", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道稚内市大字宗谷村字増幌１０８６番地", tel: "0162262641", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区八軒一条西一丁目３番１５号", tel: "0112156757", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道網走市字藻琴２１１番地の５０", tel: "0152462447", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条東四丁目７番地", tel: "0112517111", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北一条西二十六丁目３－２９ノースハイム円山公園２０２号室", tel: "0113116759", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市厚別区上野幌３条４丁目３番２１号", tel: "07026204056", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市豊平区月寒東一条十一丁目７番９号", tel: "0115228855", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道虻田郡留寿都村字留寿都２００番地１１４", tel: "0136463310", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南九条西３丁目２番１号マジソンハイツ２０６号９番１号", tel: "0115960045", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道亀田郡七飯町字上藤城１２５番地３", tel: "0138848740", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道室蘭市母恋北町一丁目５番１１号", tel: "0143227711", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道北広島市輝美町２番地３", tel: "0113738880", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北三条西十八丁目２番地１０", tel: "0116407200", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道函館市梁川町１番５号", tel: "0138315389", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道苫小牧市新富町二丁目３番４号", tel: "0144768612", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市手稲区前田９条１４丁目２番２０号ＨＯＴハウス２１５号室", tel: "0113308977", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市厚別区厚別中央三条一丁目３番２８号", tel: "0118878515", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道新冠郡新冠町字万世１５番地の２", tel: "0146490955", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-19" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道千歳市文京四丁目６番地の５", tel: "0123255044", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区西町南二十一丁目２番１５号３０２", tel: "0116769630", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市西十六条南四丁目１１番１１号", tel: "0155331177", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道小樽市石山町１７番３号", tel: "09082772397", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北三十一条西五丁目１番２４号プリンス札幌４０３", tel: "08033546654", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市西五条南五丁目４番地３", tel: "0155675666", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南十二条西十四丁目２ー１Ｂｏｒｎ１２１４－３０５室", tel: "08082916909", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市厚別区上野幌二条二丁目１３番１２号", tel: "0118877471", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道上川郡東川町進化台７８５番地３", tel: "0166824520", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市清田区北野一条二丁目１番２５号", tel: "0118876437", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市大通南九丁目１０番地１　ＡｉｍＢｌｄ．２０２", tel: "0155665000", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南八条西１７丁目３番２６号", tel: "0115203020", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道石狩郡当別町白樺町３１８５番地５", tel: "0133222225", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北一条西九丁目３番１９号", tel: "0112217737", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区菊水元町一条五丁目４番１３号", tel: "0113308982", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道伊達市舟岡町３５７番地２２", tel: "08032328028", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区東苗穂三条１丁目３番５０号Ｂ－３１８", tel: "0112994922", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南１条東２丁目１１番地１ノーザンヒルズ大通東５０１号", tel: "0112140632", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北八条西五丁目６番地１", tel: "0117076106", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北四条西十二丁目１番地２８北４条ビル５F", tel: "0112069357", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市清田区清田三条一丁目１番１６号", tel: "07026204056", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市大正町東三線８５番地", tel: "0155644886", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道千歳市東雲町三丁目１番地１７", tel: "0123297811", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北三条西一丁目２番地", tel: "0112121890", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市一条通十八丁目５２－４８ロジェ・エスト１Ｆ", tel: "0166748951", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道河東郡音更町南鈴蘭南二丁目４番地", tel: "0155323800", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南二条西七丁目８番２南２条ビル４０１", tel: "0115968420", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北四条西一丁目１番地北農ビル１０階", tel: "0112326411", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道二海郡八雲町東町２７３番地", tel: "0137624300", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道河東郡音更町木野大通西十四丁目１番地１５", tel: "0155435011", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道二海郡八雲町内浦町１０７番地２６", tel: "08088811610", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区北三十一条東一丁目４番１０号", tel: "0117884326", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道中川郡美深町字南町２５番地", tel: "0165621431", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市末広東1条6丁目１番8号", tel: "0166519922", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条西八丁目９－１ＥＣＯＮＥＴ　ＢＬＤ．３階", tel: "0112186077", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道函館市中道二丁目３９番１３号", tel: "0138872835", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南五条西一丁目１番地２３北一ビル３F", tel: "0115327797", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北七条西一丁目１番地２", tel: "0117267771", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道常呂郡佐呂間町字富丘２６６番地２", tel: "08050673481", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市西八条南二十五丁目１３番地", tel: "09075146300", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道小樽市祝津二丁目３６９番地", tel: "05088880182", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道名寄市西八条南十一丁目５５番地４８", tel: "0165487908", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区宮の森二条十七丁目４番８号", tel: "08045036886", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市豊平区西岡５条１４丁目７－６", tel: "0113507495", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条西九丁目５番地１札幌１９Ｌビル５階", tel: "0115905451", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北七条西二丁目６番地　３７山京ビル６１６号", tel: "09017375522", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市手稲区新発寒六条七丁目１０－３７", tel: "08018742000", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市清田区清田二条二丁目１４番５０号", tel: "0118845858", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道釧路郡釧路町東陽西三丁目１番地１０", tel: "0154401165", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市４条通十三丁目１３８５番地３", tel: "0166237177", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北三十一条西五丁目１番２４号プリンス札幌４０３", tel: "0117886111", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道枝幸郡枝幸町山臼７１３１番地２", tel: "0163675535", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区新琴似七条五丁目２番１１号", tel: "05010281804", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北五条西六丁目１番地２３北海道通信ビル８階", tel: "0116007474", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市豊平区福住一条四丁目５－３７－１Ｆ", tel: "09085660606", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区北三十四条東九丁目１番１号", tel: "0117518887", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南八条西４丁目４２２番地", tel: "0115967771", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区宮の森２条１７丁目１１番１８号", tel: "09062198119", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区北五条東八丁目１番３３号", tel: "0117428222", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区西町北６丁目４番８号", tel: "07090367009", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道釧路市美原五丁目２２番５号", tel: "09028786488", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区流通センター七丁目８番２１号", tel: "0118938711", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道勇払郡むかわ町有明５０番地５", tel: "08031285182", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北六条西六丁目２番地１１第３山﨑ビル", tel: "0112111312", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市西七条南十九丁目１番地", tel: "0155210001", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道余市郡余市町梅川町６７４番地４", tel: "0135301846", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市西三条南九丁目２番地", tel: "0155674509", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市豊平区平岸四条十丁目８番２３号", tel: "0118319400", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南八条西十七丁目３番２６号", tel: "0115203020", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区山の手一条一丁目３番地", tel: "0116120310", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道砂川市東一条北七丁目１番１８号", tel: "0125747091", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市春光三条九丁目７番１号", tel: "0166514774", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北一条東八丁目８４－２　ウリトンポセンター２階", tel: "09037753792", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北二十条西六丁目２番３６号", tel: "0117690224", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市春光台二条六丁目１番１１号", tel: "0166513088", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南十四条西８丁目５番５０号　クリオ行啓通２番館６０２", tel: "08032677382", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区二十四軒一条四丁目２番１号", tel: "08049602644", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道旭川市神楽岡七条三丁目３番２号", tel: "0166651087", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-18" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道虻田郡ニセコ町字東山一番地", tel: "0136441112", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区北八条東三丁目１番１号", tel: "0117886855", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区発寒７条５丁目１１－２１　クレストコート６０１", tel: "0115900470", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南五条西九丁目１０１４番１号１階", tel: "0115188700", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道江別市向ケ丘２２番地１", tel: "0113802666", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-17" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道岩見沢市幌向南一条五丁目４００番地１", tel: "0126263556", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道釧路市昭和南六丁目４３番１７号", tel: "09076414582", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区北三条西七丁目１番１号緑苑ビル８０９号", tel: "0112725000", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市西一条南二十五丁目２番２", tel: "0155676436", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南三条西十四丁目１ｰ１　ONODERA４５　BLD", tel: "0118876561", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区山の手二条十二丁目１２－２１", tel: "05012422884", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道野付郡別海町別海川上町１３９番地の１４", tel: "0153748144", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道浦河郡浦河町築地３丁目１番地３", tel: "0146221212", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区西野二条１丁目２番１号", tel: "0116635000", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区中央二条４丁目４番２０号", tel: "0118213633", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条東２丁目１１番地１ノーザンヒルズ大通東９階さっぽろＲオフィス大通東Ｎ室", tel: "08035557333", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道岩見沢市四条西７丁目３番地３", tel: "0126315513", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道伊達市上長和町４４０番地５", tel: "0142827417", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道夕張郡長沼町宮下２丁目９番２号", tel: "0123767582", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市北区北十三条西３丁目２番１号アルファスクエア北１３条９０６号", tel: "0117906185", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区二十四軒三条７丁目２番９号", tel: "0112118959", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道釧路市星が浦北３丁目４番地７", tel: "0154641720", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道江別市野幌松並町２６番地の６", tel: "0113985137", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-17" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道函館市東雲町１番８号", tel: "09048787417", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道虻田郡京極町字三崎５６番地", tel: "0136423986", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区東札幌四条６丁目１番１５号", tel: "0115989511", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南一条西２３丁目１番８号チサンマンション第８札幌７０７号", tel: "08018690793", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道帯広市東二条南６丁目２番地８", tel: "0155671235", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区東札幌二条５丁目７番８号３Ｄコート５階Ｄ号室", tel: "0118077573", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道千歳市旭ケ丘２丁目５番１７号", tel: "0123296901", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市南区石山一条１丁目１２番６－５０５号", tel: "0115811230", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市豊平区月寒東三条１９丁目１３番５－１０２号", tel: "0113000074", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市豊平区月寒西二条８丁目１番６号", tel: "0112991757", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市西区宮の沢三条５丁目１８番２３号", tel: "05036374222", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市東区北七条東３丁目１５番地３０ＳＡＫＵＲＡ－Ｎ７Ｋ室", tel: "0117687598", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市中央区南四条東４丁目１－７２－１００１", tel: "0112131777", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道江別市野幌屯田町１９－７", tel: "0113817800", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-17" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道中川郡幕別町字南勢３３０番地３", tel: "0155675992", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道千歳市富士１丁目１番地５", tel: "0123259212", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市白石区川下７３０番地５１", tel: "08032628945", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道札幌市豊平区平岸三条１２丁目１番３３号第一ヒラギシビル６１０号", tel: "0115987477", visa: ["tokutei1"], prefId: "hokkaido", districtId: "hokkaido-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道函館市東山３丁目１８番１号", tel: "09083727661", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "北海道空知郡南幌町栄町４丁目４番３４号", tel: "0113872800", visa: ["tokutei1"], prefId: "hokkaido", districtId: null },
  ];
  if (window.VISA_DATA && VISA_DATA.agencies) {
    VISA_DATA.agencies.push(...data);
  } else {
    window._pendingAgencies = window._pendingAgencies || [];
    window._pendingAgencies.push(...data);
  }
})();