// iwate (44件)
(function(){
  const data = [
    { name: "地域産業パートナーシップ協同組合", type: "登録支援機関", address: "岩手県遠野市材木町２番２１号", tel: "0198663888", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-3" },
    { name: "職業訓練法人北日本人材育成協会", type: "登録支援機関", address: "岩手県盛岡市山王町１０番６号山王ハイツ２階", tel: "0196813009", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社アルム不動産運輸", type: "登録支援機関", address: "岩手県胆沢郡金ケ崎町西根油地２８番地１", tel: "0197443386", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-4" },
    { name: "ヒトタ協同組合", type: "登録支援機関", address: "岩手県奥州市水沢字三本木４－４２ (株)北都交通 本社２階", tel: "0197228655", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-5" },
    { name: "岩野　光進（いわて行政書士法務事務所）", type: "登録支援機関", address: "岩手県盛岡市菜園一丁目１２番２５号", tel: "0196567425", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "協同組合大船渡水産加工", type: "登録支援機関", address: "岩手県大船渡市大船渡町字永沢１９番地３", tel: "0192475041", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-2" },
    { name: "東日本情報支援協同組合", type: "登録支援機関", address: "岩手県大船渡市大船渡町字山馬越１８２－１", tel: "0192265448", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-2" },
    { name: "株式会社ヒカリ", type: "登録支援機関", address: "岩手県一関市山目字中野１４０番地５ ササキビル中野３F", tel: "08061658899", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-6" },
    { name: "有限会社介護施設あお空", type: "登録支援機関", address: "岩手県宮古市向町２番３４号", tel: "0193635519", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-7" },
    { name: "めんこい協同組合", type: "登録支援機関", address: "岩手県盛岡市中央通一丁目９番１１号", tel: "0196569681", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "国際情報ビジネス協同組合", type: "登録支援機関", address: "岩手県盛岡市大沢川原三丁目４番１号", tel: "0196059933", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "協同組合アジア交流会", type: "登録支援機関", address: "岩手県盛岡市三ッ割三丁目１４番１２号", tel: "0196134882", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ヒロキャリアスタッフ", type: "登録支援機関", address: "岩手県盛岡市開運橋通３番４１号ダビンチビル", tel: "0196230707", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "日本グローバル人材協同組合", type: "登録支援機関", address: "岩手県盛岡市開運橋通３番３９号ダビンチビル２", tel: "0196542320", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "協同組合シーテック", type: "登録支援機関", address: "岩手県釜石市大字平田第３地割７５番１公益財団法人釜石・大槌地域産業育成センター内", tel: "0193276770", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-8" },
    { name: "合同会社リードアイ", type: "登録支援機関", address: "岩手県盛岡市黒石野三丁目１７番８号", tel: "0196135818", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県大船渡市大船渡町字地ノ森４７番地１１", tel: "0192212002", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市紺屋町２番３０号紺屋町テラス４階", tel: "0196189038", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市菜園１－３－６", tel: "0356477440", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県一関市荻荘字下中田７番地１", tel: "0191483081", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県大船渡市盛町字みどり町６番地６", tel: "0192270175", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県花巻市材木町１２番１８号", tel: "0198213141", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県北上市青柳町一丁目７番２０号AOYAGI８０５BIL２F-A", tel: "0197623733", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県北上市青柳町１丁目５番３号和野内ビル３階", tel: "0197728465", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県滝沢市鵜飼迫１０７番地５", tel: "0196137705", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県紫波郡紫波町東長岡字米一田２８番地５", tel: "0196819316", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市山王町１０番６号山王ハイツ２階", tel: "0196358839", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市材木町１２番地１５号", tel: "0196231730", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市開運橋通３番４１号ダビンチビル", tel: "0196230666", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県九戸郡九戸村大字伊保内第２２地割字鰻沢１１２", tel: "0195434508", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市菜園二丁目４番５号", tel: "0196567425", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市茶畑一丁目１番５３号", tel: "07056253548", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市玉山字二子沢１３番地１", tel: "08042828353", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市東安庭二丁目１２番６号", tel: "0196812235", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県奥州市水沢佐倉河字後樋４１番地１", tel: "0197226568", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市上堂一丁目１７番５３号", tel: "0196015573", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県九戸郡九戸村大字伊保内第１３地割４７番地", tel: "0195423611", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県一関市赤荻字鶴巻１７３－５番地Ｄ", tel: "0191347471", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県二戸市石切所字大渕６番地１", tel: "09090372988", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市浅岸二丁目４番３号", tel: "08051363361", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県盛岡市菜園一丁目１１番３号", tel: "0196063244", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県大船渡市盛町字町６番地８", tel: "0192278808", visa: ["tokutei1"], prefId: "iwate", districtId: "iwate-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県北上市本石町一丁目５番３０号プロビル２０２", tel: "0197728001", visa: ["tokutei1"], prefId: "iwate", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "岩手県八幡平市安比高原１６５番地６", tel: "0195788823", visa: ["tokutei1"], prefId: "iwate", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();