// kagoshima (73件)
(function(){
  const data = [
    { name: "Ｔ＆Ｔ事業協同組合", type: "登録支援機関", address: "鹿児島県姶良市加治木町反土２７８８番地１", tel: "0995575570", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-3" },
    { name: "南九州畜産食品協同組合", type: "登録支援機関", address: "鹿児島県南九州市川辺町平山６８１３－８", tel: "0993761585", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-4" },
    { name: "大崎町商工会", type: "登録支援機関", address: "鹿児島県曽於郡大崎町仮宿１０３２－２", tel: "0994760136", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-5" },
    { name: "佐藤　広明（行政書士佐藤広明事務所）", type: "登録支援機関", address: "鹿児島県鹿児島市松原町１番２１号佐藤ビル２０２", tel: "0992261433", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "イタックス株式会社", type: "登録支援機関", address: "鹿児島県鹿児島市小松原１丁目４４－８", tel: "0992102430", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "フロンティア鹿児島協同組合", type: "登録支援機関", address: "鹿児島県鹿屋市浜田町６３２－１", tel: "0994472447", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-2" },
    { name: "株式会社ネクステージ", type: "登録支援機関", address: "鹿児島県鹿児島市新町４－１８", tel: "0992247878", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "鹿児島国際交流協同組合", type: "登録支援機関", address: "鹿児島県鹿児島市谷山港二丁目２番８", tel: "0992624114", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "人材リンク株式会社", type: "登録支援機関", address: "鹿児島県出水市大野原町２２番地５", tel: "0996635055", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-6" },
    { name: "協同組合リライズ", type: "登録支援機関", address: "鹿児島県鹿児島市山下町１７番１９号加世田ビル２階", tel: "0992953708", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "特定非営利活動法人ＫＬＳ", type: "登録支援機関", address: "鹿児島県鹿児島市上本町１４番７号", tel: "0992927161", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "ハートングループ株式会社", type: "登録支援機関", address: "鹿児島県鹿屋市笠之原町４８番１８号", tel: "0994351757", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-2" },
    { name: "エーアンドエフ事業協同組合", type: "登録支援機関", address: "鹿児島県志布志市有明町伊崎田４９１０番地", tel: "0994741713", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市下伊敷一丁目５３番１６号", tel: "0992297500", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県いちき串木野市別府４４６０番地", tel: "09036136025", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市山之口町１番１０号１１階", tel: "0992489623", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市新屋敷町２２番地１８", tel: "0992488863", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県指宿市十二町字野中４５０１番地３", tel: "0993264188", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県姶良市宮島町１９番地２", tel: "0995502506", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県薩摩郡さつま町柏原２３５７番地４", tel: "0996523643", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市西田二丁目２番１６号", tel: "0992956001", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県曽於郡大崎町假宿６７０番地２", tel: "0994762139", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県霧島市横川町上ノ３２６５番地１", tel: "0995721011", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県出水市平和町２２５番地", tel: "0996630101", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県志布志市志布志町志布志２丁目１２番１６号", tel: "0994014434", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市真砂本町５３番１２号", tel: "0992584903", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市大黒町３番２７号清友ビル", tel: "0992267760", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市西別府町１６９２番地２", tel: "0992786788", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県姶良市宮島町３２番地１３", tel: "0995551631", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県志布志市有明町伊﨑田４９１０番地", tel: "0994741713", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市武二丁目２１番１号永吉マンション１０２", tel: "0998008725", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県曽於郡大崎町神領２１４０番地１", tel: "0994762103", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県指宿市山川成川７３８６番地３", tel: "05088840638", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市吉野町２３９０番地３３　オガタビル２階", tel: "0992488962", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県いちき串木野市塩屋町１３８番地", tel: "09025025780", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿屋市笠之原町１８番３号", tel: "0994415197", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市武岡一丁目１４番地３", tel: "0992810567", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県霧島市隼人町朝日１３２番地", tel: "07083236679", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市若葉町１番３号", tel: "0992953033", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県肝属郡肝付町前田４５４８番地８", tel: "0994351344", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市荒田二丁目７６番１６号ジュンクビル１Ｆ", tel: "0992145050", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿屋市輝北町上百引３８４７番地２", tel: "0994788600", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市坂之上８丁目２３番２号", tel: "0998016576", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県霧島市国分中央一丁目２４－４津山ビル２０２", tel: "0995706347", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県薩摩川内市東郷町南瀬１７００番地", tel: "0996415766", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市吉野町８７９２番地８", tel: "0992047722", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市小野一丁目２０番６号", tel: "0992954447", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿屋市寿七丁目９番５号", tel: "0994455845", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県曽於市大隅町須田木５２２番地", tel: "0994841458", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県南さつま市金峰町尾下７２８番地２８", tel: "08092426096", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市城西２丁目１８番２２号", tel: "0992571656", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県曽於市末吉町南之郷水窪４７６番地３", tel: "0986368930", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県曽於市末吉町諏訪方８６０６", tel: "05037038606", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿屋市寿五丁目２７番４号", tel: "0994368989", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県日置市伊集院町飯牟礼１７１５番地", tel: "08036694421", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県霧島市隼人町真孝３６９５番地", tel: "0995733015", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県姶良市東餅田１０５４番地２８", tel: "09019284485", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県南九州市知覧町東別府９６０６番地", tel: "0993842583", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市下荒田一丁目５番５号", tel: "0992087888", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県いちき串木野市塩屋町１３８番地", tel: "0996331131", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県出水市平和町１０１８番地", tel: "0996621811", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市山下町１７番１９号加世田ビル２階", tel: "0992950735", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県薩摩川内市平佐一丁目３６番地　ＮＫビル２F", tel: "0996222410", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県大島郡瀬戸内町大字古仁屋字船津３番地８", tel: "0997723757", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市真砂本町５６番１１号（３階）", tel: "0992020400", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市永吉二丁目２２番２号", tel: "0927919401", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県霧島市国分福島１丁目１９番１０号", tel: "08030351034", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市新屋敷町２２番１４－２", tel: "09079870114", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市春山町１５０２番地１", tel: "0992954407", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県曽於市末吉町岩﨑２８００番地", tel: "0986365815", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県奄美市名瀬入舟町１８番２１号", tel: "0997537087", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県鹿児島市錦江町８番２１号", tel: "0992224446", visa: ["tokutei1"], prefId: "kagoshima", districtId: "kagoshima-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "鹿児島県薩摩郡さつま町山崎１１６６番地パティオス山崎Ｋ２Ｙ１０８号室", tel: "07094296045", visa: ["tokutei1"], prefId: "kagoshima", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();