// kanagawa (412件)
(function(){
  const data = [
    { name: "合同会社みなと国際事務所", type: "登録支援機関", address: "神奈川県横浜市中区元浜町三丁目２１番地２ヘリオス関内ビル", tel: "0452228533", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "安達　篤志（司法書士・行政書士あだちラチエン通り法務事務所）", type: "登録支援機関", address: "神奈川県茅ヶ崎市松が丘一丁目１番６９号", tel: "0467956278", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-8" },
    { name: "田中　諭（行政書士田中諭横浜事務所）", type: "登録支援機関", address: "神奈川県横浜市磯子区新杉田町７ー１１ あびしにー新杉田２０８号", tel: "0453494251", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社Ｔ．Ｇ．Ｔ", type: "登録支援機関", address: "神奈川県大和市大和南一丁目１５番６号タイセイビル２－B号室", tel: "0462065836", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "公益社団法人横浜市福祉事業経営者会", type: "登録支援機関", address: "神奈川県横浜市港南区上大岡西１ー６ー１ ゆめおおおかオフィスタワー１０階", tel: "0458405815", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社大成ＥＲＣ", type: "登録支援機関", address: "神奈川県横浜市金沢区福浦一丁目７番１３号", tel: "0453533651", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "一般社団法人国際職業能力育成協会", type: "登録支援機関", address: "神奈川県横浜市中区不老町一丁目６番地１０", tel: "0453156460", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "ＩＳＴ協同組合", type: "登録支援機関", address: "神奈川県横浜市神奈川区松ヶ丘３９番地４", tel: "0456249600", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "亜州三九能力開発協同組合", type: "登録支援機関", address: "神奈川県横浜市中区羽衣町二丁目４番４号　エバーズ第８関内ビル８F－A", tel: "0453080088", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "棚村　英行（行政書士みなと国際法務事務所）", type: "登録支援機関", address: "神奈川県相模原市中央区共和４－２２－１２第２パティオ桔梗２０３", tel: "07026705361", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "グローバルキャリア職業訓練法人", type: "登録支援機関", address: "神奈川県川崎市川崎区砂子１－１－１４", tel: "0443824800", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社オリーヴ", type: "登録支援機関", address: "神奈川県横浜市中区桜木町２－２ 港陽ビル３F", tel: "0456505460", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "協同組合すばる", type: "登録支援機関", address: "神奈川県横浜市青葉区田奈町４３－５第２新幸レジデンス田奈５階", tel: "0455118601", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "エコパワー協同組合", type: "登録支援機関", address: "神奈川県横須賀市東浦賀１－１０－７", tel: "0468439122", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ミックコーポレーション", type: "登録支援機関", address: "神奈川県横浜市中区羽衣町二丁目４番４号エバーズ第８関内ビル９F", tel: "0453158139", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "楽信株式会社", type: "登録支援機関", address: "神奈川県横浜市中区野毛町二丁目９０番地", tel: "0459006888", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "セリテック株式会社", type: "登録支援機関", address: "神奈川県平塚市立野町１０番５号", tel: "0463634240", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "社会福祉法人喜楽会", type: "登録支援機関", address: "神奈川県相模原市南区当麻４９０番地１", tel: "0427787211", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "秋山企業株式会社", type: "登録支援機関", address: "神奈川県横浜市泉区上飯田町２２７７番地", tel: "0458050664", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "南関東人材育成協同組合", type: "登録支援機関", address: "神奈川県川崎市川崎区榎町１番８号", tel: "0442016117", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "下田　益子（下田行政書士事務所）", type: "登録支援機関", address: "神奈川県平塚市高浜台１番５－３０３号", tel: "0463343241", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "プロジックシステム株式会社", type: "登録支援機関", address: "神奈川県横浜市港南区日野中央三丁目９番１－５０１号", tel: "0458323676", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "JACTEC協同組合", type: "登録支援機関", address: "神奈川県平塚市東真土一丁目５番１号", tel: "0463796660", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "株式会社Ｍｕｌａｎ国際交流機構", type: "登録支援機関", address: "神奈川県横浜市都筑区高山１９番地４－１０７", tel: "0455678007", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ＰＱＩ", type: "登録支援機関", address: "神奈川県相模原市中央区相模原二丁目１番３号ＳＬＤビル３階", tel: "0427687011", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社迫田商店", type: "登録支援機関", address: "神奈川県横浜市緑区十日市場町１７０９番地", tel: "0459832211", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "アジアビジネスサポート事業協同組合", type: "登録支援機関", address: "神奈川県大和市下鶴間２－４－３１", tel: "0462005101", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ビオラジャパン", type: "登録支援機関", address: "神奈川県横浜市中区常盤町三丁目３０番１号SOLACUBE４階", tel: "0459001216", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "横浜医療介護福祉協同組合", type: "登録支援機関", address: "神奈川県横浜市旭区中希望が丘２５番地の１", tel: "0454894988", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "小峰　隆広（アドバンスコンサル）", type: "登録支援機関", address: "神奈川県横浜市戸塚区汲沢町１１５４番地ぐみざわ東ハイツ２棟６０７号", tel: "0455156476", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社日友インターナショナル", type: "登録支援機関", address: "神奈川県藤沢市湘南台四丁目１０番地の２４", tel: "0466460041", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "有限会社藤田圧送", type: "登録支援機関", address: "神奈川県川崎市宮前区水沢１－３－４", tel: "0449773138", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社東海ビルメンテナス", type: "登録支援機関", address: "神奈川県小田原市本町一丁目１３番６号", tel: "0465234114", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "岡田電機工業株式会社", type: "登録支援機関", address: "神奈川県横須賀市三春町二丁目３２番地", tel: "0468252288", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社サグラダ", type: "登録支援機関", address: "神奈川県横浜市鶴見区下野谷町三丁目８８番１Ｄ－ＹＫ つるみ", tel: "0455085301", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社Ｈ・Ｂ", type: "登録支援機関", address: "神奈川県横浜市港北区篠原東２丁目２１番１０－２号", tel: "0454313300", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "特定非営利活動法人愛のささえ", type: "登録支援機関", address: "神奈川県横浜市瀬谷区三ツ境７３番地７", tel: "0453666166", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "一般社団法人リベストアジアコンサルタンツ", type: "登録支援機関", address: "神奈川県横浜市中区伊勢佐木町２丁目６６満利屋ビル７階", tel: "05015740866", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ＰＬＹ", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜３－２０－５スリーワンビル２０２", tel: "0456206535", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社健商", type: "登録支援機関", address: "神奈川県横浜市瀬谷区阿久和南２－２１－３", tel: "0453600877", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "蒲谷　孝（行政書士かばや孝事務所）", type: "登録支援機関", address: "神奈川県横浜市保土ヶ谷区天王町一丁目２２番地１２ＡＮＥＭＯＳ天王町２０４号", tel: "0454423589", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社城ヶ島水産", type: "登録支援機関", address: "神奈川県三浦市三崎町城ヶ島６５８番地８", tel: "0468813202", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-10" },
    { name: "カインドサポート株式会社", type: "登録支援機関", address: "神奈川県横浜市西区高島二丁目１２番６号　崎陽軒ビルヨコハマ・ジャスト１号館６階", tel: "0454505250", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "ラストル事業協同組合", type: "登録支援機関", address: "神奈川県横浜市緑区鴨居一丁目９番１２号", tel: "0454799777", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "あおぞら協同組合", type: "登録支援機関", address: "神奈川県横浜市神奈川区平川町１４番地３山二ビル２０５号", tel: "0455483855", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社リレーションシップ", type: "登録支援機関", address: "神奈川県横浜市中区蓬莱町一丁目１番地３Ｂｅｌｌｅ関内９０１", tel: "0453348739", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "有限会社シンクリエイティブ", type: "登録支援機関", address: "神奈川県川崎市高津区諏訪一丁目２３番１８号ハニークリエイティブ", tel: "0448115228", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "村上　茂（オフィス　ムラカミ）", type: "登録支援機関", address: "神奈川県横浜市瀬谷区本郷１丁目５５番２１号", tel: "0458840878", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "県央機械工業協同組合", type: "登録支援機関", address: "神奈川県相模原市中央区千代田１－３－１２ニックハイム相模原１F１０２", tel: "0427551745", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "神奈川県建設センター事業協同組合", type: "登録支援機関", address: "神奈川県横浜市中区本町三丁目２４番地本町中央ビル５０１号", tel: "0453054555", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社未来", type: "登録支援機関", address: "神奈川県横浜市港南区最戸一丁目２１－３シティコープ上大岡１－３０５号", tel: "0433089303", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "協同組合ジャスティス", type: "登録支援機関", address: "神奈川県川崎市川崎区砂子二丁目８番１号シャンボール互恵ビル１００６号室", tel: "0442238767", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "協同組合川崎中小企業労務協会", type: "登録支援機関", address: "神奈川県川崎市幸区北加瀬一丁目９番１号", tel: "0445889339", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "ＨＲＳ事業協同組合", type: "登録支援機関", address: "神奈川県横浜市磯子区磯子２－２１－１２", tel: "0453154649", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "事業協同組合相信", type: "登録支援機関", address: "神奈川県相模原市中央区田名４４３６番地１", tel: "0427133943", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社メディアブリッジ", type: "登録支援機関", address: "神奈川県横浜市中区吉田町６５番地ＥＲＶＩＣ横浜", tel: "0427854336", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ジェーピーエー", type: "登録支援機関", address: "神奈川県横浜市神奈川区鶴屋町二丁目２０番地１ＹＴＵビル３階", tel: "0452908250", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "ＭＩＣＳ合同会社", type: "登録支援機関", address: "神奈川県川崎市高津区久本一丁目１２番１７号１０３", tel: "09015477402", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "Ｙ＆Ｒ合同会社", type: "登録支援機関", address: "神奈川県横浜市中区本牧満坂１８７番地４６", tel: "0452646251", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "フォーラム事業協同組合", type: "登録支援機関", address: "神奈川県小田原市千代１８９番地の１", tel: "0465422012", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "日総工産株式会社", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜一丁目４番１号", tel: "0454764121", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "公益社団法人国際人材交流協会", type: "登録支援機関", address: "神奈川県相模原市南区相模大野七丁目２４番１５－５０２号", tel: "0427054001", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社サポートライフ", type: "登録支援機関", address: "神奈川県秦野市曲松二丁目１番３８号", tel: "0463889317", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-11" },
    { name: "協同組合エイ・エス・ジェイ", type: "登録支援機関", address: "神奈川県平塚市唐ヶ原２３番地２", tel: "0463737311", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "株式会社萬珍樓", type: "登録支援機関", address: "神奈川県横浜市中区山下町１５３番地", tel: "0456644006", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "ＳＣＡ事業協同組合", type: "登録支援機関", address: "神奈川県相模原市南区松が枝町４番５号　株式会社中島建設内", tel: "0427337020", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "パッションジャパン株式会社", type: "登録支援機関", address: "神奈川県横浜市西区北幸二丁目５番１７号横浜ＮＳビル", tel: "0456200845", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "ＯＣＳ協同組合", type: "登録支援機関", address: "神奈川県伊勢原市上粕屋６８４番地２", tel: "0463913153", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-12" },
    { name: "ミライヒューマン株式会社", type: "登録支援機関", address: "神奈川県川崎市中原区上丸子山王町二丁目１３４１番地１０", tel: "08022745232", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "髙島　万希子(髙島国際行政書士事務所）", type: "登録支援機関", address: "神奈川県相模原市南区相模大野５－２６－１１第二和田ビル２階", tel: "0428515024", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "よこはま創生協同組合", type: "登録支援機関", address: "神奈川県横浜市西区中央一丁目３５番２１号湘南ビル５０２号", tel: "0452904107", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区塩浜３－２４－９", tel: "0442991797", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区楠町２７－９横浜ウエストビル４０２号", tel: "0453141385", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市南区松が枝町２４番３", tel: "0427025855", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県厚木市中町四丁目１６番２１号", tel: "0462214545", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市旭区都岡町１５番１２", tel: "0459512525", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区西神奈川１－１０－５コスモ東神奈川駅前１００８号室", tel: "0455484952", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区品濃町５１４－６ ボヌール東戸塚４０６", tel: "0454435253", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市鵠沼石上一丁目６番１号エスタビル１Ｆ", tel: "08050096969", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区上矢部町１９６８番地", tel: "0458112771", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区北幸一丁目１番８号エキニア横浜５０３", tel: "0452731272", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区宮前町８番１３号大幸ビル３０３", tel: "0445895691", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区砂子２－８－１シャンボール川崎砂子９１３号室", tel: "0442016432", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市南藤沢５番９号朝日生命藤沢ビル", tel: "0466550881", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県愛甲郡愛川町中津２１５１番地", tel: "0462859600", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区上溝七丁目３番１９号", tel: "0427645588", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市磯子区磯子三丁目３ー２１磯子江戸徳ビル５階", tel: "0457548151", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市多摩区南生田七丁目９番５号ルミエール市村１０２号", tel: "0369143759", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区高島２ー１０ー１３", tel: "0454513191", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県伊勢原市伊勢原一丁目１３番５号　綾部ビル２階A号", tel: "0463599522", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-12" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県秦野市萩が丘１番４号スタープラザビル２０１号室", tel: "0463873465", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-11" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜二丁目３番１９", tel: "0456202040", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県南足柄市塚原４５２４番地１１", tel: "0465703303", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市藤沢４８４番地４９箕田藤沢ビルディング５階", tel: "0466537520", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市藤沢３８番地３", tel: "0466547290", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市東浦賀二丁目１１番２２号", tel: "0468747290", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区汲沢二丁目２３番－９－３０４号", tel: "0454109600", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県座間市相武台三丁目４２番５０号Ｂ", tel: "0462596531", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市長後１２７９ＡＣＡＤＥＭＥＩＡ湘南ビル", tel: "0466479521", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県小田原市中村原７５６番地の１金山ハイツ２０３号室", tel: "0465201136", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市瀬谷区橋戸三丁目６２番地５", tel: "0454596318", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区鶴見中央一丁目１９番５号　新栄ビル４０３", tel: "0456334171", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県大和市大和南二丁目５番１号", tel: "0462648420", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市南区高根町４－２３－６ダイコーパレス阪東橋１０２号", tel: "0453414806", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市南区大野台６丁目１９番１２号大野台クリニックビル４階", tel: "0427048240", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区大倉山６丁目１７番７号", tel: "0459472667", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区相生町二丁目５２泰生ポーチ４階４０４号室", tel: "0459009315", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市藤沢９７１－３　パール湘南４階", tel: "0466255001", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県座間市入谷西４－１－２１ウエストポイント.Ｔビル２F", tel: "0462562525", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区本牧町２丁目３１３番地７サングライス本牧４０３室", tel: "0458838448", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市中原区丸子通１－６３６－４　朝日多摩川マンション２０４", tel: "0447899330", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県大和市桜森２－２６－１３", tel: "0462617710", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区宮川町２－４７大貫ビル３０６号", tel: "08030977335", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市青葉区鴨志田町１３３－７", tel: "0459627146", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区藤塚町１９－２１", tel: "0457445791", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県高座郡寒川町一之宮２－２３－１１　２００－C　２階", tel: "0467555920", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区淵野辺本町３－２８－１", tel: "08077408606", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市走水１丁目３５番地", tel: "0468421031", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ヶ崎市甘沼８６５番１", tel: "0467384165", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県平塚市めぐみが丘１－２１－１０", tel: "0463503019", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区弁天通三丁目４３番地１－２階", tel: "0452288043", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区山下町２　産業貿易センタービルB－１２６", tel: "0452649600", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区日吉本町一丁目6番20号", tel: "0456203945", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市湘南台一丁目１１番６号Ｔビル２階", tel: "0466412150", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市泉区和泉中央南４－１０－２０　Oasis one 1階B", tel: "0454439882", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県逗子市新宿３－１０－１９", tel: "09071839164", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県大和市中央林間西３－２－４６", tel: "0462712291", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市旭区本宿町１８番地１４", tel: "0454894546", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県平塚市菫平３番６号", tel: "0463796712", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ヶ崎市平和町５-１３", tel: "0467591517", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港南区上大岡西１丁目６番１号", tel: "0458425401", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県大和市深見２２００－７", tel: "0462750577", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区下末吉２－２３－３１ サニーサイドＡ棟１０３", tel: "0452945506", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市辻堂神台１丁目３番３９号　オザワビル５０５号室", tel: "0466903788", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市三春町三丁目４４番地", tel: "0468232085", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市辻堂神台一丁目３番３９－５０１－１２号", tel: "0466216075", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区矢部町１４１８番地", tel: "0458618681", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区曙町五丁目６４Ｋビル７０１", tel: "0452639911", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区馬場七丁目１６-１６", tel: "09099502488", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区西之谷町１１５番地", tel: "0452988124", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市追浜町三丁目１番勝野ビル３階", tel: "0468459937", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区常盤町三丁目２５番地　サンビル７階", tel: "0452288033", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区上柏尾町２４６-８", tel: "0454438118", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市緑区橋本台１-２９-３６", tel: "0427031721", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市小川町１４-１", tel: "0468201211", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県座間市相模が丘一丁目２９番１１号", tel: "0427400237", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県平塚市入野３４７-３", tel: "0463343089", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区本牧三之谷１９-２０", tel: "09053330627", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区矢部１－７－１８", tel: "0427074450", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区高島二丁目１１番２号　スカイメナー横浜５１９", tel: "0455505779", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市南区白妙町五丁目６９番アタックビル３階", tel: "0453156131", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市多摩区南生田３-６-２-３", tel: "08010486868", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県伊勢原市桜台２-１３-２８", tel: "0463687089", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-12" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ヶ谷区釜台町３９番地２５", tel: "0455168116", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県鎌倉市七里ガ浜東二丁目９番７号", tel: "07013111978", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市南区東林間５丁目１８番１３号２階", tel: "0428653560", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市幸区小向西町一丁目２０番地２９号", tel: "09085133177", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区獅子ヶ谷二丁目３５番２２号", tel: "0452738615", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県小田原市東町３丁目７番６号", tel: "09021538216", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区尾上町５-８０神奈川中小企業センタービル７階７１０号室", tel: "08043441628", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区星が丘三丁目９番２４号", tel: "08065843910", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区曙町４-５９-５　北見ビル２階", tel: "0459000378", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区千歳町１－２横浜ＴＨビル３０８", tel: "0453347757", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区日吉本町一丁目３８番３－２１８号", tel: "0455638502", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市佐原３－２０－２３", tel: "0468746930", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市高津区久地二丁目９番１０－５０９号フローレンスパレス多摩川緑地", tel: "0442999001", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市青葉区市ヶ尾町１１１番地２", tel: "0452771515", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区弁天通二丁目２５番地関内キャピタルビル７階", tel: "0452258987", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県足柄上郡開成町吉田島４３５２－３ ザ開成プレイス２階", tel: "0465828555", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区綱島西五丁目４番５－１１０３号", tel: "07015732984", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ヶ崎市赤羽根３７６１-１４", tel: "0467559592", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県海老名市今里二丁目２番１６-５０５号", tel: "08020648891", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市磯子区森三丁目１８番２５号ニイヤビル１階", tel: "0453535550", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区砂子１-５-８第一諏訪ビル２０２室", tel: "0442237966", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区相模原２丁目２番１８号", tel: "0427044788", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区千代田４-１２-６", tel: "0427760659", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区鶴見中央４丁目３６番３０号サンセイビルディング９０４号", tel: "0452993062", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港南区港南台４-２５-２５", tel: "0453492629", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区みなとみらい二丁目２番１号　横浜ランドマークタワー４４階", tel: "0452115442", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市緑区十日市場町８３８-４　ラガードビル", tel: "0455304428", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市南区相模大野６丁目７－２ 　３F", tel: "0427053598", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市幸区大宮町１８番地２ナイスアーバンプラザ川崎２F-６", tel: "0442004198", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市高津区久本三丁目４番８－８０５号", tel: "08096875437", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区鶴屋町三丁目３２番地１４新港ビル３０４号", tel: "0455348205", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県綾瀬市寺尾南三丁目１６－１２ＯＡコーポラス３０１", tel: "0467802176", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市南区相模台七丁目４３番２３号", tel: "0427497333", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県厚木市上荻野２７０８番地４", tel: "0462806248", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区宮前町８番１５号パールビルディング５０１号室", tel: "0442807493", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市幸区中幸町３丁目３１－２ DAIKYO KENNKI KAWASAKI BLDG ８F（８－２９）", tel: "08068114281", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区江川１丁目６番１５号", tel: "05035513714", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市湘南台一丁目１１番６号Ｔビル１階", tel: "0466410303", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市南区新川町１丁目２番地６　スタジオデン横濱吉野町Ⅱ　７０１", tel: "09090116561", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区大曽根台９番６号　グリーンヒルズ大倉山１０２", tel: "09052007268", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区渡田山王町２８番１３号", tel: "0443443375", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区矢向二丁目１３番４号レオハイツ１F", tel: "08031755417", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区高根二丁目２番１８号", tel: "0428514405", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区常磐町２－２０　ヴェラハイツ関内３０６号室", tel: "0456631050", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区山下町２番地 産業貿易センタービル６Ｆ", tel: "0456815470", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県愛甲郡愛川町中津１９０２－１サン・ハイツさいとう１０２号", tel: "0462867788", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区小机町９７８番地１", tel: "08051715464", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市金沢区釜利谷西一丁目２２番４号　ラ・ルーチェ１０１号室", tel: "09082761124", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県厚木市飯山４７５０番地１１", tel: "0462806296", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市泉区緑園五丁目２９番地５緑園ＫＭプラザ２階", tel: "0442814998", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市麻生区万福寺一丁目１番１号新百合ヶ丘シティビルディング３０４Ｂ号室", tel: "0442997218", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区鶴屋町２－１２－１　横浜カリオカビル２階", tel: "0453145211", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区矢部町１１００番地", tel: "0459009999", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県平塚市中原３－１－５３", tel: "05035516700", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区渡田４－１２－１１－１０１", tel: "0445776277", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区砂子一丁目８－６長谷川ビル４０３", tel: "0447427475", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区元浜町三丁目２１番地２", tel: "0452228797", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区長者町四丁目９番１号", tel: "09056153498", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市緑区西橋本一丁目１６番１８号", tel: "0427743339", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県小田原市栄町一丁目９番１０号", tel: "0465210551", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県小田原市栄町一丁目１７番３２号", tel: "0465226797", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市南区井土ケ谷上町９番１５号", tel: "0452801683", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区千代田二丁目２番１５号", tel: "0428517146", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市藤沢９７６番地２秀明ビル２Ｆ", tel: "0466533930", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区田名７０７３番地３上溝マンション１号棟１０１号室", tel: "0427600225", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県厚木市棚沢１３５番地８", tel: "0462804940", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区北幸２－５－１７横浜NSビル６０２", tel: "05017229978", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区渡田東町１８番１５号ダイカビル２階", tel: "0442769886", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区鶴見中央五丁目７番２－２１６号", tel: "08090643740", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区矢部町１４１８番地", tel: "0458618681", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県高座郡寒川町倉見１４２５番地６", tel: "08040960963", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区篠原西町２４番１３号", tel: "0452867541", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市高津区末長３丁目１７番１５号", tel: "05035913179", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市高津区諏訪二丁目２番３－１号", tel: "0448137028", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ヶ崎市香川７丁目３－番２６－３号", tel: "09038182132", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県鎌倉市大町七丁目１５６４番地１", tel: "0467613777", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区太田町５－６９－７０１", tel: "0459001555", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市金沢区大道二丁目２２番２４号", tel: "08080271374", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区天王町二丁目３６番地６第７増田ビル３０７号", tel: "0454424734", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区相模原六丁目２６－１２マリノビル４０１号室", tel: "07036263112", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区市場東中町１０番１６号", tel: "0457166878", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜一丁目１３番地６アイシスプラザⅢ５０４号室", tel: "0454726620", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県大和市つきみ野三丁目２５番地４", tel: "08054909455", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県鎌倉市岩瀬５５５番地１", tel: "0467373428", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市柄沢二丁目３６番地１３", tel: "09083818691", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市舟倉一丁目１－２３", tel: "05052419888", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市都筑区見花山１-３０　見花山ビル３階", tel: "07085656494", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区長者町三丁目８番１３号", tel: "0456512755", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市藤沢５５１番地１", tel: "0466538274", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区戸塚町２２３０－３ヒルズ南戸塚３号棟３０１号室", tel: "08043420228", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県大和市大和東三丁目３番１５号", tel: "0462057700", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県綾瀬市吉岡東三丁目４番６号", tel: "0467555125", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区北幸一丁目１１番５号相鉄ＫＳビル", tel: "0452871049", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区青木町６番地２０　１１０１号", tel: "09026735920", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市磯子区洋光台六丁目３４番３４号プレジール洋光台３０３号", tel: "08033080100", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ヶ崎市南湖五丁目６－１第２南湖ビル２０１", tel: "0467814354", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区北幸二丁目１２番２６号フェリーチェ横浜レジデンスＲ００７", tel: "0455779371", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜三丁目７番地１８日総第１８ビル６階", tel: "05037177733", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜三丁目１３番地５宗久ビル８０１号室", tel: "0455774766", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜二丁目１５番１２号", tel: "0455347846", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県小田原市南鴨宮三丁目４－１２ふくもと南鴨宮ビル１階Ｂ号室", tel: "0465208140", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県大和市大和東三丁目３番１５号", tel: "0462406541", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市金沢区六浦東二丁目１２－１４ １０５", tel: "08074351020", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜二丁目１２番地１１", tel: "0452853251", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区峰岡町一丁目２１番地", tel: "0453381533", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区桜木町四丁目２０番地１", tel: "0452648695", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区北幸一丁目１１番５号", tel: "0452870804", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市湘南台三丁目５番地の２", tel: "0466467801", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市長沢一丁目２７番２７号", tel: "0468470700", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区桜木町４丁目２０番地１号　ワイズビル６０１号", tel: "0452120220", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区篠原町１５４７番地１７", tel: "08095783784", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区住吉町一丁目５番地", tel: "0453069808", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区鶴見中央四丁目１７番地１号", tel: "05030912735", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港南区港南一丁目７番２６号", tel: "09017390303", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区駅前本町１１番１号", tel: "0442011435", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港南区日野五丁目３０－８ＵＳテラスハウス１０２", tel: "0458846248", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区相生１－９－３レジデンスピア相生４０３", tel: "09024394207", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区中央三丁目１１番２０号", tel: "0427688124", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市金沢区富岡東六丁目３０番Ｅー５０２号", tel: "0455675858", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市南区松が枝町２３番３", tel: "0427018751", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市中原区木月四丁目４６番１８号", tel: "0444112783", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市宮前区菅生二丁目４番２０号", tel: "0449781002", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港南区日野南三丁目７番１５号", tel: "07044663544", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市青葉区 1－5－4 青葉台サンクスビル　４２号室", tel: "07090361094", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県厚木市旭町一丁目３３番５号本多ビル３Ｆ", tel: "0462818118", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市南区六ツ川１丁目２０４番地", tel: "0453153772", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区尾上町四丁目５７番地横浜尾上町ビル８－８０２", tel: "09011202274", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区保土ケ谷町三丁目２３７番地", tel: "05036291764", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区みなとみらい二丁目２番１号", tel: "0452646431", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜二丁目１４番２６号石川ビル６０１", tel: "0456289963", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区万代町一丁目２番８号", tel: "0452258195", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区住吉町二丁目２１番地１", tel: "0452649873", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市南区西大沼一丁目６番４号", tel: "09052109439", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区金港町７－３　金港ビル７F", tel: "05052118475", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県足柄下郡箱根町湯本４８４番地", tel: "0460855536", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区仏向町１１７８番地１９", tel: "05088804615", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市磯子区磯子二丁目２１番８号", tel: "0453708275", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区大師本町８番１０号", tel: "0287621481", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ケ崎市堤９５－６", tel: "0467914904", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市幸区古市場１７７０正美荘１０１号室", tel: "09038149834", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市緑区白山２－２Ｅ３１２", tel: "08065292599", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区佃野町十丁目６番２０５", tel: "0457166250", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市緑区いぶき野２番地６キャッスルサンシャイン２０５", tel: "0458841185", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区日ノ出一丁目１２番８", tel: "09070044189", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜三丁目８番地８", tel: "0455774042", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区中島三丁目９番９号アレスメディカルビルヂング３３０１号室", tel: "05018078616", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県三浦市三崎三丁目２番１１号", tel: "0468823791", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-10" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県厚木市林三丁目１５番５４号", tel: "0462216311", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ケ崎市小和田１－１５－１４－１", tel: "09049187181", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市緑区橋本三丁目１１番２号小池ビル２A", tel: "0427030756", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区吉浜町２－１０　ＩＤＡビル　５０３号", tel: "0428509797", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区福富町仲通４－５和光中央ビル１０１", tel: "0453259926", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市緑区大山町８番２０号マンションサルナート１０１号", tel: "0427030431", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区北幸二丁目９番３０号横浜西口加藤ビル６Ｆ", tel: "0453176658", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区みなとみらい３－７－１", tel: "09026821656", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ヶ谷区和田一丁目１３番１９－１１３号", tel: "07085592031", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区境之谷３２番地８", tel: "08037239992", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区台町９番地１３ルックハイツ横浜台町８０８号", tel: "0455949684", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市都築区川和町２５５", tel: "0455770369", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県綾瀬市深谷中五丁目１７番１号", tel: "0467780606", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区若葉町二丁目３１番地１ビクトリア・メイフェアハウス３０５号室", tel: "09087479908", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区鶴見中央二丁目２番４－８０８号", tel: "08051177333", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市青葉区荏田西二丁目１－３", tel: "0455305959", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県小田原市蓮正寺７６６番地９", tel: "07089482159", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県厚木市中町四丁目１６番２１号", tel: "0462068808", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市戸塚区柏尾町１２１２－１", tel: "09023020635", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県伊勢原市小稲葉４５８番地", tel: "0463737295", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-12" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市幸区下平間１０８－５ダイアパレス鹿島田４０４", tel: "0442723193", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区本町二丁目２２番地", tel: "0452639124", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区京町三丁目２０番１－１１１６号グリーンシア川崎京町", tel: "0442717343", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区宮前町８番１５号", tel: "0442447838", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区花咲町一丁目４６番地１GSプラザ桜木町１１０４", tel: "0452630306", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市小矢部二丁目２２番６号", tel: "0468870718", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区砂子一丁目１０番地２号", tel: "0442766517", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ヶ崎市松が丘一丁目１番６９号", tel: "0467956278", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区みなとみらい四丁目６番２号　みなとみらいグランドセントラルタワー３Ｆ", tel: "0452648638", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区鶴見中央四丁目３２番１号", tel: "0455027411", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区平沼一丁目１３番１４号", tel: "0453174152", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区不老町三丁目１２番地", tel: "0453196638", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区みなとみらい三丁目７番－１号", tel: "0459000715", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市青葉区市ヶ尾町５９４－１", tel: "0459780260", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区獅子ケ谷一丁目３７番２号", tel: "0456427671", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区長者町五丁目７５－１　スクエア長者町１１１１号室", tel: "0453259265", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ヶ谷区岩間町二丁目１００番地６天王町ハイツ２０１号", tel: "0454448041", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区根岸町３丁目１９８番地２クオス横浜根岸森林公園４０１号室", tel: "08061240682", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区新川通３－４サイトウビル２Ｆ－１", tel: "0447429813", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県茅ヶ崎市香川六丁目２０番３７号", tel: "0467911142", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市磯子区磯子３－１１－２７－３０１室", tel: "08047976768", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市青葉区恩田町９６４", tel: "0457555880", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市中央区千代田二丁目２番１５号", tel: "0428606189", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市都筑区池辺町３３６２番地８", tel: "09060246830", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市南区永田南２－２３－１６ライオンズマンション弘明寺第２　２０８号", tel: "07040655227", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市中原区小杉町２ー３１５メゾネットコスギⅡ１０２", tel: "0442997466", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市多摩区長沢２－８－５－１０１", tel: "0443798319", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市中原区上小田中三丁目６－５　第４メゾン中子４０２", tel: "09014607661", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区三ツ沢西町１１番１８号", tel: "09040187692", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区東久保町３番１６号", tel: "0456637911", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区不老町一丁目２番地１", tel: "09074233338", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県足柄下郡湯河原町門川４９７番地５", tel: "0465630222", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区宮前町８－１５　パールビルディング５０１", tel: "0442807492", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市旭区市沢町１６７-１０３", tel: "05068635804", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市幸区中幸町三丁目３１番２号", tel: "05017215728", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区東神奈川二丁目４３番の１", tel: "0454534851", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区山下町１０６番地１２", tel: "09061840243", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区長者町四丁目９番６号青柳パークビル２０２号室", tel: "0452639253", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区西谷一丁目２１番１－１０１", tel: "05033909485", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市旭区上白根三丁目３８番３号", tel: "0459541134", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県秦野市戸川１１５番地", tel: "0463741155", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-11" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区西戸部町３丁目２７７番地", tel: "09064998642", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横須賀市佐野町六丁目２５番地", tel: "0468014191", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区山内町１－１横浜市中央卸売市場本所水産棟５F（５１９）", tel: "0455485700", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市緑区白山一丁目１２番３号", tel: "0459346087", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区尾上町三丁目４６番地１木村ビル７階", tel: "0456202007", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市青葉区市ケ尾町１１５３－３第２カブラギビル６０６", tel: "0459790120", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市緑区鴨居４－５２－１５", tel: "0459293605", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区浅間町１丁目４番３号ウィザード４０１", tel: "05068653337", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市多摩区登戸１０９３－１１", tel: "0449001200", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市西区高島二丁目１１番２号スカイメナー横浜２０１", tel: "0455948156", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区桜木町一丁目１番地８日石横浜ビル１０階", tel: "0452638670", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市青葉区美しが丘西３－４４－２５", tel: "0454146073", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市高津区久本２－５－１　イースト溝の口１１３", tel: "09071970397", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区峰岡町1丁目１２－１４", tel: "09072611873", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県綾瀬市上土棚中一丁目１０番２９号", tel: "0467919098", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区山下町７０番地３", tel: "0456717585", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区岩井町１－７　アーバン・I保土ヶ谷駅ビル５F３号室", tel: "08040336794", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区東田町８番地　パレール川崎レッド館４０１B室", tel: "0447428438", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区扇町２丁目４－４－６０１号", tel: "08098204824", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区山下町１５８－１", tel: "0452288843", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市鵠沼花沢町２－１第一興産２５号館１階", tel: "08067181828", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市都筑区川和町８６－３・２F", tel: "0454829934", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜１－４－１　日総工産新横浜ビル", tel: "0454704333", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市南区宮元町１－１９－３　アーバンキャッスル吉野町５０１号室", tel: "08066267757", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市神奈川区子安通三丁目３０５番地", tel: "0454403001", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区山下町１８６番地白楽天ビル４F", tel: "0452276870", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市幸区幸町三丁目４番地３", tel: "08078814172", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県藤沢市白旗三丁目３－D－６０６", tel: "08058302101", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県相模原市緑区千木良１２７１番地１", tel: "09047269004", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市麻生区万福寺一丁目１番１号新百合ヶ丘シティビルディング３０４B号室", tel: "0442997218", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区大曽根台３６番１３　コスモ綱島３０１号", tel: "0459006236", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県大和市南林間２丁目１０－７　小幡ビル３F", tel: "0462440022", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市磯子区森２丁目２－３磯子ユーラシアハイム１０６号", tel: "09038357564", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区曙町二丁目１９番地１号曙町新井ビル１００３号", tel: "0453410220", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市鶴見区栄町通三丁目３６番地２６", tel: "09086821666", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区狩場町２００番９", tel: "0457128601", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区西久保町２００－７", tel: "08036635759", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港北区新横浜三丁目７番地７新横浜アリーナ通りビル３F", tel: "07089897011", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県海老名市国分寺台五丁目９番３３号", tel: "07090408208", visa: ["tokutei1"], prefId: "kanagawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市保土ケ谷区東川島町３９－５０", tel: "08061548920", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市港南区上永谷２－１７－１２", tel: "0457529047", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区本町３丁目２４－２ ニュー本町ビル６階", tel: "0453154143", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市中原区小杉町３丁目６００番　コスギサードアヴェニュー ＭＩＤ　ＰＯＩＮＴ　武蔵小杉２－０９", tel: "09042659933", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区日乃出町１－２スカイコート横浜日ノ出町４０２号", tel: "0364265519", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市川崎区藤崎二丁目１８番１９号ー２Ｆ", tel: "05068655818", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県平塚市紅谷町１７番１３号　ＶＩＶＡ２－２F", tel: "0463758972", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市中区石川町１－１３－２ ＴＨＥ　ＨＵＢ 横浜元町１０２", tel: "0455505135", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県川崎市宮前区菅生４－１５－５６", tel: "08030980836", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県小田原市栄町２丁目５－２２　木戸ビル３０４", tel: "0465203232", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県平塚市紅谷町１３－２１", tel: "0463728405", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "神奈川県横浜市緑区中山一丁目１４番１０号", tel: "0455077473", visa: ["tokutei1"], prefId: "kanagawa", districtId: "kanagawa-1" },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();