// kumamoto (136件)
(function(){
  const data = [
    { name: "ベトナムトレーディング株式会社", type: "登録支援機関", address: "熊本県熊本市東区長嶺南４丁目７番１２５ー１号", tel: "0962348770", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "ナウス株式会社", type: "登録支援機関", address: "熊本県宇土市城之浦町１４９番地", tel: "0964276350", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-5" },
    { name: "福島　賢哉（国際行政書士事務所　ＷＯＲＬＤ　ＡＴＬＡＳ）", type: "登録支援機関", address: "熊本県熊本市東区東野１－１－３東野タウンビル飛鳥２０１", tel: "0962857215", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "瑞穂通商株式会社", type: "登録支援機関", address: "熊本県熊本市東区保田窪三丁目４番１５号", tel: "0962855375", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "日越協同組合", type: "登録支援機関", address: "熊本県熊本市東区戸島西一丁目１６－２２", tel: "0962348160", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "くまかい協同組合", type: "登録支援機関", address: "熊本県熊本市東区三郎１－１２－８７", tel: "0962856846", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "木村　憲二（Ｆｏｒｅｉｇｎ　Ｓｕｐｐｏｒｔ　Ｃｅｎｔｅｒ）", type: "登録支援機関", address: "熊本県熊本市北区弓削１丁目１６－５５ロイヤルコンフォ－ト龍田１１０２号", tel: "0362795335", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "ファイン・サービス株式会社", type: "登録支援機関", address: "熊本県阿蘇市一の宮町宮地２００５番地８", tel: "0967229223", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-3" },
    { name: "九州経済交流事業協同組合", type: "登録支援機関", address: "熊本県熊本市東区秋津２丁目１番５８号", tel: "0962017825", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "プラセスワーク協同組合", type: "登録支援機関", address: "熊本県熊本市東区保田窪本町１２－１０", tel: "0962889828", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "業務推進協同組合", type: "登録支援機関", address: "熊本県合志市野々島４３９３－１９０", tel: "0962426468", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-6" },
    { name: "株式会社ツトムＴＴＭ", type: "登録支援機関", address: "熊本県宇城市松橋町豊福２５１３番地１", tel: "0964334471", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-7" },
    { name: "株式会社ネクステイジ", type: "登録支援機関", address: "熊本県熊本市中央区神水本町７番５７号", tel: "0962214119", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社リフティングブレーン", type: "登録支援機関", address: "熊本県熊本市北区弓削五丁目１番１７号", tel: "0963373200", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "亜細亜経済技術支援協同組合", type: "登録支援機関", address: "熊本県菊池郡大津町高尾野字７２０番地", tel: "0962921504", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-4" },
    { name: "熊春協同組合", type: "登録支援機関", address: "熊本県阿蘇市一の宮町宮地６３１５番地１３", tel: "0967241010", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-3" },
    { name: "極東経済交流協同組合", type: "登録支援機関", address: "熊本県阿蘇郡小国町大字宮原１８４６番地", tel: "0967465990", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-2" },
    { name: "熊本県農業協同組合中央会", type: "登録支援機関", address: "熊本県熊本市中央区南千反畑町２－３", tel: "0963281000", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ＫＵＳ", type: "登録支援機関", address: "熊本県熊本市東区京塚本町３９番１０号", tel: "0962239998", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "国際里麗協同組合", type: "登録支援機関", address: "熊本県玉名市大倉１５５１－１", tel: "0968768838", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-8" },
    { name: "東南亜細亜経済交流協同組合", type: "登録支援機関", address: "熊本県熊本市東区長嶺東七丁目１０番４５号", tel: "0962836122", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "日和協同組合", type: "登録支援機関", address: "熊本県熊本市南区富合町平原７３４", tel: "05031861130", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "有限会社ドリーム", type: "登録支援機関", address: "熊本県阿蘇郡小国町宮原１８４６番地", tel: "0967323693", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-2" },
    { name: "河原　聖也（行政書士事務所　Ｎｏｒｔｈ　Ｓｔａｒ)", type: "登録支援機関", address: "熊本県熊本市東区健軍本町３５－３０－３０３　天神ハイツ", tel: "0963000160", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "リリオコーポレーション株式会社", type: "登録支援機関", address: "熊本県菊池郡菊陽町津久礼２４２２番地１３－１Ｆ", tel: "09059488392", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-9" },
    { name: "蒋　毅", type: "登録支援機関", address: "熊本県熊本市中央区本荘町６７４－１２", tel: "09096585683", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "東亜市場開拓協同組合", type: "登録支援機関", address: "熊本県菊池郡大津町大字矢護川１２９４番地", tel: "0962851192", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-4" },
    { name: "佐藤　保久", type: "登録支援機関", address: "熊本県阿蘇郡小国町大字下城２５４５番地３", tel: "09088396645", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区田井島二丁目７番１号", tel: "0963702020", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県菊池市旭志川辺１１２６番地１", tel: "07033276989", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県宇城市松橋町松橋１８８５番地１", tel: "0964274775", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市郡築十番町１５２番地２", tel: "09034630455", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県合志市須屋１９２２番地１", tel: "0962235965", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区桜木三丁目１番３０－１０２", tel: "0962003136", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区出仲間六丁目１５番８号", tel: "09086627450", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県上益城郡益城町宮園５０２－１０", tel: "0962841433", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市北区四方寄町５３１番地２", tel: "0963120285", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区島町三丁目８番２８号INFビル２F", tel: "0962456433", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区水前寺三丁目１４番１ー１０１", tel: "0962889230", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区花立五丁目１０番２５号エスポアール・フルール１０３", tel: "0962348976", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市出町８番９号", tel: "0965317210", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県宇城市不知火町御領１５６－１", tel: "0964429393", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県下益城郡美里町佐俣４８３番地１", tel: "0964462412", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県球磨郡五木村丙字小八重８９４番地１０", tel: "0966363300", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区城南町阿高６６３－３", tel: "05036985511", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市井揚町２６５０番地３", tel: "0965629360", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市鏡町宝出１０４１番地４", tel: "0965378828", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区帯山３丁目１４番８号", tel: "0963843223", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区小山３－８－８７　カームリーハウスＢ２０１", tel: "05088904000", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区田井島２丁目７番４１号", tel: "0963700666", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県玉名郡長洲町長洲　２８８４－６", tel: "0968787878", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区長嶺南八丁目１５番２６号", tel: "0963889171", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市北区楠二丁目１－５１", tel: "0962880462", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県宇土市古城町１８９番地８", tel: "0964429380", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市高島町４１７０－２", tel: "0965320015", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区北千反畑町１－７－４０２", tel: "0962457626", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市西区松尾二丁目２２番１号", tel: "0962885768", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県宇城市不知火町御領７３１番地", tel: "0964343100", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市通町８番３０号", tel: "0965300125", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県宇城市松橋町豊崎２０２７番地１　ステラ　２０７", tel: "09019797744", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区田迎二丁目１７番８号", tel: "0962214119", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区新屋敷１-３-２５", tel: "0963279887", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県玉名市伊倉南方９７７番地５", tel: "0968742973", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県人吉市九日町１０９番地１", tel: "0966329515", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区下通１丁目２番１０号", tel: "0963250084", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区田井島３丁目１１番１００号", tel: "0963794061", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区城南町今吉野１０００番地の１", tel: "0964283300", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県菊池郡大津町室２５番地１", tel: "0962937760", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市郡築一番町１９９番地２", tel: "0965370527", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市北区植木町鞍掛１５２２番地１", tel: "0962733000", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県宇城市松橋町松橋９８８－５　Ｋ店舗", tel: "08058006789", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県人吉市下原田町字荒毛１８９８番地", tel: "0966247131", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県玉名市天水町小天６７３８－１０", tel: "08027736286", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区新生二丁目２番１０号BILLCOM健軍南棟２階２０１号", tel: "0962828245", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区水前寺公園５番４１－２０１号", tel: "0963840414", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区九品寺五丁目１５番５号", tel: "0963754300", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区世安二丁目１番１６号", tel: "0963220050", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区本町２１番２－６１０号", tel: "0962347942", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県玉名郡長洲町大字長洲２８８４番地４", tel: "08039494909", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区月出八丁目２番５号", tel: "09027170863", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区城南町今吉野６００番地１４", tel: "08043119482", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区桜木一丁目１４番１５号", tel: "0963681789", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区上通町１番２０号", tel: "0963561110", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県荒尾市宮内１１７番地４", tel: "08039542319", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県阿蘇市黒川１７５９番地４", tel: "09046697150", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代郡氷川町鹿野８３－２", tel: "0965449013", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区長嶺東４丁目２番４５-１０２号　ディアスクレペール", tel: "09087620228", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市西区田崎町３８０－８", tel: "0963517880", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区若葉一丁目９番１３号", tel: "0963696663", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県荒尾市川登１１６９番地３", tel: "0968577407", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県水俣市丸島町一丁目５番２５号佐々木アパート１０２号", tel: "0966838424", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市古閑下町１８１９番地", tel: "0965332668", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県菊池郡菊陽町原水３５６４", tel: "0962329705", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市北区弓削四丁目８番１号", tel: "0963863855", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区長嶺東六丁目２３番７号", tel: "0963892930", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県玉名市岱明町大野下１５１３-１大野下駅前ハイツ３号室", tel: "0968578303", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市北区植木町正清字箱根崎８８８番地", tel: "0962747700", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県菊池郡大津町大林１５２８番地１３７", tel: "0962433771", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市平山新町２５１８番地１", tel: "0965455378", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市西区島崎二丁目１１番１６号", tel: "0963426372", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県阿蘇郡高森町大字高森２１３２番地１", tel: "0967631165", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県球磨郡錦町大字西７１５番地１８", tel: "09075283191", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区川口町２１１９番地４", tel: "0962885825", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区長嶺南八丁目１５－２７", tel: "0962841518", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区水前寺四丁目５２番５号", tel: "09034108845", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区富合町御船手１５７０番地１", tel: "0962476928", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区上通町１－２５Ｍ’ｓ１（エムズワン）ビル３階", tel: "0963565588", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市西区城山下代四丁目１０番１８号", tel: "0963114745", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区国府本町１２－９", tel: "0963667511", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区南熊本５丁目１０－２８－２０７号", tel: "0963005205", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区西原三丁目１番３５号ＯＮＯビル５階", tel: "0963429555", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区沼山津一丁目１０番２３号", tel: "0962376573", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市北区楠四丁目１０番５号", tel: "08094481002", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市敷川内町６８５番地３", tel: "0965381539", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区黒髪三丁目７番２９号", tel: "0963432250", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市北区楠６丁目６番２５号", tel: "0963386956", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区小峯二丁目２－１１０", tel: "0963279747", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区御領五丁目８番１４号", tel: "0962004634", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県玉名市岩崎１１番地１", tel: "0968745010", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県宇土市新松原町２０７番地３号", tel: "0964276007", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県山鹿市鹿央町千田１８６８番地１", tel: "0968364511", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区神水１丁目３８番１０号", tel: "0963859888", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区新外４丁目１番１号", tel: "09649968739", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市西区島崎５丁目４６番１０号", tel: "0964429192", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区国府四丁目９番８号水幸アパート１０１", tel: "0962478005", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区沼山津四丁目２番２２号", tel: "0963650112", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区城南町下宮地９０５番地８", tel: "09079870115", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県天草市久玉町２００７番地", tel: "0969728711", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区水道町１２－１", tel: "0362638845", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県八代市古閑下町２２２４番地", tel: "0965629777", visa: ["tokutei1"], prefId: "kumamoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区水前寺１丁目９番６号", tel: "0963859002", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市中央区新市街４番１８号酒湊ビル", tel: "0963562278", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市西区上熊本２丁目７番１４号シャローム上熊本１階", tel: "0368204379", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市西区池田２丁目１－５３－３０２号", tel: "0963426444", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市南区島町３丁目８番２８号ＩＮＦビル２Ｆ", tel: "0962456433", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "熊本県熊本市東区若葉１丁目１２－１オカムラビル１階", tel: "0925616611", visa: ["tokutei1"], prefId: "kumamoto", districtId: "kumamoto-1" },
  ];
  if (window.VISA_DATA && VISA_DATA.agencies) {
    VISA_DATA.agencies.push(...data);
  } else {
    window._pendingAgencies = window._pendingAgencies || [];
    window._pendingAgencies.push(...data);
  }
})();