// 登録支援機関データ - kyoto (149件)
(function(){
  const data = [
    { name: "一般社団法人海外技術交流社団", type: "登録支援機関", address: "京都府京都市右京区花園馬代町２－２１", tel: "0759259251", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "新谷　義雄（行政書士しんたに法務事務所）", type: "登録支援機関", address: "京都府京都市右京区龍安寺池ノ下町５番地２", tel: "09011568820", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "ライズＮＥＯ協同組合", type: "登録支援機関", address: "京都府舞鶴市字浜８１６番地", tel: "0773631110", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "グローバル経済交流協同組合", type: "登録支援機関", address: "京都府京都市右京区西院平町２５番地ライフプラザ西大路四条３階", tel: "0759256572", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "ＢＩＧ協同組合", type: "登録支援機関", address: "京都府綴喜郡井手町大字井手小字下赤田８１番地", tel: "09032802828", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "せんと協同組合", type: "登録支援機関", address: "京都府京都市南区上鳥羽清井町２０６番地", tel: "0756918712", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "一般社団法人ＡーＴｒｕｓｔ", type: "登録支援機関", address: "京都府京都市伏見区醍醐大高町１５－２", tel: "07090913133", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ＳＡＮＳＥＩ", type: "登録支援機関", address: "京都府京都市伏見区横大路下三栖南郷２５番地", tel: "0756236111", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "岡田　知（岡田国際行政書士事務所）", type: "登録支援機関", address: "京都府福知山市字堀２５９５番地の２", tel: "0773227655", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "一般社団法人毎日オフィスユニオン", type: "登録支援機関", address: "京都府京都市伏見区桃山町大島１２８－１６", tel: "0756028526", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社クリアビジョン", type: "登録支援機関", address: "京都府京都市南区東九条松田町１５番地十条産業ビル２階", tel: "0756620607", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社キャリアタイム", type: "登録支援機関", address: "京都府京都市下京区西洞院通四条下る妙伝寺町７２０－４F", tel: "0753541110", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ユウキ", type: "登録支援機関", address: "京都府亀岡市本梅町平松谷ケ奥７番地４", tel: "0771265454", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "一般社団法人くらしの相談支援センター", type: "登録支援機関", address: "京都府京都市南区久世上久世町５４２－３２８", tel: "0759335804", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社スマイルズ", type: "登録支援機関", address: "京都府京都市左京区一乗寺梅ノ木町８５番地１マックスビル３階", tel: "0757222525", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社コイズミデザイン", type: "登録支援機関", address: "京都府京都市右京区太秦開日町５番地４", tel: "0758653808", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "きずな協同組合", type: "登録支援機関", address: "京都府京都市伏見区羽束師鴨川町７９－１リジェール鴨川３０７号室", tel: "0757576998", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "大西　祐子（行政書士事務所アシスト）", type: "登録支援機関", address: "京都府木津川市城山台十三丁目２３番地４", tel: "0774275950", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "大嶋　信介（行政書士・海事代理士　大嶋法務事務所）", type: "登録支援機関", address: "京都府京都市中京区御倉町７５ ファーストコート三条４F－１７", tel: "0752044473", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社インディペンデンス", type: "登録支援機関", address: "京都府京田辺市同志社山手四丁目１番地１２４", tel: "0774260116", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "アジアキャリアサービス合同会社", type: "登録支援機関", address: "京都府京丹後市久美浜町佐野１２６番地", tel: "0772849000", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "松本　篤人（優京　ネクスト）", type: "登録支援機関", address: "京都府京都市下京区醒ヶ井高辻下る住吉町５０５番地１　デュオヒルズ京都烏丸　５０２", tel: "09091132620", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ＫＹＯＴＯ　ＦＯＲＥＩＧＮＥＲ　ＳＵＰＰＯＲＴ", type: "登録支援機関", address: "京都府京都市伏見区深草小久保町２１０番地", tel: "09042862770", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社クライム", type: "登録支援機関", address: "京都府京都市西京区大原野西境谷町一丁目１１番地５", tel: "0753355528", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社キョーセンサービス", type: "登録支援機関", address: "京都府亀岡市馬路町堂ノ西３番地１", tel: "0771255767", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "関西経友会事業協同組合", type: "登録支援機関", address: "京都府京都市南区吉祥院九条町３０番地１　江後経営ビル", tel: "0756936400", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "髙谷　滋樹（都総合法律事務所）", type: "登録支援機関", address: "京都府京都市中京区山伏山町５４０丸池藤井ビル５階　都総合法律事務所", tel: "05057994519", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府与謝郡与謝野町字加悦奥１３１６番地", tel: "0772424881", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区七条通猪熊東入ル西八百屋町１６０番地", tel: "0753432722", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区石田桜木１１番地２１", tel: "0756446868", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府船井郡京丹波町三ノ宮小谷３０番地", tel: "0771880150", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区烏丸通六角下ル七観音町６２３番地第１１長谷ビル", tel: "0752113088", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市山科区西野左義長町３１番地の５", tel: "0755914048", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京丹後市弥栄町溝谷５４４３－１", tel: "0772654130", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市右京区嵯峨新宮町７番地１シーズン嵐山２０６", tel: "0758745545", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市南区東九条明田町３９番地１２", tel: "08091670972", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府南丹市園部町新町火打谷１番地３", tel: "0771868011", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府福知山市三和町下川合３７番地の４", tel: "0773583366", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区石田大受町３１－９４", tel: "0755731161", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府亀岡市篠町篠向谷４３番地３５", tel: "09095423668", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区竹田西段川原町８９番地", tel: "0756435700", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区四条通新町東入月鉾町３９番地１四条烏丸大西ビル９０４号", tel: "0757082938", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市淀池上町１３６－２－３０１", tel: "0756325075", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市南区吉祥院嶋野間詰町１１番地", tel: "0756719100", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区竹田東小屋ノ内町１０６", tel: "0756041170", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府亀岡市曽我部町重利風ノ口１９－２", tel: "0771228806", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府宇治市小倉町南浦２８番地９号２階", tel: "0774853681", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府久世郡久御山町田井向野４０番地", tel: "0774413370", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区竹田向代町５１－５", tel: "0756819757", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府久世郡久御山町田井向野４０番地", tel: "0774411655", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区小川通蛸薬師上ル元本能寺町３８２", tel: "0757416026", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市左京区岩倉村松町２０３番地", tel: "0757077878", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区中堂寺粟田町９３ＫＲＰ４号館３階ＫＲＰ・ＢＩＺ・ＮＥＸＴ", tel: "0759500432", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市左京区下鴨狗子田町５－５", tel: "0757237720", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区西ノ京東中合町４２　オリエントビル５Ｆ", tel: "0753666735", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区桃山長岡越中南町６２－３", tel: "0756110826", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市西京区樫原平田町１５－４５", tel: "0757546712", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府向日市寺戸町大牧６番地１８", tel: "0759255691", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府宇治市大久保町井ノ尻３９番地の３　中川ビル２０７号", tel: "0759837365", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市上京区一条通御前通西入三丁目西町４９番", tel: "0754965953", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市右京区西院西貝川５９－２", tel: "0758744282", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草泓ノ壺町１７-４ 藤和ライブタウン伏見５２０", tel: "0752019026", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市西京区上桂北ノ口町２０５", tel: "0753941888", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区中堂寺坊城町６５番地パークスクエア", tel: "0758032662", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区富小路通五条下ル本塩竈町５５８－８昭栄ビル５階B", tel: "0753658185", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草西浦町五丁目５３-１ペガサスプラザ２０５", tel: "0756420810", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市右京区西院西田町２６番地", tel: "0759504515", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府船井郡京丹波町中台桜梅７１－３０", tel: "08059789261", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草山村町１０１８-１", tel: "08075845848", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区加茂川端正面上ル平岡町３７７番地の１", tel: "0753715110", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区新町通松原下る富永町１０７番地１", tel: "0755855074", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府南丹市園部町新町火打谷１番地３　２Ｆ", tel: "0771868022", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区室町通五条上る板東屋町２７２番地", tel: "0433012111", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区四条通室町東入函谷鉾町１０１アーバンネット四条烏丸７Ｆ", tel: "0752794247", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府城陽市平川指月５８－２　田辺ビル３F－A", tel: "0774667320", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草西浦町六丁目５９番地１　メゾンマツヨシ２０４号", tel: "0756449399", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市右京区西院西貝川町６５－７", tel: "0758658141", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府亀岡市亀岡駅北一丁目５番地２", tel: "0774748288", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区竹田北三ツ杭町４５番地　アイビー・ビル２A", tel: "0756061258", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市左京区下鴨東本町２６番地３、７F", tel: "0757121505", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府綾部市幸通り１１番地", tel: "0773422055", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府舞鶴市字溝尻小字長谷山１番地の３３", tel: "0773639686", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区七条通東堀川西入八百屋町５番地", tel: "0753664233", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府亀岡市篠町見晴６丁目２番９号", tel: "08091280069", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市北区鞍馬口通寺町東入２丁目鞍馬口町３１１番地１", tel: "0757572099", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区大宮通綾小路下る綾大宮町４４", tel: "0758223531", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草池ノ内町１０番地１４", tel: "0756002698", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区柳馬場六角下る井筒屋町４２１番地", tel: "0752555500", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府木津川市相楽台九丁目５番１号フローレス高の原２０７号", tel: "09059088091", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市南区東九条宇賀辺町１８－１", tel: "0756721515", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区蛸薬師通烏丸東入一漣社町３００番地パームビル３０８", tel: "08051801981", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府宇治市木幡中村１９番地の１８", tel: "09033553026", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府木津川市城山台七丁目３４番地８", tel: "0774804678", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府相楽郡精華町祝園西一丁目２４番地１", tel: "0774340882", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市左京区岩倉幡枝町７８５番地４９", tel: "0757463845", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草直違橋七丁目２６６番地１", tel: "0756424477", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市南区吉祥院西ノ庄西中町１番地Ｇｌａｎｚ八条２Ｆ", tel: "0753135574", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市上京区東堀川通丸太町上る六町目２１３番地", tel: "0757418992", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市右京区太秦安井馬塚町１２番地１４", tel: "0758880170", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草大亀谷万帖敷町３番地の２３", tel: "09077650544", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区西ノ京左馬寮町２１番地３２", tel: "09081205990", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市左京区聖護院蓮華蔵町５１番地１", tel: "0757527350", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市南区西九条柳ノ内町８３番地４ぷらむビル４階", tel: "0756329947", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区七条御所ノ内中町６４番地１", tel: "0753266333", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市山科区音羽沢町２番地の１９", tel: "0756120505", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区西七条掛越町６０西大路ハイム５１０", tel: "08046065577", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区御影堂町１６－２１京都建物ビル５Ｆ", tel: "08098258822", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府舞鶴市字上安久６４０番地６", tel: "0773751075", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区烏丸通四条上ル笋町６８８第１５長谷ビル９階", tel: "0757463518", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府綾部市大島町外山田１番地１エスポール２－Ｃ", tel: "0773420821", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府福知山市篠尾新町一丁目７５番地グランコート篠尾新町", tel: "0773240180", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市西京区上桂森下町１番地１２１", tel: "0753831116", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市西京区上桂森下町１番地１２１", tel: "0753831116", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区六角油小路町３３８番地", tel: "0752116720", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草池ノ内町２番地３０", tel: "0756422278", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市西京区大原野上里北ノ町１３２８番地３３", tel: "05010265320", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府乙訓郡大山崎町字大山崎小字尻江２９番地６　２０９号", tel: "09029594409", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区常真横町１９０－５ＮＨＫビル ４０１", tel: "0754067307", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市北区上賀茂池殿町２９－１０", tel: "0753664291", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区二条油小路東入る西大国町３１８", tel: "08014755380", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区七条通間之町東入材木町４７１番地１０", tel: "0755854956", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市右京区西院西貝川町６５番地７", tel: "0758658141", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市左京区吉田神楽岡町７６番地", tel: "0757710088", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市中京区三条通高倉東入桝屋町５７", tel: "0756000223", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市左京区一乗寺築田町１７－４", tel: "09083829540", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府相楽郡精華町光台六丁目５番地５", tel: "0774951811", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府相楽郡精華町光台一丁目７けいはんなプラザ９階", tel: "0774666994", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市山科区御陵別所町１２７－８", tel: "09088883693", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府向日市寺戸町山縄手２１番１京都フィナンシャルグループ MUKOUビル３階", tel: "0753255550", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市上京区土屋町通出水上る弁天町２９９番地", tel: "09011501163", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府舞鶴市字大波下２８５番地", tel: "0773624577", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府福知山市字天田２０５－９　２０２号", tel: "0773489881", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府福知山市字三俣５７２番地", tel: "09085706920", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府宇治市莵道籔里４１－５０８", tel: "0774246114", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府長岡京市神足七ノ坪６番地", tel: "0756939505", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区下鳥羽中円面田町３１番地", tel: "0756055626", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区西錺屋町１６－２眞栄五條ビルヂング４F", tel: "0757416129", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市西京区川島有栖川町７－１　サムソンビル３０３", tel: "0753822772", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市山科区音羽草田町１８番地３５－１F", tel: "0756444074", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市南区西九条寺ノ前町３番地", tel: "09015683672", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市下京区梅湊町８３－１　京都市市民活動総合センター", tel: "0753717060", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区醍醐大高町１５番地２", tel: "0752023133", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府八幡市岩田西玉造７７番地", tel: "0759726666", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府亀岡市保津町社ノ下１番地１０", tel: "0771229330", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府舞鶴市字伊佐津４７４番地の３", tel: "0773752067", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市南区西九条寺ノ前町６番地", tel: "0756711939", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市南区西九条池ノ内町１８番地の１", tel: "0756827577", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市右京区西院西矢掛町１８－２　アールグランツ西院３０５", tel: "08040141218", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "京都府京都市伏見区深草善導寺町３－４６", tel: "08080496768", visa: ["tokutei1"], prefId: "kyoto", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();