// miyagi (89件)
(function(){
  const data = [
    { name: "事業アシスト協同組合", type: "登録支援機関", address: "宮城県塩竈市舟入二丁目１番２６号", tel: "0223693840", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-3" },
    { name: "金　成吉（行政書士・社労士　仙台第一事務所）", type: "登録支援機関", address: "宮城県仙台市青葉区五橋１－５－２８－１１０５", tel: "0222268584", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "有限会社Ｂ・Ｐ・トレーディング", type: "登録支援機関", address: "宮城県黒川郡大郷町東成田字板谷西山１３番地の１７", tel: "0223595943", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-4" },
    { name: "株式会社仙台フォレスト", type: "登録支援機関", address: "宮城県仙台市青葉区木町通一丁目８－２８　三栄木町通ビル３Ｆ", tel: "0223436025", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社Ｈ＆Ｓ　ＣＯ．，ＬＴＤ", type: "登録支援機関", address: "宮城県仙台市宮城野区中野５丁目６番地の２３", tel: "0223555057", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "東洋ワーク株式会社", type: "登録支援機関", address: "宮城県仙台市青葉区国分町一丁目７番１８号", tel: "0222255052", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "翼協同組合", type: "登録支援機関", address: "宮城県仙台市若林区鶴代町６番３号", tel: "0227838580", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "協同組合信", type: "登録支援機関", address: "宮城県仙台市宮城野区鉄砲町中３ー４プラザ和光４０７", tel: "0223570924", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "宮城フィッシャリー・フーズ協同組合", type: "登録支援機関", address: "宮城県宮城郡七ヶ浜町境山２丁目１番１号", tel: "0223535032", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-5" },
    { name: "キョーワ・システム株式会社", type: "登録支援機関", address: "宮城県仙台市若林区石名坂２７－４", tel: "0222819751", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "新沼　理香（国際経済技術支援）", type: "登録支援機関", address: "宮城県仙台市宮城野区榴ヶ岡１０８－１０－３０６", tel: "0227625383", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "ジェー・オー・ピー協同組合", type: "登録支援機関", address: "宮城県仙台市青葉区福沢町４番８号", tel: "0222245473", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "ＳｏｌｖｅＨＲ　株式会社", type: "登録支援機関", address: "宮城県仙台市青葉区本町１丁目５番２８号　カーニープレイス仙台駅前通２０１号室", tel: "0227972822", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社パルズスタッフィング", type: "登録支援機関", address: "宮城県仙台市宮城野区榴岡四丁目５番２２号", tel: "0222925011", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社マリック関根貿易", type: "登録支援機関", address: "宮城県石巻市明神南６番地１０", tel: "0225237160", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-2" },
    { name: "ＴＷＧ 外国人育成就労協同組合", type: "登録支援機関", address: "宮城県黒川郡大和町吉岡字東車堰３６－５", tel: "0227255252", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-6" },
    { name: "株式会社ワールドウォーカーズ", type: "登録支援機関", address: "宮城県塩竃市玉川一丁目５番４０号", tel: "0223637080", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-7" },
    { name: "特定非営利活動法人石巻漁業実習協議会", type: "登録支援機関", address: "宮城県石巻市鹿妻南四丁目１－６１", tel: "0225249101", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-2" },
    { name: "株式会社人事・教育サービス", type: "登録支援機関", address: "宮城県仙台市青葉区五橋一丁目１番５８ダイアパレス仙台中央１０６号室", tel: "0222267255", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "情報管理システム協同組合", type: "登録支援機関", address: "宮城県仙台市青葉区中央一丁目６番２７号", tel: "0227263081", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "三陸アシスト協同組合", type: "登録支援機関", address: "宮城県気仙沼市本吉町坊の倉６７番地の３", tel: "0226422655", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-8" },
    { name: "有限会社三藤", type: "登録支援機関", address: "宮城県仙台市若林区日辺字畑田１７８", tel: "0222891020", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "宮城県農水産サービス振興協同組合", type: "登録支援機関", address: "宮城県白石市字中町１１井丸ビル３階", tel: "0224252088", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-9" },
    { name: "株式会社日将コンサルティング", type: "登録支援機関", address: "宮城県多賀城市伝上山三丁目３１番１－４０６号", tel: "0227626883", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-10" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市若林区白萩町１２－５", tel: "0222909321", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市太白区ひより台４６番３１号", tel: "0222456403", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区米ケ袋一丁目１番１４号片平レジデンス３０３", tel: "0227968596", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県刈田郡七ケ宿町愛宕下５２番地４", tel: "0224268688", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市泉区南中山１丁目４１－４", tel: "0222360084", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市宮城野区宮城野一丁目１２番１５号", tel: "0222925181", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区一番町二丁目８番１０号", tel: "0227146131", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市宮城野区扇町二丁目４番３０号", tel: "0223524246", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区花京院二丁目１番５号", tel: "0227486551", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県宮城郡七ヶ浜町花渕浜字鹿野５番地の１", tel: "08088215500", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県大崎市古川清水字新田３４番地２", tel: "0229259951", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県塩竈市新浜町３丁目２番１５号", tel: "0223671551", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区本町三丁目１番１７号", tel: "0223983815", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市泉区松森字斉兵衛５８番地の５２", tel: "0227710743", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市若林区種次字道元７２", tel: "0223495946", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県気仙沼市弁天町一丁目８番１７号", tel: "0226220500", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県塩竈市白萩町６番１２号", tel: "09044798678", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県石巻市魚町一丁目７番地３　石巻市水産加工業協同組合内３階", tel: "0225965707", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県気仙沼市魚市場前３番３８号", tel: "0226296355", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区上杉１－７－１７　１Ｆ", tel: "09029750024", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区大町二丁目１３番４－２０５号", tel: "0227967548", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区宮町三丁目５-２９馬淵事務所２階", tel: "0223956411", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県多賀城市町前三丁目１番４３号", tel: "0223651887", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-10" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県石巻市中里六丁目１４番２４号", tel: "09063002932", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市泉区歩坂町３３番１７号", tel: "0223410234", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県富谷市富谷新町９５ ２階", tel: "08060589517", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区一番町一丁目１番８号　青葉パークビル３階", tel: "0223025846", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県名取市手倉田字八幡７５ー１ シャローネ星１０１", tel: "0227977932", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市泉区加茂一丁目３０番地の１２", tel: "0227033657", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市太白区柳生７－２６－５", tel: "0223520290", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市泉区高森８－２－９", tel: "08056099215", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区一番町一丁目１２－２　星光堂ビル６Ｆ　ジテキベース", tel: "08018285569", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区柏木一丁目２番４５号　\nフォレスト仙台１１Ｆ", tel: "0223449361", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市泉区歩坂町３３番１７号", tel: "0223410234", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市太白区鈎取二丁目２４番３６号", tel: "0223411941", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市宮城野区鉄砲町中６番地の５シャーメゾンアゼリア１０１", tel: "0223554494", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県塩竈市北浜町四丁目１６番３１号", tel: "0223619570", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区国分町一丁目８番１４号", tel: "0222046640", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県亘理郡亘理町荒浜字築港通り９番４３", tel: "0223231355", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区一番町二丁目１１－１２", tel: "0227247648", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区花京院二丁目１番６１号　オークツリー仙台９階", tel: "0222909838", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県大崎市古川駅南１丁目２５オフィスサウスＩ", tel: "08052011667", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市太白区鹿野２丁目１８－７－９０１号", tel: "0223536694", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県石巻市羽黒町二丁目３番１８号", tel: "0225983570", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県栗原市築館青野８番１０号", tel: "0228248447", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県本吉郡南三陸町志津川字天王山１３５番地２６", tel: "0226485865", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市太白区砂押町７番１０号グリーンハイツD１０２", tel: "0223526508", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県富谷市日吉台一丁目１７番地３", tel: "09079376716", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市宮城野区榴ケ岡１０８番地１０プレジデント榴ケ岡３０６", tel: "0227625407", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市若林区日辺字田中１１番地", tel: "0222896768", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区一番町３－３－１　クラックス仙台４Ｆ", tel: "0227111364", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市若林区大和町三丁目５番１０号大和ビル３０２号室", tel: "0223693032", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県多賀城市高橋三丁目１５－４０", tel: "0227078139", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-10" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県栗原市高清水中の茎３２番地３", tel: "08033202610", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区花京院一丁目５番２２号", tel: "09029929978", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市若林区卸町４ー７－８仙台水産ビル４階４１２", tel: "0223855390", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市宮城野区栄２－８－８", tel: "08054460325", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県富谷市上桜木一丁目３５番地１３", tel: "0223421470", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市若林区六丁の目北町１番５８号　シャルムエンドウ２０１", tel: "0223855617", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県牡鹿郡女川町市場通り７０番地５", tel: "0225534455", visa: ["tokutei1"], prefId: "miyagi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市泉区住吉台東五丁目５番地の８", tel: "0227252180", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区本町一丁目１３番３２号", tel: "0223959814", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県石巻市蛇田字東道下１５８－２", tel: "0225255427", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県石巻市鮎川浜北１８番地", tel: "0225452515", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "宮城県仙台市青葉区二日町１４番４号　北四番丁ステーションビル２階", tel: "0222250522", visa: ["tokutei1"], prefId: "miyagi", districtId: "miyagi-1" },
  ];
  if (window.VISA_DATA && VISA_DATA.agencies) {
    VISA_DATA.agencies.push(...data);
  } else {
    window._pendingAgencies = window._pendingAgencies || [];
    window._pendingAgencies.push(...data);
  }
})();