// nagasaki (71件)
(function(){
  const data = [
    { name: "青山　周広（青山行政書士法務事務所）", type: "登録支援機関", address: "長崎県長崎市中町２番２号　興士会館４階", tel: "0958328100", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "光武　幸治（行政書士光武幸治法務事務所）", type: "登録支援機関", address: "長崎県佐世保市万津町７番８号", tel: "0956555702", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "長崎県中小企業ビジネス支援協同組合", type: "登録支援機関", address: "長崎県西海市西彼町下岳郷９５１番地１", tel: "0959375011", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-5" },
    { name: "西日本産業交流事業協同組合", type: "登録支援機関", address: "長崎県佐世保市干尽町４８番地", tel: "0956342205", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "ＦＲＯＭながさき協同組合", type: "登録支援機関", address: "長崎県長崎市上戸町四丁目３５２番地２", tel: "0958944301", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "ＳＳＫ協力事業協同組合", type: "登録支援機関", address: "長崎県佐世保市立神町２２番地", tel: "0956236407", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "ＡＲＵＫＯＯ　Ｇｌｏｂａｌ　Ｗｏｒｋｓ株式会社", type: "登録支援機関", address: "長崎県佐世保市大潟町３１６－８", tel: "09015107757", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社エヌ", type: "登録支援機関", address: "長崎県平戸市田平町里免２７番地１", tel: "0950201201", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-6" },
    { name: "未来創造事業協同組合", type: "登録支援機関", address: "長崎県雲仙市愛野町甲３８７６番地7", tel: "0957362011", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-3" },
    { name: "西日本食品産業事業協同組合", type: "登録支援機関", address: "長崎県諫早市松里町１６２８番地５４", tel: "0957280086", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-4" },
    { name: "株式会社シンコー", type: "登録支援機関", address: "長崎県佐世保市万津町１番１１号", tel: "0956421523", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "九州アジアン産業支援協同組合", type: "登録支援機関", address: "長崎県大村市久原一丁目５９５番地１", tel: "0957424233", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-7" },
    { name: "ふれあい事業協同組合", type: "登録支援機関", address: "長崎県諫早市高来町冨地戸４６１番地", tel: "0957348181", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-4" },
    { name: "九州経営サポート協同組合", type: "登録支援機関", address: "長崎県雲仙市国見町多比良丙１００番地－２", tel: "0957739908", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-3" },
    { name: "長崎県青果移出商業協同組合", type: "登録支援機関", address: "長崎県雲仙市吾妻町阿母名９番地１", tel: "0957383535", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-3" },
    { name: "長崎県アジア産業交流協同組合", type: "登録支援機関", address: "長崎県長崎市大橋町１０番２２号", tel: "0958417622", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "ＭＡＮＡＢＩＪＵＫＵ　合同会社", type: "登録支援機関", address: "長崎県長崎市出雲一丁目８番３６－８０１号", tel: "05017251151", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県諫早市宇都町３番５０号", tel: "0957246678", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市卸本町５番４８号", tel: "0956341100", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県島原市新馬場１３６番地４", tel: "0957610703", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市葉山１丁目２８－３２", tel: "0120562125", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市江の浦町１８番１号", tel: "0958616411", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県五島市平蔵町１４６０番地", tel: "0959730126", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県松浦市調川町下免字牛ノ鼻８５１番５７", tel: "0956720909", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市白岳町１１６８番地", tel: "0956596531", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県西海市西彼町大串郷１８３５番地", tel: "09054761331", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県東彼杵郡東彼杵町瀬戸郷３３４番地４", tel: "09071588668", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県五島市岐宿町二本楠２８５番地３", tel: "0959831274", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市城山町５番１１号ハレアカラ５０１", tel: "0956887641", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県諫早市本野町７２７ー１", tel: "09059208067", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市上銭座町１１番８号", tel: "0958657177", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市高尾町２番１５号", tel: "0958945420", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県諫早市飯盛町野中９３８番地８", tel: "09011653756", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市花園町２０１番地", tel: "0956421060", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市上銭座町１１番８号", tel: "0958657186", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市川口町１０番２号", tel: "0958487772", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市松山町３番９０号", tel: "0958485600", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市上小島三丁目１番８号", tel: "0958249938", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市松山町４番４８号　囲ビル２F", tel: "07050853685", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県大村市鬼橋町１９３－７", tel: "09086298127", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市小佐々町矢岳１０６２番３号", tel: "0956692075", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市栄町４番１７号", tel: "0958253344", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県雲仙市吾妻町平江名１１７－１", tel: "0957369838", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県諫早市松里町１６２８番地５４", tel: "0957280086", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市大浦町２番２５－９０１号", tel: "0958200850", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県諫早市栄田町３２番２３号", tel: "0957465579", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県諫早市貝津町１７２６番地５", tel: "0957463388", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県島原市本町乙４８７番地１", tel: "0957739423", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市桜町３番１５号", tel: "0958005100", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市籠町５番２３号", tel: "0958957407", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市魚の町７番２０号", tel: "08058067990", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市茂里町３番１号", tel: "0958938888", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市万才町３番４号", tel: "0958958531", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市小佐々町黒石３２８番地３", tel: "0956682637", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市小江原１丁目３６番１２号", tel: "0958466540", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市鍛冶屋町６番３号４０２", tel: "0958944649", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県西彼杵郡長与町三根郷３５７番地", tel: "0958872808", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市かき道四丁目２２番２０号", tel: "08039939395", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市戸尾町３番７号", tel: "0956238770", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市現川町３３５番地１", tel: "0958075151", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市上小島三丁目１番８号", tel: "0958273524", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市出島町５番２号", tel: "0958116071", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市天神三丁目２３９番地２７", tel: "0956887277", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県佐世保市万徳町８番２２号", tel: "0956556135", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市横尾三丁目２６番１号", tel: "0958013003", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県島原市有明町湯江丁１３番地１５６", tel: "0957680086", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市赤迫二丁目１１番３８号", tel: "0958572275", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県島原市長貫町丙２０８３番地", tel: "0957626550", visa: ["tokutei1"], prefId: "nagasaki", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市戸町４丁目１番１４号", tel: "0958955755", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市丸山町１番２８号", tel: "09045893682", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "長崎県長崎市西山台１丁目１５番１号", tel: "0958480088", visa: ["tokutei1"], prefId: "nagasaki", districtId: "nagasaki-2" },
  ];
  if (window.VISA_DATA && VISA_DATA.agencies) {
    VISA_DATA.agencies.push(...data);
  } else {
    window._pendingAgencies = window._pendingAgencies || [];
    window._pendingAgencies.push(...data);
  }
})();