// 登録支援機関データ - niigata (70件)
(function(){
  const data = [
    { name: "播磨　史雄（Asocia行政書士法務事務所）", type: "登録支援機関", address: "新潟県新潟市西区平島２丁目１３番地１１　２階", tel: "0252017514", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社グローバルステーション", type: "登録支援機関", address: "新潟県北蒲原郡聖籠町次第浜２０４９番地７", tel: "0254273502", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "富安事業協同組合", type: "登録支援機関", address: "新潟県新潟市中央区女池神明３－５－３", tel: "0252787305", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "行政書士法人みなみ法務事務所", type: "登録支援機関", address: "新潟県新潟市東区下木戸１丁目４番１号", tel: "0252721390", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "有限会社パワーステージ", type: "登録支援機関", address: "新潟県上越市寺町二丁目１０番２５号", tel: "0255212695", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "ＥＮＷＡコンサルティング株式会社", type: "登録支援機関", address: "新潟県新潟市中央区女池上山三丁目１４番１０", tel: "0253840491", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社川﨑コーポレーション", type: "登録支援機関", address: "新潟県新潟市中央区南笹口一丁目１－３８号コープオリンピア笹口４０５号", tel: "0252568830", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "グローバルサポート協同組合", type: "登録支援機関", address: "新潟県北蒲原郡聖籠町大字次第浜２０４９番地７", tel: "0254273502", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "ケア・アジャスト協同組合", type: "登録支援機関", address: "新潟県中央区東中通一番町２０１番地１トーカンマンション東中通り外階段２階２号室", tel: "0250245029", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ＷＩＮＤＳ　ＣＯＲＰＯＲＡＴＩＯＮ", type: "登録支援機関", address: "新潟県長岡市寺泊野積１０７番地１７５", tel: "0258867140", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "ＪＩグローバルライフ合同会社", type: "登録支援機関", address: "新潟県新潟市西区小針二丁目３５番５号佐山第一ビルA", tel: "0253784751", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "新潟経成会国際化支援事業協同組合", type: "登録支援機関", address: "新潟県長岡市新保一丁目１２番２０号", tel: "0258868872", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "県央加工協同組合", type: "登録支援機関", address: "新潟県燕市小池３３３０番地５", tel: "0256632182", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "新潟国際異業種協同組合", type: "登録支援機関", address: "新潟県新潟市中央区西堀通三番町７９０番地", tel: "0252236022", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市秋葉区古田２丁目１９５番地１", tel: "0250236911", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市殿町一丁目１番地１", tel: "0258372033", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県妙高市朝日町一丁目１番７号", tel: "0255707010", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県南魚沼市塩沢１７６番地", tel: "0257881421", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市大島本町四丁目１０３番地２０", tel: "0258273310", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市東区大形本町六丁目８番５号", tel: "0252724220", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県北蒲原郡聖籠町網代浜１０５２番地１", tel: "0254207834", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市東区幸栄２丁目７番７号", tel: "0252881939", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市曙三丁目５番地８", tel: "0258368336", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県上越市昭和町二丁目１８番２０号", tel: "0255233899", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市東区新松崎３丁目２１番１０号", tel: "08061551368", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市西区山田３４８７番地", tel: "0253791181", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市江南区船戸山三丁目５－２１", tel: "08048057531", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県三条市東裏館二丁目１番３３号", tel: "0256346341", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市中央区花園二丁目２番１２号", tel: "0252458188", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市東区卸新町１丁目９２４番地８", tel: "0252553980", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県三条市北新保二丁目４番３２号", tel: "0256330551", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市来迎寺３７８４番地", tel: "09053082866", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市東区向陽２丁目８番地１４", tel: "09028426546", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県見附市本町一丁目４番４１号", tel: "0258621365", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県阿賀野市保田６１６２番地１", tel: "0250478333", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新発田市大手町三丁目４番１０号", tel: "0254372403", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市西区新通２１９２番地１", tel: "0252641058", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市南区茨曽根６４０１番地１", tel: "0253784680", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県燕市吉田堤町３番１号", tel: "0256779190", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県上越市北城町三丁目９番２０号", tel: "08055375518", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市中央区附船町一丁目４２７３番地１", tel: "0253781013", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市中央区西大畑町６２０番地４３ハイツ日本海５０５", tel: "08095127126", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県中魚沼郡津南町大字下船渡丁２６８２番地３", tel: "0257653700", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市鉄工町二丁目５番７号", tel: "0258299741", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市西区山田２５８７番地７", tel: "05036976897", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市美沢一丁目３６番地２", tel: "07026714588", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市旭岡一丁目１番地", tel: "0258868671", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市北区新崎一丁目１３番２０号", tel: "0252586831", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市摂田屋町２６６０-１　岡南ハイツ２０３", tel: "09099645088", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市西区寺尾前通二丁目３番地６", tel: "0252661136", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市東区山木戸三丁目７番９号", tel: "0252789123", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市槇下町１９１６番地３", tel: "08032496081", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県五泉市郷屋川２丁目１６４－１７", tel: "0250478308", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県上越市大字大日３４番地５", tel: "0255230700", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市西区坂井砂山四丁目１７番１９号", tel: "0253780868", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市中央区下大川前通四ノ町２１８６番地", tel: "0252285000", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市中央区西堀前通８番町１５１３番地WestHill’sM＆M６－３号室", tel: "0250245029", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市中央区愛宕三丁目９番１８号", tel: "0252881337", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県五泉市吉沢一丁目１番３－１号", tel: "0250475360", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県中魚沼郡津南町大字下船渡戊４２０番地６", tel: "0257555407", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市東区秋葉通三丁目４０番地２秋葉ビル３０２号室", tel: "0252787707", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県阿賀野市北本町１０番１４号", tel: "09014309041", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市中央区東大通一丁目３番１号INPEX新潟ビルディング６階", tel: "0252437700", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県長岡市寺泊野積２４０番地２野積の里マンションＣ２０８号", tel: "0258865299", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県南魚沼郡湯沢町土樽１７８番地１スカイリゾート湯沢１３０７", tel: "0257881798", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新発田市佐々木５９番地", tel: "0254281535", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県糸魚川市南寺島二丁目１２番１３号", tel: "0255501178", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市江南区沢海三丁目４番２６号", tel: "0253854583", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市中央区鳥屋野南三丁目１４番２６号", tel: "0252505556", visa: ["tokutei1"], prefId: "niigata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "新潟県新潟市西区坂井砂山三丁目８番２号", tel: "0252689000", visa: ["tokutei1"], prefId: "niigata", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();