// okinawa (111件)
(function(){
  const data = [
    { name: "株式会社ＪＯＢ　ＢＡＮＫ", type: "登録支援機関", address: "沖縄県那覇市銘苅２ー４ー４６", tel: "0989884470", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "仲宗根　隼人（沖縄在留資格サポートセンター）", type: "登録支援機関", address: "沖縄県那覇市楚辺１－５－１６竹越商会ビル３階", tel: "0989962475", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "渡慶次　佳朗　(グスクード社会保険労務士事務所)", type: "登録支援機関", address: "沖縄県那覇市天久７６２－１４　クリアスビル３階", tel: "0988623018", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ジャイス", type: "登録支援機関", address: "沖縄県那覇市西２丁目１２番１４号３０３", tel: "0989884686", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社国際言語文化センター", type: "登録支援機関", address: "沖縄県那覇市田原一丁目４番地１サンヒルズ田原２階", tel: "0988593881", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社新学", type: "登録支援機関", address: "沖縄県うるま市みどり町５丁目３番２５号", tel: "0989724888", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-2" },
    { name: "行政書士法人ときわ", type: "登録支援機関", address: "沖縄県島尻郡与那原町字与那原８７７番", tel: "0989889541", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-3" },
    { name: "株式会社ジャンボツアーズ", type: "登録支援機関", address: "沖縄県那覇市久茂地二丁目１５番１０号", tel: "0989175595", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社沖縄リレーションシップ", type: "登録支援機関", address: "沖縄県那覇市おもろまち二丁目５番３７号", tel: "0988607196", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "有限会社ＡＤＧ　Ｐａｒｔｎｅｒｓ", type: "登録支援機関", address: "沖縄県名護市我部祖河１７４番地１", tel: "0980435388", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-4" },
    { name: "株式会社五風商事", type: "登録支援機関", address: "沖縄県那覇市真地３２９番地１", tel: "09025104881", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "保田　隆生（Ｏｉｓｕｉ行政書士）", type: "登録支援機関", address: "沖縄県那覇市田原３丁目１番１０（有）やま店舗開発ビル４０３", tel: "0988596710", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ＪＳＬインターナショナル", type: "登録支援機関", address: "沖縄県浦添市仲西一丁目１番１号", tel: "0988751456", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "泰斗株式会社", type: "登録支援機関", address: "沖縄県豊見城市字真玉橋１８０番地１４", tel: "0988406563", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-6" },
    { name: "Ｓｃｈｏｏｌｈｏｕｓｅ　ｂｙ　Ｒｙｕｋｙｕ　Ｓｃｈｏｌａｒｓ　Ｉｎｃｏｒｐｏｒａｔｅｄ合同会社", type: "登録支援機関", address: "沖縄県沖縄市知花一丁目２番１号１８２８ＨＵＢ", tel: "0989533964", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-7" },
    { name: "沖縄県農業協同組合中央会", type: "登録支援機関", address: "沖縄県那覇市壺川二丁目９番地１", tel: "0988315104", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市与儀一丁目１４番３号１階", tel: "0988517705", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市寄宮一丁目８番５０号", tel: "0989965023", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宜野湾市大謝名二丁目１番７号", tel: "08075841824", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県浦添市勢理客四丁目２０番１号", tel: "0988754510", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市西一丁目９番１８号", tel: "0988632725", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市壺川一丁目４番地１５", tel: "0988543172", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市西二丁目１２番１４号", tel: "0988653377", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県浦添市西原一丁目３番２号棚原ビル２０１", tel: "0989639206", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県名護市字宮里９２５番地３", tel: "0980439977", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市西崎六丁目１６番１号嘉数ビル３０１号室", tel: "0988403002", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県うるま市みどり町四丁目１番８号", tel: "0989891779", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市銘苅１丁目２番１７号クレセントビル４階Ａ－４", tel: "09030450714", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市首里石嶺町２丁目７０番地２９", tel: "0988865585", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県豊見城市豊崎１番地１１６０　ディアフラッツ豊崎４０５", tel: "0988568490", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県島尻郡八重瀬町字具志頭１８９９番地", tel: "09068652176", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県浦添市伊祖３丁目４番１２号伊々寿スポット２０２号室", tel: "0989437981", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県うるま市字赤野８４７番地３", tel: "0989231790", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県浦添市西原２丁目４番１号Ｐ’ｓＳＱＵＡＲＥ５階", tel: "0988713804", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県豊見城市字豊崎１番地５５９", tel: "0988567751", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県沖縄市字登川３２３１番地１", tel: "0989891671", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市上之屋１-１０-２", tel: "0988945313", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市真地３２９番地１", tel: "0989877111", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市西崎六丁目１５－９ネクストビル西崎２０２号室", tel: "0989871981", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市字宇江城５５６番地", tel: "09049827104", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県中頭郡中城村南上原９５３-２南上原ハイツＦ", tel: "07023093921", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市上之屋一丁目１８番１５号", tel: "0989434281", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市首里石嶺町２－１７６", tel: "05036394954", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市字国吉５４番地の２", tel: "08039555337", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県豊見城市字高安７９８番地４", tel: "08042751203", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市西崎２丁目２７-１１　３０３", tel: "0989965020", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市久茂地二丁目２２－１２久茂地UFビル８F", tel: "0988949933", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市松尾二丁目８番２８号３F", tel: "0988608599", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市天久一丁目８番１号コーポ杜２０２", tel: "0989430400", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市樋川一丁目１番７７号", tel: "0988336715", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市字糸満６０６番地の２", tel: "0988518266", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県沖縄市胡屋二丁目１２番１２号", tel: "090978７0177", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市田原二丁目２番５号", tel: "09884011111", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市松尾二丁目２２番１７号", tel: "0988519646", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県浦添市城間二丁目１７番１５　ＳＳマンション４０５", tel: "0989431608", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県沖縄市中央一丁目７番８号 Ｓｔａｒｔｕｐ　Ｌａｂ　Ｌａｇｏｏｎ　２F", tel: "05017456052", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市西川町５－２ １F", tel: "0989965305", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県浦添市字経塚７７４番地２モンゴメリーハウス３０３", tel: "09037943400", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市繫多川五丁目１番７号 永吉荘１０１号室", tel: "0988513517", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県島尻郡八重瀬町字後原６５８番地の２", tel: "0988407671", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市字天久９０５番地", tel: "0988655533", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県中頭郡西原町字我謝７７６番地の５", tel: "0989438677", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市首里山川町二丁目５６番１４", tel: "0989174115", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県豊見城市宜保四丁目３番地１", tel: "09034161980", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宜野湾市志真志２丁目１番７－８０１号室　スカイヒルズ志真志", tel: "09097818685", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市西崎町四丁目１７番１０", tel: "0989953588", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市字西二丁目１６番３号屋島組ビル２F", tel: "09068585538", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市銘苅３－２３－１６あーとびーる４０１", tel: "0989175898", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宜野湾市真志喜１－１１－１２コモンズビル４０２号", tel: "0989438258", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宜野湾市大山三丁目２４番１号", tel: "09068649975", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県沖縄市与儀二丁目４番１３号　大濱ビル３－B", tel: "0989828813", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県うるま市石川東山本町二丁目３番４７号", tel: "0989893925", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県島尻郡南大東村字在所１８２番地", tel: "0980222115", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市西二丁目６番１６号コーポ流翔１階", tel: "0988639871", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宮古島市平良西里２７番地", tel: "08042298844", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宜野湾市真志喜一丁目７番２号３Ｂ", tel: "0989014690", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市字糸満１４９５番地の２", tel: "0989538764", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県国頭郡恩納村真栄田９３５番地４", tel: "09097843113", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市安謝２丁目２０番３０号　フェリーチェ新都心３０１", tel: "08091042847", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市安謝二丁目１７番１９号", tel: "0989965995", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市字天久１０６０番地１　タカダ上之屋マンションＢ－２０５", tel: "07090331314", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宜野湾市大謝名一丁目２番２２号１Ｆ", tel: "0989634196", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市曙二丁目２６番６号タカダ曙マンション２０３", tel: "09019441950", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県中頭郡北中城村字屋宜原７９３番地屋宜原テラスY-７", tel: "09097810920", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県名護市字屋部８６２番地１６", tel: "05055265822", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市泉崎一丁目２０番１号", tel: "0989435092", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県国頭郡恩納村字名嘉真２３８６番地", tel: "0989677233", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県うるま市みどり町一丁目１４番４号 パルティールみどり町１階", tel: "0989797169", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市久茂地一丁目１番１号パレットくもじ９階", tel: "0989115295", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県島尻郡八重瀬町字具志頭１０９０番地１", tel: "0989980050", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県沖縄市中央四丁目８番２号", tel: "0988803189", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市松尾二丁目１５番３３号", tel: "0988602323", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県豊見城市字真玉橋１７５番地１", tel: "0988568889", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県浦添市西原二丁目１９番５号", tel: "0988001886", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県うるま市字江洲６０４番地１５", tel: "0989826205", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市牧志２ー１７－２７－４０１", tel: "0989016388", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宜野湾市我如古二丁目３６番１２号", tel: "0988944904", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県宜野湾市大山１丁目５番１２－８０２　トーマス大山", tel: "08064837533", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県豊見城市字瀬長１７４番地５", tel: "0989965181", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市壺屋二丁目１番３０号", tel: "09068644764", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市牧志１－１－１４安木屋ビル４階", tel: "0988693575", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県沖縄市山里１丁目４番１５号", tel: "0989230260", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市久米１丁目２３番１３号４０３号室", tel: "0988949899", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市曙２丁目２番９ー２０１号室", tel: "08064838299", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市首里石嶺町３ー２６７ー５０", tel: "09089114972", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県島尻郡与那原町字上与那原４９７番地３", tel: "0989465661", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県糸満市賀数３７番地", tel: "07092342372", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市前島二丁目１９番１２号桃原アパート１０２", tel: "09037960778", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県浦添市字経塚７７４番地２－３０３", tel: "0988943477", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県那覇市安里３８１－１", tel: "08017237973", visa: ["tokutei1"], prefId: "okinawa", districtId: "okinawa-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "沖縄県南城市大里字大城１３９２番地", tel: "0989462051", visa: ["tokutei1"], prefId: "okinawa", districtId: null },
  ];
  if (window.VISA_DATA && VISA_DATA.agencies) {
    VISA_DATA.agencies.push(...data);
  } else {
    window._pendingAgencies = window._pendingAgencies || [];
    window._pendingAgencies.push(...data);
  }
})();