// tochigi (145件)
(function(){
  const data = [
    { name: "天谷　雅隆（BELQIS国際管理（アマタニ国際行政書士事務所内））", type: "登録支援機関", address: "栃木県宇都宮市東宿郷２丁目５ー３ MYビル４階", tel: "0286786141", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "福田　智一（行政書士福田国際法務事務所）", type: "登録支援機関", address: "栃木県宇都宮市材木町４番１号矢口ビル１F", tel: "0286105931", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社オーエヌシー", type: "登録支援機関", address: "栃木県小山市東城南三丁目６番地５", tel: "0285284992", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ＥＶＥＲＥＳＴ", type: "登録支援機関", address: "栃木県大田原市加治屋８８番地２１", tel: "0287551038", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-4" },
    { name: "社会福祉法人松徳会", type: "登録支援機関", address: "栃木県栃木市皆川城内町５２０番地", tel: "0282208770", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "一般社団法人にほん語でかいご共育会", type: "登録支援機関", address: "栃木県宇都宮市不動前四丁目２番３９号", tel: "0283483770", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "医療法人社団松徳会", type: "登録支援機関", address: "栃木県芳賀郡茂木町大字烏生田字下郷３４６番地１", tel: "0285641167", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-7" },
    { name: "アイ・ネットワーク協同組合", type: "登録支援機関", address: "栃木県宇都宮市駒生２－１０－２０", tel: "0286121105", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "アイデアル株式会社", type: "登録支援機関", address: "栃木県那須塩原市北赤田３１６－１０１０", tel: "0287487951", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-8" },
    { name: "シーデーピージャパン株式会社", type: "登録支援機関", address: "栃木県宇都宮市峰二丁目２番１号", tel: "0286516123", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ＳＭＳ", type: "登録支援機関", address: "栃木県栃木市富士見町３－５ファッションコミュニティオリーブビル２F", tel: "0282257401", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社行廣国際アカデミー", type: "登録支援機関", address: "栃木県栃木市大宮町２４９６番地５", tel: "0282218760", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "とちぎビジネスネットワーク協同組合", type: "登録支援機関", address: "栃木県佐野市小見町１０８番地２１", tel: "0283621238", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-9" },
    { name: "服部　一人（服部行政書士事務所）", type: "登録支援機関", address: "栃木県足利市通６丁目３１５５番地", tel: "0284221656", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社アーチ", type: "登録支援機関", address: "栃木県栃木市片柳町五丁目６番５号", tel: "0282226030", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "グローバルポテンシャル株式会社", type: "登録支援機関", address: "栃木県小山市大字千駄塚５７６番地９", tel: "0285458175", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "ソートー関東協同組合", type: "登録支援機関", address: "栃木県小山市大字犬塚３－８－１０", tel: "0285226011", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社篠崎", type: "登録支援機関", address: "栃木県小山市城東７丁目２１番８号", tel: "0285230904", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "ジョブサポート協同組合", type: "登録支援機関", address: "栃木県小山市城東四丁目１番３５号", tel: "0285307780", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "果菜協同組合", type: "登録支援機関", address: "栃木県塩谷郡高根沢町大字桑窪１７２番地１", tel: "0286763213", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-10" },
    { name: "株式会社海新", type: "登録支援機関", address: "栃木県小山市犬塚一丁目３番地５", tel: "0285200770", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社エマール", type: "登録支援機関", address: "栃木県小山市犬塚一丁目３番５", tel: "0285303555", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ユーユーワールド", type: "登録支援機関", address: "栃木県宇都宮市平出工業団地３９番地５", tel: "0286643007", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社アイ電子工業", type: "登録支援機関", address: "栃木県大田原市美原三丁目３３２３番地１２", tel: "0287230057", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-4" },
    { name: "オリオンコンピュータ株式会社", type: "登録支援機関", address: "栃木県宇都宮市鶴田町２５６１番地２", tel: "0286144770", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社サンスタッフ", type: "登録支援機関", address: "栃木県宇都宮市宿郷一丁目１５番６号", tel: "0286899231", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "鹿沼機械金属工業協同組合", type: "登録支援機関", address: "栃木県鹿沼市武子１０８８番８", tel: "0289624973", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-6" },
    { name: "行政書士法人あおば", type: "登録支援機関", address: "栃木県小山市城東一丁目６番地３２号", tel: "0285251122", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社アイエーシー", type: "登録支援機関", address: "栃木県宇都宮市野沢４９４番地３４", tel: "0286655670", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "とちぎ人材開発協同組合", type: "登録支援機関", address: "栃木県鹿沼市貝島町５０３３番地２", tel: "0289633385", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-6" },
    { name: "東日本人材協同組合", type: "登録支援機関", address: "栃木県足利市伊勢町一丁目７－１２", tel: "0284227300", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社惣", type: "登録支援機関", address: "栃木県宇都宮市下川俣町２６４番地３", tel: "05054915274", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ネクスト", type: "登録支援機関", address: "栃木県宇都宮市峰４丁目３番２２号", tel: "0286126407", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "有限会社光真製作所", type: "登録支援機関", address: "栃木県小山市大字粟宮８３６番地３", tel: "0285455431", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社モンキークルージャパン", type: "登録支援機関", address: "栃木県宇都宮市昭和一丁目７番３号", tel: "05053288465", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市薗部町１－１３－３３　 ステートピア　A２０１", tel: "08051158247", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市城東一丁目６番３２号", tel: "0285246110", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市羽牛田町１１５番地", tel: "0286789247", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県下都賀郡野木町大字友沼５８５９番地１２１", tel: "0363834578", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県大田原市北金丸字上ノ原２６００番１", tel: "0287243000", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市平出町４０６６番地４６", tel: "0286624111", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市大平町下皆川２１１７番地１", tel: "0282257992", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市石井町２９８６番地３９", tel: "0289024239", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市御幸本町４６３９番地３１", tel: "0286806783", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市神明町二丁目４０９番地２", tel: "0285387102", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市堀込町２００１番地", tel: "05088804599", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市川原田町１６７５番地６", tel: "0282236387", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県芳賀郡茂木町大字烏生田３４６番地", tel: "0285641317", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市雨ケ谷新田８３ー４７", tel: "09081192385", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市平柳町１丁目１１番１１号", tel: "0282255218", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市境町２３番８号", tel: "0282205666", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県真岡市下大田和１２５番地１", tel: "0285815556", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市岩曽町１３４０番地２", tel: "09080284380", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市岩曽町１１７７－１６", tel: "0286898668", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市伊勢町４丁目３番地３　阿部ビル２階B号室", tel: "0284228809", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市鹿島町５９１番地第１増栄荘１０６号棟", tel: "0284649812", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市南大通り一丁目３番２３号", tel: "0286784218", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市大平町西水代３６０８番地１８", tel: "0282286221", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市城北五丁目３番５号", tel: "0285386355", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県大田原市若松町１６５０番地４５７", tel: "0287241183", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市片柳町一丁目３０番２３号", tel: "0282221226", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市上戸祭町９４番地２１", tel: "0286006630", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市城東四丁目１９番３１号", tel: "0285307769", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市平出工業団地９番地２５", tel: "0286168570", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市羽刈町９５６番地１", tel: "0284724781", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市境町２２番２６号", tel: "0282257244", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県矢板市木幡１６３３番地２", tel: "0287474510", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市海道町１１０番地", tel: "0286831717", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県日光市今市６９番地１４", tel: "0288253172", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市大字神鳥谷８５３番地１８", tel: "09090046919", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市都賀町平川１０８番地３", tel: "08048961975", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市喜沢１２７１番地１", tel: "0285224354", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市東宿郷五丁目２番５号", tel: "0286337502", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市西一の沢町１番４号", tel: "0286125354", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市相生町３８９番地５", tel: "0284444511", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県芳賀郡市貝町大字杉山９３９", tel: "08072556293", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市西川田町１０７９番地１８", tel: "0286485877", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県那須塩原市前弥六３７１番地１", tel: "0287673660", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市宿郷二丁目７番１６号メゾン千秀２０３号", tel: "0286128864", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県芳賀郡益子町大字塙３４６番地１", tel: "0285816241", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市大字土塔２４６番地５２", tel: "0285285296", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市東城南四丁目３１番１号", tel: "050", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市中今泉３－２０－１１", tel: "0283335744", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県大田原市北野上２１１６番地", tel: "0287238137", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市中央本町４番２３号ローカルボーイズ新館２階", tel: "028", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市小俣町１９２８番地２", tel: "0284648779", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県下都賀郡壬生町緑町二丁目６番２号オイカワビル２階", tel: "0282854777", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市中戸祭町８４７番地８", tel: "0286805199", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県下都賀郡壬生町大師町１６番１１号", tel: "09070008383", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県日光市根室６９７番地１", tel: "0288327140", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県佐野市富岡町５９２番地９", tel: "0283258023", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市中島町７６５番地１", tel: "0286121141", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市駅南町四丁目２番１号－１０３", tel: "0285279704", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県下都賀郡壬生町大字壬生甲３３１２番地４", tel: "0282286288", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市西川田一丁目３番２号", tel: "0286842911", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市針ケ谷１－２７－４", tel: "09055053692", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県河内郡上三川町上三川４９４５－１", tel: "0285387160", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市雀の宮二丁目１２番４号", tel: "05053272628", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県佐野市伊賀町７０８番地３", tel: "0283867230", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県那須塩原市佐野１４番地３０", tel: "0287746815", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市大字下河原田９５４栃木県南地方卸売市場内２Ｆ", tel: "0285388906", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市滝谷町１４番７号", tel: "0286473322", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市大字間々田１６５５番地２", tel: "08020504040", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市鵤木町１４番地１鵤木町テナント１０１号室", tel: "0284223024", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市西一丁目４番２７号ＴＡＫＡＳＨＯビル３階Ｂ", tel: "0286105931", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市西城南七丁目４番地４", tel: "0285389755", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県下野市下石橋４１６番地５", tel: "0285512788", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市利保町三丁目１５番地４４フラットステージ１０３号", tel: "0284649592", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市神明町二丁目４０９番地２", tel: "0285386731", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市三峯２丁目４番２号", tel: "07083423041", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市大宮町２４９６番地５", tel: "0282218990", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市東峰町３０２９番地１３０", tel: "08074584331", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市小幡二丁目２番１１号", tel: "0286783898", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県那須塩原市東原３番地７１５", tel: "0287634648", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市下河原一丁目３番１０号", tel: "09035375700", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市南町１番３号第３朝日マンション１０１号室", tel: "0286541754", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市島田町２４６番地５", tel: "08012660137", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県真岡市下籠谷２６２番地１", tel: "09046032024", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市松田町１５６３番地１", tel: "09088922835", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市大字犬塚字箒島５０番地１４２", tel: "0285326553", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市今泉新町６１番地６にしき今泉新町ハイツＩＩＩ３０７号室", tel: "07021887389", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市江曽島町１３０６－１９マンションヴィガラス１０５号室", tel: "0286667992", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市兵庫塚三丁目４６番８号", tel: "0286783705", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市迫間町４４１番地５", tel: "0284822033", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市板倉町１７０６番地５", tel: "08021306092", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市城北一丁目１番地１１", tel: "0285389270", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県佐野市西浦町５８７番地", tel: "0283239313", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県鹿沼市板荷４６９番地４", tel: "08050363217", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-6" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市神鳥谷五丁目５番５号", tel: "0285378866", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市陽東３丁目１０番２５号コーポブリッジ１０１号室", tel: "0286805080", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県那須郡那須町高久丙5464番地", tel: "0287771774", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県河内郡上三川町しらさぎ二丁目２６番地２１", tel: "0285356397", visa: ["tokutei1"], prefId: "tochigi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市粟宮一丁目１０番２号", tel: "09074199471", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市山下町１０４６番地１シャトー２２、２０１号室", tel: "09029947418", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県足利市駒場町５６８番地１", tel: "0284650506", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市今泉町７８番地１", tel: "0286215800", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市大字高椅４００番地１", tel: "0285386443", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市宿郷二丁目１０番１６号外池宿郷ビル２階", tel: "07021818345", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市藤岡町藤岡４３０７番地１", tel: "09072703309", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県小山市天神町一丁目９番９号", tel: "0285248105", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市江野町９番１号ＮＩＮＥＳＴＡＲＳビル１Ｆ・２Ｆ・３Ｆ", tel: "0286346750", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市今泉二丁目７番８号", tel: "09034084790", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県那須塩原市佐野１４番地３０", tel: "0287746813", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県宇都宮市馬場通り三丁目４番７号宇都宮ＰＥＡＫＳ５０３", tel: "0286786851", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "栃木県栃木市平井町２５１番地８ブランドールコーポ１０６", tel: "0282255441", visa: ["tokutei1"], prefId: "tochigi", districtId: "tochigi-3" },
  ];
  if (window.VISA_DATA && VISA_DATA.agencies) {
    VISA_DATA.agencies.push(...data);
  } else {
    window._pendingAgencies = window._pendingAgencies || [];
    window._pendingAgencies.push(...data);
  }
})();