// 登録支援機関データ - tokushima (63件)
(function(){
  const data = [
    { name: "ファーストクラス株式会社", type: "登録支援機関", address: "徳島県吉野川市山川町翁喜台８２ー１", tel: "0120913041", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワークスタッフ", type: "登録支援機関", address: "徳島県徳島市西新町５丁目１７", tel: "0886262626", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "グリンアグリ協同組合", type: "登録支援機関", address: "徳島県徳島市城南町４丁目２番１８号", tel: "0886116888", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "徳島県藍協同組合", type: "登録支援機関", address: "徳島県徳島市新蔵町１丁目９５番地５階", tel: "0886783212", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社めいん", type: "登録支援機関", address: "徳島県吉野川市鴨島町鴨島１０１番地５", tel: "0883361100", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "合同会社ＮｅｗＢＥ", type: "登録支援機関", address: "徳島県徳島市中洲町三丁目２４番地中州ウェアハウス２階３号室", tel: "0886613942", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "阿波国際技術交流協同組合", type: "登録支援機関", address: "徳島県阿波市吉野町柿原字北二条１３７－３０", tel: "0886377737", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "職業訓練法人徳島食品工業職業能力開発協会", type: "登録支援機関", address: "徳島県海部郡海陽町大井字西谷６番地", tel: "0884743336", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "徳島ファーマーズ協同組合", type: "登録支援機関", address: "徳島県徳島市入田町月ノ宮３６２番地３４", tel: "0886442023", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "徳島技術交流協同組合", type: "登録支援機関", address: "徳島県吉野川市鴨島町牛島字西崎前１６３５番地２", tel: "0883223332", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "異業種パワー協同組合", type: "登録支援機関", address: "徳島県小松島市中郷町字西野１番２１　徳島サンハイツ１２５号", tel: "0885327257", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社フィフティ・フィフティ", type: "登録支援機関", address: "徳島県徳島市国府町府中６０４番地の７", tel: "0886422670", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "徳島経済振興協同組合", type: "登録支援機関", address: "徳島県鳴門市大津町矢倉字中開４５番地１", tel: "0886779223", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "藤原　雅和（行政書士秋桜法務事務所）", type: "登録支援機関", address: "徳島県板野郡上板町高瀬６３番地４", tel: "07053554410", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "協同組合徳島経済フォーラム", type: "登録支援機関", address: "徳島県鳴門市大津町矢倉字中開４５番地の５", tel: "0886850807", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "徳島光メディア協同組合", type: "登録支援機関", address: "徳島県鳴門市大津町矢倉字中開４５番地６", tel: "0886796560", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿波市市場町市場字町筋７０番１－１F", tel: "0883369380", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市出来島本町三丁目２２番地３", tel: "0886358442", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市南昭和町七丁目８番地の５０", tel: "0886245555", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市応神町吉成字轟５９－１３", tel: "0886356331", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市富田橋三丁目２７－１１", tel: "0886265302", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市南蔵本町２丁目７番地", tel: "0886312050", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県板野郡藍住町東中富字朏傍示２９－４", tel: "0886797185", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿波市吉野町柿原字小島２０４番地１", tel: "0886377820", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県板野郡藍住町笠木字西野５０番地の１", tel: "0886925757", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市国府町中３２７番地の５", tel: "0886426454", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市沖浜東三丁目１９番１", tel: "0886250708", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市伊月町５丁目６番地", tel: "0886787428", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県鳴門市大津町矢倉字五の越５５番地の３", tel: "0886784489", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県小松島市板野町字鸛ノ巣１２番地の１", tel: "0885390268", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿波市市場町香美字郷社本２５０－４エンゼルハイツ１０３", tel: "0883368222", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県吉野川市鴨島町鴨島１６１番地５", tel: "0883228801", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市庄町四丁目８０", tel: "0886333255", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県吉野川市鴨島町内原字桑ノ内４５－３", tel: "0883303468", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市住吉２丁目１－２　石本建設ビル２０６号", tel: "08088851437", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿波市阿波町北整理１番地１", tel: "0883356085", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県小松島市中田町字新開４８番地", tel: "0885387272", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県吉野川市鴨島町鴨島７２３－１　住友店舗１F", tel: "0883361780", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿波市阿波町中原２１番地１", tel: "0883355699", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県美馬市脇町字西赤谷２２３６番地", tel: "09039885965", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県吉野川市山川町奥川田８９番地", tel: "0883424420", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県吉野川市川島町学字近久２２０番地", tel: "08031668860", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県名西郡石井町高川原字南原７２－２１", tel: "0886747307", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県名西郡石井町浦庄字下浦９２９番地１７", tel: "0886751410", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県小松島市坂野町字鸛ノ巣１２番地１", tel: "0885387271", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県鳴門市撫養町黒崎字松島２９２番地", tel: "0886603622", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市新浜本町三丁目６番３５－１２", tel: "0886129216", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市八万町中津浦３２番地の１４", tel: "07076399885", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市富田橋８丁目６番地　ライオンズマンション富田橋　１００７", tel: "09017858838", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市一番町三丁目１６番地の３", tel: "09089499595", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市応神町古川字戎子野１１４－４", tel: "0886651120", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県名西郡神山町鬼籠野字小原１０２番地", tel: "0886761105", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿波市吉野町柿原字北二条１３７番地３０", tel: "0886963208", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市佐古四番町６番６号", tel: "0886310321", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿南市見能林町北野３４番地４", tel: "0884224450", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県三好市山城町信正１１５３番地５", tel: "0883862334", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿南市富岡町あ王谷５２番２", tel: "0884235539", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市東出来島町３５番地", tel: "0886247995", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿南市才見町石橋６７番地１", tel: "09075750336", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市国府町府中７２３－５", tel: "0886601743", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市住吉２丁目９－３３住吉マンション１０５", tel: "09061789406", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県徳島市新南福島２丁目１－２", tel: "09077287775", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "徳島県阿波市市場町大俣字貞久３０１番１", tel: "0883365760", visa: ["tokutei1"], prefId: "tokushima", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();