// 登録支援機関データ - toyama (88件)
(function(){
  const data = [
    { name: "株式会社林インターナショナル", type: "登録支援機関", address: "富山県富山市問屋町一丁目２番５２号", tel: "0764510088", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "北日本国際事業協同組合", type: "登録支援機関", address: "富山県富山市堀川小泉町８４２番地１", tel: "0764816727", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "富山国際人材交流センター協同組合", type: "登録支援機関", address: "富山県富山市太郎丸西町１丁目３－４根塚ビル３０１号", tel: "0764235370", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "大高建設株式会社", type: "登録支援機関", address: "富山県黒部市宇奈月温泉６３３－１", tel: "0765621106", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社コラビエット", type: "登録支援機関", address: "富山県高岡市二塚３６３番地", tel: "0766234015", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "アクトワーカーズ株式会社", type: "登録支援機関", address: "富山県高岡市姫野４３番地１", tel: "0766546912", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "栄日国際交流事業協同組合", type: "登録支援機関", address: "富山県富山市弥生町二丁目３番２", tel: "0764716943", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "マイアジアパートナーズ株式会社", type: "登録支援機関", address: "富山県富山市吉作４７２８番地", tel: "0764823677", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "一般社団法人ＴＦＪ国際支援協会", type: "登録支援機関", address: "富山県富山市下大久保１５３０番地１１", tel: "0764643806", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "北陸シンコウ協同組合", type: "登録支援機関", address: "富山県滑川市菰原１９８番地８", tel: "0764752232", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "川西　孝昭（川西国際行政書士事務所）", type: "登録支援機関", address: "富山県富山市綾田町一丁目８番２３号SUMIKA－０５号", tel: "0764715888", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "協同組合テクノ・トヤマ", type: "登録支援機関", address: "富山県高岡市荒屋敷９８番地の１", tel: "0766315508", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "ＢＥＳＴ　ＪＡＰＡＮ株式会社", type: "登録支援機関", address: "富山県魚津市文化町２番３号", tel: "0765325999", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "富瀋国際事業協同組合", type: "登録支援機関", address: "富山県富山市問屋町二丁目４番６号", tel: "0764521515", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "協同組合ＧＳＨ", type: "登録支援機関", address: "富山県富山市奥田双葉町１番４９号", tel: "0764415111", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "協同組合ＣＥＯ", type: "登録支援機関", address: "富山県砺波市春日町４番１号", tel: "0763348899", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "信心協同組合", type: "登録支援機関", address: "富山県富山市稲荷元町二丁目７番１０号サンシャイン８８－４０１号室", tel: "0764823915", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社龍成", type: "登録支援機関", address: "富山県富山市古沢５３０番地２", tel: "0764361110", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "ＡＴＥ国際協同組合", type: "登録支援機関", address: "富山県高岡市昭和町二丁目２番４３号", tel: "0766954445", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "富山アジア経済技術協同組合", type: "登録支援機関", address: "富山県砺波市宮丸２５３番地", tel: "0763341031", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "公益社団法人ＯＮＥ　ＡＳＩＡ", type: "登録支援機関", address: "富山県富山市布瀬町南二丁目６番地１", tel: "0764132275", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市西中野町一丁目８番１号", tel: "0764643092", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市綾田町一丁目８番２３－０５号", tel: "0764115115", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市上冨居一丁目７番２号", tel: "0764115808", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県黒部市荻生５２９７番地", tel: "0765540753", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市公文名５番地２", tel: "0764817227", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市田中町四丁目１４番７６号", tel: "0764136554", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県小矢部東福町１番６号", tel: "0766753282", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市西公文名町１２番２１号", tel: "0764943330", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市星井町一丁目２番１７号", tel: "0764616218", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市西田地方町一丁目３番８号", tel: "0764823455", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市岩瀬白山町９３番地６", tel: "08071265791", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市福岡町荒屋敷５１１番地の１２", tel: "0766646200", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市本宮２番地１０６", tel: "0764811132", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市開発３４６番地", tel: "0764715487", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市黒瀬北町二丁目１３番地１イムズビル４Ｆ", tel: "0764645205", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市山室２１０番地６", tel: "0764225770", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市上黒田２５７番地", tel: "0766757662", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県南砺市吉江中６６１番地アラックスビル福光ＩＩＩ１Ｆ－Ｂ", tel: "0763525552", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市草島１５番１４号", tel: "0764418225", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市西公文名町１２番２１号", tel: "0764943888", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市本郷町１０４番地", tel: "0764643241", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市五福４５４６番１", tel: "0764413710", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市大泉東町一丁目４番１号", tel: "0764824098", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県魚津市漁港定坊割", tel: "0765240068", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市山室字浦田割３５７番１６の２", tel: "0764617571", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市永楽町３５-３ アサイビル１F", tel: "0764008665", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市向新庄町二丁目１０番４７号", tel: "0764110855", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市星井町二丁目３番１号", tel: "0764615345", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市水橋市田袋２６４番地１", tel: "0764785800", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市小原屋４２番地１", tel: "09042673481", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市北代５２９８番地", tel: "0764341881", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県小矢部市埴生１７番地３", tel: "09020396164", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市つばめ野一丁目５２番地", tel: "0764355755", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県氷見市伊勢大町１丁目１０－２７", tel: "05088827940", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市清水町２丁目７－１", tel: "0766304200", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市室町通り一丁目２番１０号", tel: "0764211514", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市婦中町長沢２３４９番地７", tel: "0762359111", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県魚津市真成寺町４番５号", tel: "0765220201", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県小矢部市後谷３２３番地７", tel: "09020396164", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市上黒田２５７番地", tel: "0766227828", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市綾田町一丁目３４番５号", tel: "0764119731", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市日俣１３８番地６", tel: "0764132801", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市黒瀬４３７番地の１", tel: "0764948041", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市呉羽町３９１８番地１７１", tel: "0764341412", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市オフィスパーク１３番", tel: "0766638820", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市野村１３７３番地４　いわせの創ビル２Ｆ", tel: "0766284145", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市婦中町田島５４６番地３", tel: "0764665656", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県氷見市上泉１６１番地１", tel: "0766914551", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市上飯野新町３丁目３９１", tel: "0764511290", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市京田４３２番地", tel: "0766255055", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市西中野町一丁目８番１号", tel: "0764643091", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市星井町二丁目３番１号", tel: "0764615345", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市城川原一丁目１０番３１号", tel: "0764386800", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市牛島新町３番７号レジデンス牛島８０２号", tel: "0764119103", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市南央町３７番１１", tel: "0764295995", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市上冨居一丁目７番２号", tel: "0764115808", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市婦中町西本郷４４８番３", tel: "0764825995", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市鷲北新４７７番地", tel: "0766287700", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市針原中町８８５番地５", tel: "0764718705", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県射水市庄西町二丁目１４番１４号", tel: "0766751261", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県高岡市赤祖父６７９番地", tel: "0766229333", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市高田５２７番地情報ビル５Ｆ", tel: "0764715458", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市小泉町１８１番地グラヨール小泉町４階Ｄ号室", tel: "0764917260", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県魚津市友道７８９番地", tel: "0765247671", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市赤田８９５番地", tel: "0764258774", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市掛尾町１７－１", tel: "09089550174", visa: ["tokutei1"], prefId: "toyama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "富山県富山市町村１番地", tel: "0764250900", visa: ["tokutei1"], prefId: "toyama", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();