// wakayama (41件)
(function(){
  const data = [
    { name: "株式会社キャリーアップ", type: "登録支援機関", address: "和歌山県和歌山市園部１０２７－５", tel: "0734627265", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "人と人協同組合", type: "登録支援機関", address: "和歌山県御坊市塩屋町南塩屋３３９番地１", tel: "0738204717", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-2" },
    { name: "中原　満久（行政書士中原満久事務所）", type: "登録支援機関", address: "和歌山県和歌山市東高松２丁目５番２８号", tel: "0734885690", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "一般社団法人希望", type: "登録支援機関", address: "和歌山県日高郡美浜町大字和田２１０１番地の１（２０１）", tel: "0738525272", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-3" },
    { name: "株式会社紀乃屋", type: "登録支援機関", address: "和歌山県日高郡みなべ町西岩代１６０６番地７", tel: "0739342320", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ハウディ", type: "登録支援機関", address: "和歌山県和歌山市田中町五丁目４番の１", tel: "0736797312", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "みらい事業協同組合", type: "登録支援機関", address: "和歌山県岩出市西国分６８８番地の４", tel: "0736635559", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-4" },
    { name: "株式会社ＫＥＧキャリア・アカデミー", type: "登録支援機関", address: "和歌山県和歌山市友田町二丁目１４５番地　ＫＥＧ教育センタービル", tel: "0734211112", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市黒田９７番地の６", tel: "0734761717", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市六十谷２３６番地５", tel: "0734645177", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県田辺市下万呂５８９番地の１", tel: "0739247422", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市黒田９７番地の６", tel: "0734763939", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市六十谷３７４番地３", tel: "0734610797", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県西牟婁郡上富田町朝来２３５９番地の１", tel: "0739473700", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県東牟婁郡那智勝浦町大字宇久井１０５８番地５", tel: "0735542001", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県西牟婁郡上富田町朝来２５７６番地の１", tel: "0739337437", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県橋本市神野々１２０１番地の１", tel: "0736393001", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県紀の川市北長田３７５番地１", tel: "0736743307", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県日高郡みなべ町西本庄１０４１番地１", tel: "0739748024", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県海南市下津町丸田１０５番地", tel: "0734924300", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市大垣内５９２番地の３", tel: "0734652055", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市島橋東ノ丁８番１５号", tel: "0734793356", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県御坊市藤田町吉田１０２４番地４", tel: "0738242257", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県西牟婁郡すさみ町周参見２３８０番地", tel: "0739553599", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市松江東四丁目２番４５号", tel: "0734545293", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県田辺市下屋敷町１番地７８", tel: "0739264037", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市六十谷２３６番地の５", tel: "0734640238", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市本町一丁目２２番地Ｗａｊｉｍａ本町ビル５階", tel: "0734253331", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県西牟婁郡上富田町朝来字大沼２３５９番地の１", tel: "0739473700", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市松江北七丁目６番５号", tel: "0734554191", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市大垣内字堤ケ丘５９２番地１", tel: "0734975700", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市岩橋９４６番地の１２", tel: "0734751391", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市本町一丁目４３番地", tel: "0734943515", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県海南市下津町丸田１９５番地の１", tel: "0734922478", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県岩出市金屋２３０番５（４０８号）", tel: "0736794633", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市鳴神８０３－１", tel: "0734889461", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県日高郡みなべ町北道１５０番地の２", tel: "0739345150", visa: ["tokutei1"], prefId: "wakayama", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県和歌山市中之島２２８７番地", tel: "0734225538", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県御坊市熊野３６２番地", tel: "0738233886", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県岩出市西国分７９３番１", tel: "0736695255", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "和歌山県岩出市吉田９２－１０５", tel: "07076613329", visa: ["tokutei1"], prefId: "wakayama", districtId: "wakayama-4" },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();