// yamaguchi (81件)
(function(){
  const data = [
    { name: "協同組合アネスト", type: "登録支援機関", address: "山口県下関市清末五毛一丁目２番１号", tel: "0832495011", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ＮＴコンサルタント", type: "登録支援機関", address: "山口県防府市大字台道１１３５５－１２０", tel: "0835321240", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-2" },
    { name: "阿部　政行（あべ行政書士事務所）", type: "登録支援機関", address: "山口県山口市大内矢田南七丁目８番１５号", tel: "0839964500", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-4" },
    { name: "謙和観遠国際技術協同組合", type: "登録支援機関", address: "山口県山陽小野田市大字東高泊１５６１番地の１３", tel: "0836838529", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-5" },
    { name: "有限会社ＢＩＳ", type: "登録支援機関", address: "山口県下関市吉見里町一丁目１番８号", tel: "0832944949", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "下関・ミャンマー産業振興協同組合", type: "登録支援機関", address: "山口県下関市向洋町一丁目３番１６号", tel: "0832225171", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "サークルズ協同組合", type: "登録支援機関", address: "山口県萩市大字弥富下字田中４０３５番地１", tel: "0838740716", visa: ["tokutei1"], prefId: "yamaguchi", districtId: null },
    { name: "ユー・アイ・ケイ協同組合", type: "登録支援機関", address: "山口県宇部市大字善和字大日２０３番地１３９", tel: "0836625555", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社みとも", type: "登録支援機関", address: "山口県下関市彦島本村町七丁目１番１９号", tel: "0832274631", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "国際経営改善事業協同組合", type: "登録支援機関", address: "山口県下関市宮田町二丁目１番８号", tel: "0832328881", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "岩国EＧＧ事業協同組合", type: "登録支援機関", address: "山口県玖珂郡和木町和木４丁目９番２４号", tel: "0827286512", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-6" },
    { name: "ナカガワシステム株式会社", type: "登録支援機関", address: "山口県周南市三笹町６番１９号", tel: "0834628718", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "有限会社ワイ・エス・ケイ", type: "登録支援機関", address: "山口県下関市小月西の台９番１３号", tel: "0832824084", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "国際異業種協同組合", type: "登録支援機関", address: "山口県防府市大字台道５６０番地の１", tel: "0835321690", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-2" },
    { name: "株式会社ウメモリ", type: "登録支援機関", address: "山口県岩国市玖珂町６２２９－７", tel: "0827823530", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-8" },
    { name: "ＳＡＲＡＰＯＯＭ ＳＵＮＩＳＡ　（絆）", type: "登録支援機関", address: "山口県下関市小月茶屋三丁目９番１８号", tel: "08029384346", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "特定非営利活動法人ＴＯＭＯＳ", type: "登録支援機関", address: "山口県下松市北斗町５番１３号", tel: "09031722612", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-9" },
    { name: "サンワールド事業協同組合", type: "登録支援機関", address: "山口県宇部市中宇部１７３５－４０", tel: "0836439772", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "下関水産食品加工協同組合", type: "登録支援機関", address: "山口県下関市彦島西山町二丁目２番４２号", tel: "0832495117", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "山陽グループ事業協同組合", type: "登録支援機関", address: "山口県下関市彦島塩浜町一丁目１番１６号", tel: "0832506644", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社スタッフ・エージェンシー", type: "登録支援機関", address: "山口県防府市駅南町４番１号", tel: "0835280031", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-2" },
    { name: "株式会社ダイフク", type: "登録支援機関", address: "山口県下関市彦島西山町五丁目９番４８号", tel: "0832671729", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市大和町一丁目１６番１号漁港ビル本館南２８２号室", tel: "0832663623", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県防府市八王子一丁目２番３号", tel: "0835381128", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県光市島田二丁目２２番１１号", tel: "0833728777", visa: ["tokutei1"], prefId: "yamaguchi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市唐戸町３番８号　三共ビル３階", tel: "0832428001", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市東新川町１番３３号", tel: "0836334200", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市大字須々万本郷４８１番地の８", tel: "0834880172", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県萩市大字椿東３０００番地１０", tel: "0838220940", visa: ["tokutei1"], prefId: "yamaguchi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山口市大内矢田北一丁目１８ー２０", tel: "0839410135", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山陽小野田市大字有帆５７番地", tel: "0836396688", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市相生町１丁目３５番地", tel: "0834211155", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市草江2丁目4-41", tel: "0836354447", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市彦島本村町６丁目１６番１０号", tel: "0832506703", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市彦島塩浜町１丁目１番９号", tel: "0832667155", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市豊浦町大字吉永５２６番地の１", tel: "0837743366", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山口市下小鯖５７-１", tel: "083", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市大字櫛ケ浜２２７番地１", tel: "0834253773", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山口市佐山２７６６-１", tel: "0839896117", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山口市小郡下郷１５６０番地の５", tel: "0839025511", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市大字栗屋７５９番地の２９", tel: "0834250443", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山陽小野田市北竜王町５番１０号", tel: "0836527988", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市中央町２番３号", tel: "0834634161", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市秋根上町三丁目２番２９号", tel: "09046590445", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市大字安田１２４３番地２", tel: "0833917988", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県岩国市今津町四丁目１１－４(２F)", tel: "0827355955", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-8" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市豊田町大字荒木１００５１番地２", tel: "0837680051", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市川中豊町六丁目８番２４号", tel: "0832505444", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市大字東須恵２９２４番地１０", tel: "0836436684", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県防府市大字牟礼４５２０－２", tel: "0835266262", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市あすとぴあ一丁目１番２", tel: "0836397650", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市丸山町三丁目２番１号吉岡ビル", tel: "0832506519", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市寿町２－５－２７ １F", tel: "0836395335", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市細江新町１番１号下関海運ビル１５号室", tel: "0832272644", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下松市大字末武上５７１番地２", tel: "0833447102", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市相生町４番４－２０１号", tel: "0836436989", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市安岡駅前一丁目４番７号Ｋ’ｓビル２階", tel: "0832580312", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市大字中宇部１７３５番地４０", tel: "0836489086", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市常磐町二丁目１番２８号　常盤ビル２階", tel: "05058107875", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市清末鞍馬三丁目５番２４号", tel: "0832821777", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山陽小野田市大字有帆字中小目出１０６５９番地の１２", tel: "0836810291", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-5" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市大字有冨４番地の７", tel: "0832561919", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下松市望町一丁目１０番１号", tel: "0833432488", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下松市瑞穂町三丁目１２番１４号", tel: "0833443337", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-9" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市豊浦町大字吉永５８４番地の３", tel: "0837722007", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市大字徳山１０１２番地の１６８", tel: "0834272368", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市大字上宇部２８４２－１３－１０１号", tel: "0836395335", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市平和通一丁目１０番の２", tel: "08343111211", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山口市秋穂東７５７６番地", tel: "0839843363", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県防府市中西１２番４０号", tel: "09028696989", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-2" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市綾羅木本町４丁目１０番１号", tel: "0832424165", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県周南市大字徳山６７８１番地の１４", tel: "0948806298", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-7" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市豊浦町大字川棚字小井田場１２１３９番地２", tel: "0837743901", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市大字矢矯３３５番地２", tel: "0836672622", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山口市阿知須６２５－２", tel: "08019191443", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県宇部市大字上宇部２８４２－１３－１０１号", tel: "0836395335", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-3" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市長府四王司町３９１－１０", tel: "08033938818", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県山口市小郡令和一丁目１番１号 ＫＤＤＩ 維新ホール１階", tel: "08019361779", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-4" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市神田町２丁目２番６－３０１", tel: "0832239355", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下関市豊浦町大字吉永１２４６", tel: "09095082332", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-1" },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山口県下松市大字笠戸島１５３０番地３８", tel: "0833520123", visa: ["tokutei1"], prefId: "yamaguchi", districtId: "yamaguchi-9" },
  ];
  if (window.VISA_DATA && VISA_DATA.agencies) {
    VISA_DATA.agencies.push(...data);
  } else {
    window._pendingAgencies = window._pendingAgencies || [];
    window._pendingAgencies.push(...data);
  }
})();