// 登録支援機関データ - aomori (41件)
(function(){
  const data = [
    { name: "塚本　山和（外国人材紹介センター）", type: "登録支援機関", address: "青森県つがる市柏鷺坂清見７１番地１", tel: "0173356618", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "北造協同組合", type: "登録支援機関", address: "青森県八戸市江陽三丁目１番２５号", tel: "0178244171", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "あすなろ協同組合", type: "登録支援機関", address: "青森県青森市第二問屋町４丁目１１番１８号ソフトアカデミーあおもりビル４階Ｈ号室", tel: "0177578686", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "日本人材協同組合", type: "登録支援機関", address: "青森県弘前市大字東和徳町１番地１", tel: "0172368688", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "みちのく中小企業協同組合", type: "登録支援機関", address: "青森県八戸市大字糠塚字下屋敷７番地２", tel: "0178807568", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "国際人材支援協同組合", type: "登録支援機関", address: "青森県つがる市牛潟町村上１５－１３７", tel: "0173261068", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "令和人材協同組合", type: "登録支援機関", address: "青森県五所川原市大字唐笠柳字藤巻１４８番地２", tel: "0173345841", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "ほたて貝殻有効利用協同組合", type: "登録支援機関", address: "青森県上北郡野辺地町字鳥井平３４－６８", tel: "0175640183", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "あおば国際協同組合", type: "登録支援機関", address: "青森県八戸市根城五丁目１４番２４号", tel: "0178326672", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "北日本事業振興協同組合", type: "登録支援機関", address: "青森県弘前市大字松森町１３０番地１", tel: "0172265371", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社コネット社", type: "登録支援機関", address: "青森県青森市栄町一丁目４番８号", tel: "0177426825", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "掛端　亨（かけ行政書士事務所）", type: "登録支援機関", address: "青森県八戸市大字中居林字仕替場１２番地３", tel: "08060200088", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県むつ市十二林１１番１３号", tel: "0175231600", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県八戸市柏崎一丁目１０番３４号", tel: "0178320254", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県八戸市大字新井田字寺沢下４番地４", tel: "0178200842", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県八戸市根城八丁目６番１１号", tel: "0178242700", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県八戸市大字鍛冶町５４番地１", tel: "08028196127", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県十和田市西十四番町３４番４３号", tel: "09067886677", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県青森市本町五丁目１０番１号３Ｆ３０２号", tel: "0177324755", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県上北郡東北町字往来ノ下３０番地１", tel: "0175731081", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県上北郡六ヶ所村大字倉内字前谷地１９番地２５９", tel: "0175752651", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県弘前市大字神田二丁目６番地３", tel: "0172556565", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県八戸市新井田字水溜１２番地１", tel: "0178389187", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県三戸郡南部町大字大向字仙ノ木３１番地１", tel: "0179221215", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県青森市中央三丁目２０番２６号", tel: "0177181541", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県三戸郡階上町大字道仏字榊山１１番地９", tel: "0178892688", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県三戸郡三戸町大字同心町字古間木平７５番地４", tel: "0179230373", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県青森市大字油川字実法９８番地", tel: "0177720322", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県上北郡六戸町大字折茂字今熊２３４番地１", tel: "08055758785", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県三沢市大字三沢字下久保５９番地４４８号", tel: "08092599006", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県青森市大字筒井字八ツ橋１２１番地３", tel: "09028864269", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県八戸市長苗代四丁目１番１４号", tel: "0178326945", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県西津軽郡鰺ヶ沢町大字舞戸町字下富田３５番地１２", tel: "0173823977", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県弘前市大字神田四丁目６番地２５", tel: "0172558118", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県上北郡東北町字塔ノ沢山１番地３１１", tel: "0175655061", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県つがる市木造豊田千代鶴３７番地２４", tel: "0173426429", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県八戸市大字新荒町２８番地", tel: "0178516396", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県黒石市竹田町１０３番地", tel: "0172888443", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県上北郡六戸町大字犬落瀬字坪毛沢１４６番", tel: "0176701800", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県八戸市大字田面木字美濃助平２４番地７", tel: "09022796023", visa: ["tokutei1"], prefId: "aomori", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "青森県青森市大字新城字平岡９５９番地５", tel: "0177526555", visa: ["tokutei1"], prefId: "aomori", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();