// 登録支援機関データ - ishikawa (71件)
(function(){
  const data = [
    { name: "新道　慶治（新道社会保険労務士行政書士事務所）", type: "登録支援機関", address: "石川県野々市市横宮町１２番１６号", tel: "0762870850", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "鳥越　勇人（サポーティングオフィスとりこし）", type: "登録支援機関", address: "石川県金沢市小金町８－１６万石ビル３階", tel: "0762692520", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社梶興業", type: "登録支援機関", address: "石川県河北郡津幡町字太田ろ２２４番地２", tel: "0762892630", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "ＳＵＮＣＡＲＥ　ＨＯＬＤＩＮＧＳ株式会社", type: "登録支援機関", address: "石川県金沢市入江三丁目１６０番地１", tel: "0762876631", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "アーシング協同組合", type: "登録支援機関", address: "石川県金沢市神野町東１２２番地スポートピア緑３０２号室", tel: "0762401018", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "ナーシングケア協同組合", type: "登録支援機関", address: "石川県金沢市笠舞３丁目２番３０号", tel: "0762186772", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "アリス・スタッフ株式会社", type: "登録支援機関", address: "石川県金沢市円光寺本町８番５０号", tel: "0762803388", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "アミックス事業協同組合", type: "登録支援機関", address: "石川県能美市大成町チ２８４番地マルトビル１階３号室", tel: "0761466680", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "万通産業株式会社", type: "登録支援機関", address: "石川県金沢市横川二丁目２０８番地　サテライト９０－A", tel: "0762563866", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "北陸ロードサービス事業協同組合", type: "登録支援機関", address: "石川県金沢市駅西新町３丁目１３番２７号　金澤MJ BLD.", tel: "0762617123", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "特定非営利活動法人ＹＯＵーＩ", type: "登録支援機関", address: "石川県野々市市新庄１丁目９６番地３", tel: "0762059899", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社メビウス", type: "登録支援機関", address: "石川県金沢市示野中町１丁目１５番地", tel: "0762083923", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "アクト事業協同組合", type: "登録支援機関", address: "石川県金沢市山科町チ９８番地", tel: "0762816467", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "協同組合金沢経営管理センター", type: "登録支援機関", address: "石川県金沢市寺地１丁目３３番１９号アドバンスビル３F", tel: "0762432080", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "石川県プレス工業協同組合", type: "登録支援機関", address: "石川県金沢市鞍月二丁目３番地", tel: "0762672125", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "ＹＢＭ・ＪＡＰＡＮ株式会社", type: "登録支援機関", address: "石川県野々市市粟田一丁目１８番地５号", tel: "0762207891", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "ワールドブリッジビジネス協同組合", type: "登録支援機関", address: "石川県金沢市南塚町１８－１", tel: "0762048866", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "オレオウ・ベトナム事業協同組合", type: "登録支援機関", address: "石川県金沢市昭和町１６番１号ヴィサージュビル１５階", tel: "0762649201", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "有限会社エニィワン", type: "登録支援機関", address: "石川県金沢市山科町チ９８番地", tel: "0762206020", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "協同組合アスカ", type: "登録支援機関", address: "石川県金沢市北町乙１８番地オクト北町４０５号室", tel: "0762085540", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社国際人材支援センター", type: "登録支援機関", address: "石川県金沢市新神田一丁目１２番１号", tel: "08037436880", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県羽咋市柴垣町十二字２８３番地１０", tel: "0767271388", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県かほく市高松ム６８番地２", tel: "0762810655", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市北森本町ル１７番地２", tel: "0762876707", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県七尾市田鶴浜町る部９９番地の２", tel: "09051757680", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市北町丁３５番地林ビル３Ｆ", tel: "0762313922", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市松村１丁目５番地", tel: "0762541965", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市浅野本町ニ１４２番地１", tel: "0762279991", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県野々市市末松３丁目５７０番", tel: "0762059899", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市無量寺町ヲ５１番地", tel: "0762681410", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市四十万四丁目１２７番地２", tel: "0762987585", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市南森本町ホ３０番１号３E", tel: "0762578095", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市彦三町二丁目１５６番地２", tel: "0762995905", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市駅西新町三丁目１番１０号", tel: "0762604466", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市北安江四丁目１６番３８号", tel: "0762553277", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市入江三丁目１３２番地福村ビル３０３号室", tel: "0762256333", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市新神田３丁目３番１１号", tel: "08037498972", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市昌永町１５番６０号２２０７", tel: "0762875933", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県かほく市高松ケ１３番地２０", tel: "0762811106", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市増泉一丁目１９番３４号", tel: "0762206018", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市上安原二丁目２６４", tel: "0762402005", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県加賀市山中温泉栢野町ハ３６番地", tel: "09077450677", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市円光寺本町８番５０号", tel: "0762801001", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市畝田西一丁目１１２番地", tel: "0762148836", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市八日市三丁目６０４番地", tel: "0762406060", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県かほく市高松子１３１番地６", tel: "09080958436", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県七尾市小島町大開地１番地４９－２０１号", tel: "09032984004", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市芳斉一丁目１４番１５号", tel: "0762545453", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市示野中町一丁目１５番地", tel: "0762546775", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市八日市出町７７７番地", tel: "0762206068", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県白山市五歩市町４２４番地１", tel: "0762753535", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市高尾南一丁目１３６番１号", tel: "0762359880", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市三小牛町１０の６番地", tel: "08019547522", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市三口町火３３番地", tel: "09075997371", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県小松市丸内町大手６３番地", tel: "0761246660", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県七尾市神明町１番地", tel: "0767527177", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市駅西本町一丁目８―２２", tel: "07089646395", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市駅西本町一丁目１５番２６号", tel: "0762229239", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県小松市古河町５５番地", tel: "0761471312", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市尾山町９番１０号", tel: "0762333526", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県七尾市松百町８-１６-１１", tel: "0767520564", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県加賀市山代温泉北部二丁目７０番地", tel: "0761773848", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市駅西本町三丁目１４番２９号", tel: "0762591780", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県野々市市横宮町１４番３０号", tel: "0762943356", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市吉原町ワ２０３番地", tel: "0762136266", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市古府三丁目１２９番地", tel: "0762876858", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県小松市安宅町カ６番地", tel: "0761222515", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市笠舞２丁目３３番１５号", tel: "05031072756", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県加賀市山代温泉桔梗丘１丁目３７番地", tel: "0761770106", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市鱗町９７番地１アトラスビル２階", tel: "09020303748", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "石川県金沢市畝田東３丁目５１６番地", tel: "0762206570", visa: ["tokutei1"], prefId: "ishikawa", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();