// 登録支援機関データ - shiga (114件)
(function(){
  const data = [
    { name: "トラスト日本合同会社", type: "登録支援機関", address: "滋賀県彦根市平田町７４９番地５", tel: "0749246639", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "事業協同組合ＰＩＡネットワーク", type: "登録支援機関", address: "滋賀県近江八幡市堀上町１２２ー１", tel: "0748321010", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "滋賀産業技術育成支援協同組合", type: "登録支援機関", address: "滋賀県野洲市吉地１３２０－２楓ビル３階", tel: "0775981069", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "有限会社ヒューマンハート", type: "登録支援機関", address: "滋賀県東近江市八日市上之町８番２８号", tel: "0748232172", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社石川技研", type: "登録支援機関", address: "滋賀県彦根市地蔵町７１－３", tel: "0749248100", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "協同組合ビジネス21", type: "登録支援機関", address: "滋賀県彦根市戸賀町２５６番地の１北川ビル３階", tel: "0749212289", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社クローバー", type: "登録支援機関", address: "滋賀県長浜市列見町２９２番地", tel: "0749658239", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ビイサイドプランニング", type: "登録支援機関", address: "滋賀県草津市志那中町１０２－１", tel: "0775685020", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社びわこクリエイト", type: "登録支援機関", address: "滋賀県彦根市戸賀町２５６番地の１", tel: "0749272356", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "キャストリンクス株式会社", type: "登録支援機関", address: "滋賀県米原市坂口１５８番地", tel: "0749553909", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "協同組合滋賀ジェイ・シー・エル", type: "登録支援機関", address: "滋賀県蒲生郡日野町大字石原２番地２０１", tel: "0748538971", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ヤマト精工", type: "登録支援機関", address: "滋賀県彦根市高宮町２７３８", tel: "0749224549", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "協同組合インターナショナル・マテリアル・エンカレッジ", type: "登録支援機関", address: "滋賀県長浜市口分田町１００４番地", tel: "0749532595", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社リンクアップ", type: "登録支援機関", address: "滋賀県長浜市西上坂町９６３番地１", tel: "0749593181", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "協同組合中小企業経営技術研究会", type: "登録支援機関", address: "滋賀県長浜市八幡東町８３番地の３", tel: "0749641143", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社エスポワール", type: "登録支援機関", address: "滋賀県米原市中多良６３０番地１", tel: "0749593377", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "彦根相互事業協同組合", type: "登録支援機関", address: "滋賀県彦根市西沼波町１６４番地", tel: "0749210333", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "ハイテック協同組合", type: "登録支援機関", address: "滋賀県甲賀市土山町北土山２２７８－８", tel: "0748706074", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社アイテム", type: "登録支援機関", address: "滋賀県甲賀市水口町１－１４５", tel: "0748650555", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社木島エージェンシー", type: "登録支援機関", address: "滋賀県彦根市大堀町４１２番地１", tel: "0749291777", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社アドヴァンス", type: "登録支援機関", address: "滋賀県彦根市地蔵町３９番地６", tel: "0749207955", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "滋賀国際事業支援協同組合", type: "登録支援機関", address: "滋賀県守山市今宿二丁目９番２２号", tel: "0775811457", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "林　秀樹(林秀樹行政書士事務所)", type: "登録支援機関", address: "滋賀県草津市草津１丁目１９番２３号", tel: "0775632957", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "びわこ経済交流協同組合", type: "登録支援機関", address: "滋賀県湖南市中央五丁目６２番地", tel: "0748728822", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社スタンディング・オン", type: "登録支援機関", address: "滋賀県大津市大萱一丁目１８番１４号", tel: "0775434106", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "びわそう協同組合", type: "登録支援機関", address: "滋賀県草津市木川町９５１番地の５９", tel: "0775356721", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "パン・エイシア事業協同組合", type: "登録支援機関", address: "滋賀県湖南市朝国２２", tel: "0748729282", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "滋賀県商工企業協同組合", type: "登録支援機関", address: "滋賀県長浜市湖北町速水２７１０番地", tel: "0749782112", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワオナス", type: "登録支援機関", address: "滋賀県東近江市宮川町６８３番地１０３", tel: "0748554877", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "社会福祉法人近江ふるさと会", type: "登録支援機関", address: "滋賀県彦根市開出今町１３４３－３", tel: "0749213200", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "梅井　茉実香(プラム行政書士事務所)", type: "登録支援機関", address: "滋賀県大津市藤尾奥町１５番１８号", tel: "07041331165", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "澤村　浩正（澤村行政書士国際法務事務所　澤村経営労務管理事務所）", type: "登録支援機関", address: "滋賀県彦根市開出今町１４８８番地１５", tel: "0749261038", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "光栄産業有限会社", type: "登録支援機関", address: "滋賀県蒲生郡竜王町大字岡屋１５３５番地１", tel: "0748581800", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "ＡＳＩＡＮ　ＢＲＩＤＧＥ協同組合", type: "登録支援機関", address: "滋賀県蒲生郡竜王町大字岡屋１５３５番地の１", tel: "0748582306", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市祇園町５４６番地１", tel: "0749519039", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県湖南市水戸町１１番地７ウェル水戸１F", tel: "0748780558", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県東近江市小田苅町８３４番地の１", tel: "0749451587", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市八島町９９番地５５グランシャリオ八島２０３号", tel: "0749534905", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市西上坂町９６３番地１", tel: "0749505065", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市野村八丁目６番２５号", tel: "0775610881", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市戸賀町２５６番地の１", tel: "0749213066", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市神照町１１８番地１", tel: "0749519058", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市南山田町１１００－１１", tel: "0775097537", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市東草津１丁目４－５３　吉田ビル３階３号", tel: "0775161711", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市和邇中浜３７０番地１　ニ国屋ビル３Ｆ", tel: "0775994601", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市戸賀町２５６番地の１", tel: "0749212229", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県守山市吉身４－７－２９", tel: "09085240556", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市口分田町２４４番地１", tel: "0749650919", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市草津三丁目７番８号", tel: "0775673454", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県湖南市下田２７０７ー３ビアンテタカマツⅡ１０１号室", tel: "0748751936", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市東草津一丁目７番４６号", tel: "05068656960", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市仰木６－１８－２４", tel: "0775737827", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県甲賀市甲南町柑子７６９番地", tel: "0748695077", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市馬場町２０７番地４６", tel: "05031520801", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県野洲市高木６７５番地", tel: "0748325668", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県甲賀市水口町下山６６６番地８５", tel: "0748631004", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市志那中町１０２番地１", tel: "0775685090", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県東近江市五個荘奥町３３０番地", tel: "0748488028", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県東近江市種町１７１７番地", tel: "0748428419", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市八幡東町５０２番地", tel: "0749507153", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市列見町２９２番地", tel: "0749532304", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県愛知郡愛荘町元持４７２番地", tel: "08058110440", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県近江八幡市中村町７番地１８", tel: "0748432057", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市北小松１５９０番地の２ヴェルドール琵琶湖リゾート１００２", tel: "09037069331", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市南笠東二丁目７番７号", tel: "0775359129", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市西上坂町１０３６番地１", tel: "0749643667", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県近江八幡市鷹飼町６５６－２", tel: "0748430916", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県甲賀市甲南町新治２０９７番地", tel: "0748868787", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県栗東市安養寺八丁目４番１号\nＣＲＡＳＴＩＮＥ 安養寺３階－Ｊ号室", tel: "0775963312", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県愛知郡愛荘町東円堂２５１１番１６号", tel: "0749492245", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市野田山町９０１番地２", tel: "09073662529", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市西渋川１丁目４－６　MAEDA第２ビル", tel: "0775995573", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市城町一丁目６番１８号", tel: "0749203365", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市野路町６６７番地５", tel: "0775694322", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市芦浦町７７０番地１", tel: "09049091510", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県東近江市五箇荘中町６７番地", tel: "0748293388", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県栗東市手原五丁目２番２２号", tel: "0775521510", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県近江八幡市堀上町１２２番地の１", tel: "0748333036", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市本堅田三丁目２９番２１号", tel: "0775739990", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市京町１丁目３－４　１A", tel: "07023230667,
0749473767", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市竜が丘２番１－６０６号", tel: "0775251634", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県犬上郡多賀町大字萱原１２９６番地２", tel: "0749490294", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県蒲生郡日野町大字西大路殿町２０２８番地", tel: "0748520566", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市若竹町８－３８大五ビル３階", tel: "0775586090", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県近江八幡市鷹飼町４５５番地８MKKビル３F２号", tel: "0748332180", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県東近江市建部上中町９１番地２", tel: "0748252343", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市田村町字仙堂前１１９９番地", tel: "0749646010", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市木之本町木之本１５３４番地２、１０１号", tel: "0749824007", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県栗東市綣２ー４－５　ウイングプラザ２Ｆ", tel: "0775545500", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県米原市間田２８９番地の１", tel: "0749560099", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市大路一丁目１番地１号", tel: "05054786430", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県湖南市柑子袋字高樋５６８番１９", tel: "0792803862", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市矢橋町２０８０番地３", tel: "0775646277", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市湖北町延勝寺１８４４", tel: "0749798100", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県東近江市八日市上之町２番７号", tel: "09027042876", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県近江八幡市中村町２０－１５コルージャビル５０１号", tel: "0120693628", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県守山市森川原町２５６番地１号", tel: "0775993762", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市稲津一丁目３番５４号", tel: "0775725887", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県長浜市八幡中山町２５１番地", tel: "0749686177", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県野洲市冨波甲１１６１－８", tel: "0775876272", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市安清町５－５１", tel: "0749475406", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県東近江市八日市清水２丁目７番５号", tel: "0748223066", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市鏡が浜４番１－１１０６号", tel: "08077513252", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市本宮二丁目５番１号ビワハイツ４０５", tel: "08092785155", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市松が丘６丁目５番１号", tel: "0775488660", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県草津市野村２丁目３－１８", tel: "0775612286", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県湖南市三雲３番地２０", tel: "09098777777", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市戸賀町１００番地１０", tel: "08042346869", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市日夏町８２９番地", tel: "09050437812", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県大津市湖城が丘１９番９号", tel: "0775227650", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県米原市坂口１５８番地", tel: "0749553796", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県湖南市丸山四丁目５番１号", tel: "0748770187", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県東近江市東沖野三丁目１２－２", tel: "0748232425", visa: ["tokutei1"], prefId: "shiga", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "滋賀県彦根市新海浜二丁目１０番地８", tel: "0749205176", visa: ["tokutei1"], prefId: "shiga", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();