// 登録支援機関データ - yamagata (34件)
(function(){
  const data = [
    { name: "株式会社マイセルフ", type: "登録支援機関", address: "山形県東根市中央二丁目１２番７号", tel: "0237530886", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "協同組合パートナー・ライジング・サポート", type: "登録支援機関", address: "山形県米沢市大字川井２３５０－４", tel: "0238283287", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "東方流通協同組合", type: "登録支援機関", address: "山形県米沢市大字竹井８９９－３", tel: "0238285628", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "ＳＩＳＥＩ協同組合", type: "登録支援機関", address: "山形県山形市大字漆山３４２３－１", tel: "0236642644", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "キャプラスクインターナショナル合同会社", type: "登録支援機関", address: "山形県上山市中生居５４５", tel: "05054348065", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ＤＭＣ天童温泉", type: "登録支援機関", address: "山形県天童市鎌田本町二丁目５番４３号", tel: "0236546699", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県米沢市川井９７０番地の７", tel: "0238281090", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県鶴岡市千石町３番８号", tel: "0235261275", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県東村山郡山辺町近江１７番４５号", tel: "0236739115", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県鶴岡市大山字中道７４番地の１", tel: "0235332117", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県山形市東原町二丁目５番２６号", tel: "08031935015", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県東置賜郡高畠町大字入生田３１０７番地の６", tel: "0238574603", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県鶴岡市日和田町１番３号", tel: "0235297717", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県寒河江市新山町１番地１０", tel: "0237850570", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県山形市鉄砲町二丁目１２番２８号", tel: "09045517433", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県天童市大字大清水５３３番地の１", tel: "0236540855", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県天童市鎌田本町一丁目１番３０号", tel: "0236542211", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県米沢市金池七丁目５番２１号", tel: "0238401414", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県米沢市大字川井４０８１番地", tel: "0238339830", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県山形市香澄町二丁目８番１号７階", tel: "0236243510", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県鶴岡市文園町２番５９号", tel: "09045591930", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県東置賜郡川西町大字上小松３２９３番地の３", tel: "0238541101", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県山形市みはらしの丘四丁目１５番地３", tel: "0236871016", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県東根市中央二丁目１２番７号", tel: "0237488756", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県山形市山家町二丁目７番１７号", tel: "0236871882", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県米沢市大字長手１１２１番地１０２号室", tel: "0238498177", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県鶴岡市板井川字片茎２６３番地", tel: "0235781530", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県天童市糠塚一丁目６番２６号", tel: "0236654568", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県酒田市若浜町６番２５号", tel: "0234241890", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県寒河江市大字島３８３番地の２３", tel: "0237867198", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県酒田市千石町二丁目１３番１０号", tel: "0234210113", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県山形市あこや町二丁目２番３９号", tel: "0236317550", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県鶴岡市大塚町１６番４０号", tel: "0235246134", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山形県山形市山家町一丁目６番５５号", tel: "08031908289", visa: ["tokutei1"], prefId: "yamagata", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();