// 登録支援機関データ - yamanashi (55件)
(function(){
  const data = [
    { name: "株式会社ネクストエイジ", type: "登録支援機関", address: "山梨県中巨摩郡昭和町河東中島９６３番地１", tel: "0552753216", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "藤原　進（ビジネスサポート行政書士事務所）", type: "登録支援機関", address: "山梨県中巨摩郡昭和町清水新居１６６６", tel: "0552330211", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "大森会計事務所株式会社", type: "登録支援機関", address: "山梨県富士吉田市向原一丁目２７番２１号", tel: "0555287552", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社キャリアポケット", type: "登録支援機関", address: "山梨県中巨摩郡昭和町清水新居８９７番地３", tel: "0552888872", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "社会福祉法人光風会", type: "登録支援機関", address: "山梨県甲州市塩山西野原６０３番地", tel: "0553337511", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "富士交流サービス協同組合", type: "登録支援機関", address: "山梨県大月市駒橋１－６－１６", tel: "0554231331", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "ビジネスグリット株式会社", type: "登録支援機関", address: "山梨県甲府市高畑一丁目６番７号", tel: "0552315251", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "丹澤　仁（行政書士たんざわ事務所）", type: "登録支援機関", address: "山梨県甲府市千塚３－２－２６グリーンタウンE１０１", tel: "0552535335", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "やまなしアパレルＡＣＦ事業協同組合", type: "登録支援機関", address: "山梨県甲府市元紺屋町４８番地アンローブ工場内", tel: "0552547474", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "富士経友会協同組合", type: "登録支援機関", address: "山梨県富士吉田市上吉田５５３８番地１オサダビル２階", tel: "0555228855", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県都留市四日市場８９番地６", tel: "08053820124", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県都留市平栗１０５５番地の１", tel: "0554432602", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市下飯田３－６－２", tel: "0552676276", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市後屋町３４４番地２", tel: "0552881160", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南アルプス市小笠原４０３ー１", tel: "0552253730", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県笛吹市一宮町田中１２２３番地１０２", tel: "0553348387", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南アルプス市藤田１３８５番地２", tel: "08098061001", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市上曽根町３６６２番地１７５", tel: "0552701625", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市中央２-３-７", tel: "0552245680", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市池田一丁目５番９号", tel: "0552520555", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県都留市十日市場１４２０番地", tel: "0554 436158", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲斐市亀沢６９４９番地９６", tel: "0552603100", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県山梨市小原東１１１番地１", tel: "0262145161", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県中巨摩郡昭和町清水新居８９７番地３Ｎビル２０２号", tel: "0552699020", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南都留郡山中湖村山中１８４番地３", tel: "0552254747", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県笛吹市石和町小石和３０７番地２", tel: "0489539022", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南巨摩郡身延町手打沢１２７１番地", tel: "0556422045", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県中央市西花輪４５８８番地５", tel: "0552697257", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市国母四丁目１７番２７号", tel: "0552285577", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県笛吹市石和町東油川９番地１", tel: "0552427308", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市丸の内二丁目３０番５号", tel: "08080519284", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市下飯田３－６－２－２Ｆ", tel: "05017914520", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲斐市篠原１４３３番地", tel: "0552781147", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県上野原市コモアしおつ三丁目１９番２号", tel: "0554568046", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県中巨摩郡昭和町河西１０２３番地１", tel: "0552696047", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南都留郡富士河口湖町河口２７４６番地２", tel: "0555307374", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県中央市極楽寺９１１番地２", tel: "0552410720", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県都留市井倉２０６番地", tel: "0554432314", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市中央一丁目１２番４２号甲府第一法曹ビル３－Ａ", tel: "0552215166", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県韮崎市龍岡町下條東割９３９－２、１０２", tel: "09080422473", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市大里町２８３１番地１", tel: "0552888106", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市丸の内二丁目３０番５号", tel: "0552876811", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南巨摩郡身延町上之平１９００番地", tel: "0556360311", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県笛吹市春日居町国府４３６番地", tel: "0553264771", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県都留市大野２８４４番地１２２", tel: "0554456699", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南アルプス市寺部７６０番地", tel: "0552427340", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市下石田２丁目１０番４号", tel: "05031160370", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南都留郡富士河口湖町船津１３３９番地の１", tel: "0555721215", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県都留市つる一丁目２番６号", tel: "0554567997", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県中巨摩郡昭和町清水新居１６６６番地", tel: "0552366111", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市東下条町２０４番地１", tel: "0552742531", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県大月市猿橋町小沢１４３５番地", tel: "0554221036", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県甲府市国母六丁目２番３号", tel: "0552266531", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県中巨摩郡昭和町河東中島９６３番地１", tel: "0552753213", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
    { name: "株式会社ワンステップイースト", type: "登録支援機関", address: "山梨県南都留郡忍野村忍草３４９０番地１", tel: "0555843639", visa: ["tokutei1"], prefId: "yamanashi", districtId: null },
  ];
  if (window.VISA_DATA) VISA_DATA.agencies.push(...data);
})();